/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable no-undefined */
/* eslint-disable camelcase */

/*globals
  global
  test
  $
*/

import { nextLaunchManager } from '@app/js/plugins/nextLaunch/nextLaunch';
import { settingsManager } from '@app/js/settingsManager/settingsManager';

const setUrl = (url) => {
  const host = url.split('/')[2] || '';
  let search = url.split('?')[1] || '';
  search = search !== '' ? `?${search}` : '';

  global.window = Object.create(window);
  Object.defineProperty(window, 'location', {
    value: {
      href: url,
      host: host,
      search: search,
    },
    writable: true,
  });
};

const resp = {
  count: 189,
  next: 'https://ll.thespacedevs.com/2.0.0/launch/upcoming/?format=json&limit=20&offset=20',
  previous: null,
  results: [
    {
      id: '24cfdd1c-d150-4da3-8030-d11b2e0fc694',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/24cfdd1c-d150-4da3-8030-d11b2e0fc694/?format=json',
      launch_library_id: null,
      slug: 'long-march-2c-yaogan-30-10',
      name: 'Long March 2C | Yaogan-30-10',
      status: { id: 1, name: 'Go' },
      net: '2021-07-19T00:15:00Z',
      window_end: '2021-07-19T00:26:00Z',
      window_start: '2021-07-19T00:08:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: null,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 88, url: 'https://ll.thespacedevs.com/2.2.0/agencies/88/?format=json', name: 'China Aerospace Science and Technology Corporation', type: 'Government' },
      rocket: { id: 2970, configuration: { id: 61, launch_library_id: 75, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/61/?format=json', name: 'Long March 2', family: 'Long March 2', full_name: 'Long March 2C', variant: 'C' } },
      mission: {
        id: 1396,
        launch_library_id: null,
        name: 'Yaogan-30-10',
        description: 'NOTE: Payload identity not confirmed.\r\n\r\nThe Yaogan-30 is a series of military remote sensing satellites which are launched in triplets. The satellites are spaced by 120° in their orbit.',
        launch_designator: null,
        type: 'Government/Top Secret',
        orbit: { id: 8, name: 'Low Earth Orbit', abbrev: 'LEO' },
      },
      pad: {
        id: 66,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/66/?format=json',
        agency_id: 17,
        name: 'Launch Complex 3 ( LC-3 ) ( LA-1 )',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/Xichang_Satellite_Launch_Center',
        map_url: 'https://www.google.com/maps/?q=28.246017,102.026556',
        latitude: '28.246017',
        longitude: '102.026556',
        location: {
          id: 16,
          url: 'https://ll.thespacedevs.com/2.2.0/location/16/?format=json',
          name: "Xichang Satellite Launch Center, People's Republic of China",
          country_code: 'CHN',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_16_20200803142513.jpg',
          total_launch_count: 105,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_66_20200803143611.jpg',
        total_launch_count: 37,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/long2520march25202_image_20190222031200.jpeg',
      infographic: null,
      program: [],
    },
    {
      id: 'd0f9cb4e-8efe-4b70-a675-3f087acd6f74',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/d0f9cb4e-8efe-4b70-a675-3f087acd6f74/?format=json',
      launch_library_id: null,
      slug: 'new-shepard-ns-16',
      name: 'New Shepard | NS-16',
      status: { id: 1, name: 'Go' },
      net: '2021-07-20T13:00:00Z',
      window_end: '2021-07-20T13:00:00Z',
      window_start: '2021-07-20T13:00:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: null,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 141, url: 'https://ll.thespacedevs.com/2.2.0/agencies/141/?format=json', name: 'Blue Origin', type: 'Commercial' },
      rocket: { id: 2878, configuration: { id: 137, launch_library_id: 9999, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/137/?format=json', name: 'New Shepard', family: 'Blue Origin', full_name: 'New Shepard', variant: '' } },
      mission: { id: 1292, launch_library_id: null, name: 'NS-16', description: "First crewed flight of Blue Origin's New Shepard rocket.", launch_designator: null, type: 'Tourism', orbit: { id: 15, name: 'Suborbital', abbrev: 'Sub' } },
      pad: {
        id: 90,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/90/?format=json',
        agency_id: 141,
        name: 'West Texas Suborbital Launch Site/ Corn Ranch',
        info_url: 'http://www.blueorigin.com',
        wiki_url: 'https://en.wikipedia.org/wiki/Corn_Ranch',
        map_url: "https://www.google.com/maps/place/31%C2%B025'22.4%22N+104%C2%B045'25.6%22W",
        latitude: '31.422878000000000',
        longitude: '-104.757121000000000',
        location: {
          id: 29,
          url: 'https://ll.thespacedevs.com/2.2.0/location/29/?format=json',
          name: 'Corn Ranch, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_29_20200803142436.jpg',
          total_launch_count: 15,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_90_20200803143233.jpg',
        total_launch_count: 15,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/new2520shepard_image_20190207032624.jpeg',
      infographic: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/new2520shepard_infographic_20210716202126.jpeg',
      program: [],
    },
    {
      id: '27fd5d5a-6935-4697-98b4-b409f029e2f0',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/27fd5d5a-6935-4697-98b4-b409f029e2f0/?format=json',
      launch_library_id: 1597,
      slug: 'proton-m-mlm-nauka',
      name: 'Proton-M | MLM Nauka',
      status: { id: 1, name: 'Go' },
      net: '2021-07-21T14:58:21Z',
      window_end: '2021-07-21T14:58:21Z',
      window_start: '2021-07-21T14:58:21Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 96, url: 'https://ll.thespacedevs.com/2.2.0/agencies/96/?format=json', name: 'Khrunichev State Research and Production Space Center', type: 'Government' },
      rocket: { id: 124, configuration: { id: 152, launch_library_id: 186, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/152/?format=json', name: 'Proton-M', family: 'Proton / UR-500', full_name: 'Proton-M', variant: '' } },
      mission: {
        id: 656,
        launch_library_id: 843,
        name: 'MLM Nauka',
        description:
          'Nauka (which means "Science" in Russian), also known as Multipurpose Laboratory Module (MLM), is a new module of the russian segment of the ISS. It will dock at Zvezda\'s nadir port, replacing the Pirs module occupying it since September 2001. The Nauka module is designed to be used for experiments, docking and cargo as well as serve as a crew work and rest area. It is equipped with full guidance and navigation control including engines and an attitude control system that can be used as a backup by the ISS. The Nauka module also brings the European Robotic Arm, for which a spare elbow joint was already launched in 2010, to the orbital laboratory.',
        launch_designator: null,
        type: 'Human Exploration',
        orbit: { id: 8, name: 'Low Earth Orbit', abbrev: 'LEO' },
      },
      pad: {
        id: 15,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/15/?format=json',
        agency_id: null,
        name: '200/39 (200L)',
        info_url: null,
        wiki_url: '',
        map_url: 'http://maps.google.com/maps?q=46.040+N,+63.032+E',
        latitude: '46.039984',
        longitude: '63.032093',
        location: {
          id: 15,
          url: 'https://ll.thespacedevs.com/2.2.0/location/15/?format=json',
          name: 'Baikonur Cosmodrome, Republic of Kazakhstan',
          country_code: 'KAZ',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_15_20200803142517.jpg',
          total_launch_count: 472,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_15_20200803143530.jpg',
        total_launch_count: 39,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/proton-m_image_20201205235758.jpg',
      infographic: null,
      program: [],
    },
    {
      id: 'be2342f2-5ae2-4a91-a64f-681106da2aab',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/be2342f2-5ae2-4a91-a64f-681106da2aab/?format=json',
      launch_library_id: 1344,
      slug: 'ariane-5-eca-star-one-d2-eutelsat-quantum',
      name: 'Ariane 5 ECA | Star One D2 & Eutelsat Quantum',
      status: { id: 2, name: 'TBD' },
      net: '2021-07-27T21:14:00Z',
      window_end: '2021-07-27T21:14:00Z',
      window_start: '2021-07-27T21:14:00Z',
      inhold: false,
      tbdtime: true,
      tbddate: true,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 115, url: 'https://ll.thespacedevs.com/2.2.0/agencies/115/?format=json', name: 'Arianespace', type: 'Commercial' },
      rocket: { id: 2684, configuration: { id: 20, launch_library_id: 27, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/20/?format=json', name: 'Ariane 5 ECA', family: 'Ariane 5', full_name: 'Ariane 5 ECA', variant: 'ECA' } },
      mission: {
        id: 1245,
        launch_library_id: null,
        name: 'Star One D2 & Eutelsat Quantum',
        description:
          'Star One D2 is a 6.2 tons satellite built by Space Systems Loral for operator Star One, subsidiary of Brazilian Embratel. Its architecture is based on a SSL-1300 platform and equipped with C, X, Ku and Ka-band transceivers. It will provide communications services to Latin America for at least 15 years.\r\n\r\nEutelsat Quantum is an experimental communications satellite carrying a payload able to be reconfigured by software. It is developed by ESA, Eutelsat and Airbus Defence and Space.',
        launch_designator: null,
        type: 'Communications',
        orbit: { id: 2, name: 'Geostationary Transfer Orbit', abbrev: 'GTO' },
      },
      pad: {
        id: 77,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/77/?format=json',
        agency_id: null,
        name: 'Ariane Launch Area 3',
        info_url: null,
        wiki_url: 'http://en.wikipedia.org/wiki/ELA-3',
        map_url: 'https://www.google.com/maps/?q=5.239,-52.769',
        latitude: '5.239',
        longitude: '-52.768',
        location: {
          id: 13,
          url: 'https://ll.thespacedevs.com/2.2.0/location/13/?format=json',
          name: 'Kourou, French Guiana',
          country_code: 'GUF',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_13_20200803142412.jpg',
          total_launch_count: 152,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_77_20200803143458.jpg',
        total_launch_count: 110,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/ariane252052520eca_image_20190224012333.jpeg',
      infographic: null,
      program: [],
    },
    {
      id: '6b9f9fe6-7f94-498b-a664-7c9e42dbe76d',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/6b9f9fe6-7f94-498b-a664-7c9e42dbe76d/?format=json',
      launch_library_id: null,
      slug: 'falcon-9-block-5-starlink-29',
      name: 'Falcon 9 Block 5 | Starlink 29',
      status: { id: 2, name: 'TBD' },
      net: '2021-07-30T00:00:00Z',
      window_end: '2021-07-30T00:00:00Z',
      window_start: '2021-07-30T00:00:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: null,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 121, url: 'https://ll.thespacedevs.com/2.2.0/agencies/121/?format=json', name: 'SpaceX', type: 'Commercial' },
      rocket: { id: 2958, configuration: { id: 164, launch_library_id: 188, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/164/?format=json', name: 'Falcon 9 Block 5', family: 'Falcon', full_name: 'Falcon 9 Block 5', variant: 'Block 5' } },
      mission: {
        id: 1380,
        launch_library_id: null,
        name: 'Starlink 29',
        description: "A batch of 60 satellites for Starlink mega-constellation - SpaceX's project for space-based Internet communication system.",
        launch_designator: null,
        type: 'Communications',
        orbit: { id: 13, name: 'Polar Orbit', abbrev: 'PO' },
      },
      pad: {
        id: 72,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/72/?format=json',
        agency_id: null,
        name: 'Unknown Pad',
        info_url: null,
        wiki_url: '',
        map_url: '',
        latitude: '28.458',
        longitude: '-80.528',
        location: {
          id: 12,
          url: 'https://ll.thespacedevs.com/2.2.0/location/12/?format=json',
          name: 'Cape Canaveral, FL, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg',
          total_launch_count: 223,
          total_landing_count: 21,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_72_20200803143403.jpg',
        total_launch_count: 0,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/falcon2520925_image_20210619160237.png',
      infographic: null,
      program: [],
    },
    {
      id: 'f1bcfbf6-d00d-42d7-bc68-82252817a57e',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/f1bcfbf6-d00d-42d7-bc68-82252817a57e/?format=json',
      launch_library_id: 2055,
      slug: 'atlas-v-n22-cst-100-starliner-orbital-flight-tes-2',
      name: 'Atlas V N22 | CST-100 Starliner Orbital Flight Test 2 (Uncrewed)',
      status: { id: 1, name: 'Go' },
      net: '2021-07-30T18:53:00Z',
      window_end: '2021-07-30T18:53:00Z',
      window_start: '2021-07-30T18:53:00Z',
      inhold: false,
      tbdtime: true,
      tbddate: true,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 124, url: 'https://ll.thespacedevs.com/2.2.0/agencies/124/?format=json', name: 'United Launch Alliance', type: 'Commercial' },
      rocket: { id: 2702, configuration: { id: 166, launch_library_id: 118, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/166/?format=json', name: 'Atlas V N22', family: 'Atlas', full_name: 'Atlas V N22', variant: 'V N22' } },
      mission: {
        id: 1109,
        launch_library_id: 1305,
        name: 'CST-100 Starliner Orbital Flight Test 2 (Uncrewed)',
        description:
          'This is the second uncrewed test flight for the Starliner spacecraft. Reflight of the OFT mission will allow Boeing to demonstrate readiness of the spacecraft and implement corrections to the problems which were found during the first OFT flight.',
        launch_designator: null,
        type: 'Test Flight',
        orbit: { id: 8, name: 'Low Earth Orbit', abbrev: 'LEO' },
      },
      pad: {
        id: 29,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/29/?format=json',
        agency_id: null,
        name: 'Space Launch Complex 41',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_41',
        map_url: 'http://maps.google.com/maps?q=28.58341025,-80.58303644',
        latitude: '28.58341025',
        longitude: '-80.58303644',
        location: {
          id: 12,
          url: 'https://ll.thespacedevs.com/2.2.0/location/12/?format=json',
          name: 'Cape Canaveral, FL, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg',
          total_launch_count: 223,
          total_landing_count: 21,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_29_20200803143528.jpg',
        total_launch_count: 72,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/atlas2520v2520n22_image_20190224012241.jpeg',
      infographic: null,
      program: [
        {
          id: 5,
          url: 'https://ll.thespacedevs.com/2.2.0/program/5/?format=json',
          name: 'Commercial Crew Program',
          description:
            'The Commercial Crew Program (CCP) is a human spaceflight program operated by NASA, in association with American aerospace manufacturers Boeing and SpaceX. The program conducts rotations between the expeditions of the International Space Station program, transporting crews to and from the International Space Station (ISS) aboard Boeing Starliner and SpaceX Crew Dragon capsules, in the first crewed orbital spaceflights operated by private companies.',
          agencies: [
            { id: 80, url: 'https://ll.thespacedevs.com/2.2.0/agencies/80/?format=json', name: 'Boeing', type: 'Commercial' },
            { id: 44, url: 'https://ll.thespacedevs.com/2.2.0/agencies/44/?format=json', name: 'National Aeronautics and Space Administration', type: 'Government' },
            { id: 121, url: 'https://ll.thespacedevs.com/2.2.0/agencies/121/?format=json', name: 'SpaceX', type: 'Commercial' },
          ],
          image_url: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/commercial2520_program_20200820201209.png',
          start_date: '2011-04-18T00:00:00Z',
          end_date: null,
          info_url: 'https://www.nasa.gov/exploration/commercial/crew/index.html',
          wiki_url: 'https://en.wikipedia.org/wiki/Commercial_Crew_Program',
        },
        {
          id: 17,
          url: 'https://ll.thespacedevs.com/2.2.0/program/17/?format=json',
          name: 'International Space Station',
          description:
            'The International Space Station programme is tied together by a complex set of legal, political and financial agreements between the sixteen nations involved in the project, governing ownership of the various components, rights to crewing and utilization, and responsibilities for crew rotation and resupply of the International Space Station. It was conceived in 1984 by President Ronald Reagan, during the Space Station Freedom project as it was originally called.',
          agencies: [
            { id: 16, url: 'https://ll.thespacedevs.com/2.2.0/agencies/16/?format=json', name: 'Canadian Space Agency', type: 'Government' },
            { id: 27, url: 'https://ll.thespacedevs.com/2.2.0/agencies/27/?format=json', name: 'European Space Agency', type: 'Multinational' },
            { id: 37, url: 'https://ll.thespacedevs.com/2.2.0/agencies/37/?format=json', name: 'Japan Aerospace Exploration Agency', type: 'Government' },
            { id: 44, url: 'https://ll.thespacedevs.com/2.2.0/agencies/44/?format=json', name: 'National Aeronautics and Space Administration', type: 'Government' },
            { id: 63, url: 'https://ll.thespacedevs.com/2.2.0/agencies/63/?format=json', name: 'Russian Federal Space Agency (ROSCOSMOS)', type: 'Government' },
          ],
          image_url: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/international2_program_20201129184745.png',
          start_date: '1998-11-20T06:40:00Z',
          end_date: null,
          info_url: 'https://www.nasa.gov/mission_pages/station/main/index.html',
          wiki_url: 'https://en.wikipedia.org/wiki/International_Space_Station_programme',
        },
      ],
    },
    {
      id: 'e4200e5c-2726-43f2-8439-36bd1be59821',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/e4200e5c-2726-43f2-8439-36bd1be59821/?format=json',
      launch_library_id: null,
      slug: 'falcon-9-block-5-starlink-30',
      name: 'Falcon 9 Block 5 | Starlink 30',
      status: { id: 2, name: 'TBD' },
      net: '2021-07-31T00:00:00Z',
      window_end: '2021-07-31T00:00:00Z',
      window_start: '2021-07-31T00:00:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: null,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 121, url: 'https://ll.thespacedevs.com/2.2.0/agencies/121/?format=json', name: 'SpaceX', type: 'Commercial' },
      rocket: { id: 2959, configuration: { id: 164, launch_library_id: 188, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/164/?format=json', name: 'Falcon 9 Block 5', family: 'Falcon', full_name: 'Falcon 9 Block 5', variant: 'Block 5' } },
      mission: {
        id: 1381,
        launch_library_id: null,
        name: 'Starlink 30',
        description: "A batch of 60 satellites for Starlink mega-constellation - SpaceX's project for space-based Internet communication system.",
        launch_designator: null,
        type: 'Communications',
        orbit: { id: 13, name: 'Polar Orbit', abbrev: 'PO' },
      },
      pad: {
        id: 72,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/72/?format=json',
        agency_id: null,
        name: 'Unknown Pad',
        info_url: null,
        wiki_url: '',
        map_url: '',
        latitude: '28.458',
        longitude: '-80.528',
        location: {
          id: 12,
          url: 'https://ll.thespacedevs.com/2.2.0/location/12/?format=json',
          name: 'Cape Canaveral, FL, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg',
          total_launch_count: 223,
          total_landing_count: 21,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_72_20200803143403.jpg',
        total_launch_count: 0,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/falcon2520925_image_20210619160353.png',
      infographic: null,
      program: [],
    },
    {
      id: '6e5725b3-d0e9-4484-9d79-514fe8b978be',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/6e5725b3-d0e9-4484-9d79-514fe8b978be/?format=json',
      launch_library_id: 1955,
      slug: 'soyuz-21afregat-m-meteor-m-no2-3',
      name: 'Soyuz 2.1a/Fregat-M | Meteor-M No.2-3',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-01T00:00:00Z',
      window_end: '2021-08-01T00:00:00Z',
      window_start: '2021-08-01T00:00:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: -1,
      holdreason: null,
      failreason: null,
      hashtag: null,
      launch_service_provider: { id: 63, url: 'https://ll.thespacedevs.com/2.2.0/agencies/63/?format=json', name: 'Russian Federal Space Agency (ROSCOSMOS)', type: 'Government' },
      rocket: {
        id: 2510,
        configuration: { id: 45, launch_library_id: 83, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/45/?format=json', name: 'Soyuz 2.1a/Fregat-M', family: 'Soyuz', full_name: 'Soyuz 2.1a Fregat-M', variant: 'Fregat-M' },
      },
      mission: null,
      pad: {
        id: 83,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/83/?format=json',
        agency_id: 63,
        name: 'Cosmodrome Site 1S',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/Vostochny_Cosmodrome',
        map_url: 'https://www.google.ee/maps/place/51Â°53\'03.8"N+128Â°20\'02.2"E/',
        latitude: '51.884395',
        longitude: '128.333932',
        location: {
          id: 18,
          url: 'https://ll.thespacedevs.com/2.2.0/location/18/?format=json',
          name: 'Vostochny Cosmodrome, Siberia, Russian Federation',
          country_code: 'RUS',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_18_20200803142401.jpg',
          total_launch_count: 10,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_83_20200803143544.jpg',
        total_launch_count: 10,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/soyuz25202.1a_image_20190726062341.png',
      infographic: null,
      program: [],
    },
    {
      id: '83f38440-8a73-4209-911d-fb4f30b1bda9',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/83f38440-8a73-4209-911d-fb4f30b1bda9/?format=json',
      launch_library_id: 1523,
      slug: 'atlas-v-551-ussf-12',
      name: 'Atlas V 551 | USSF-12',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-01T00:00:00Z',
      window_end: '2021-08-01T00:00:00Z',
      window_start: '2021-08-01T00:00:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: -1,
      holdreason: null,
      failreason: null,
      hashtag: null,
      launch_service_provider: { id: 124, url: 'https://ll.thespacedevs.com/2.2.0/agencies/124/?format=json', name: 'United Launch Alliance', type: 'Commercial' },
      rocket: { id: 147, configuration: { id: 27, launch_library_id: 37, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/27/?format=json', name: 'Atlas V 551', family: 'Atlas', full_name: 'Atlas V 551', variant: '551' } },
      mission: null,
      pad: {
        id: 29,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/29/?format=json',
        agency_id: null,
        name: 'Space Launch Complex 41',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_41',
        map_url: 'http://maps.google.com/maps?q=28.58341025,-80.58303644',
        latitude: '28.58341025',
        longitude: '-80.58303644',
        location: {
          id: 12,
          url: 'https://ll.thespacedevs.com/2.2.0/location/12/?format=json',
          name: 'Cape Canaveral, FL, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg',
          total_launch_count: 223,
          total_landing_count: 21,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_29_20200803143528.jpg',
        total_launch_count: 72,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/atlas2520v2520551_image_20190224012316.jpeg',
      infographic: null,
      program: [],
    },
    {
      id: 'c46cfec6-f135-41f9-995f-9482b8cbe668',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/c46cfec6-f135-41f9-995f-9482b8cbe668/?format=json',
      launch_library_id: 1339,
      slug: 'vega-pleiades-neo-4',
      name: 'Vega | Pléiades Neo 4',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-10T01:50:00Z',
      window_end: '2021-08-10T01:50:00Z',
      window_start: '2021-08-10T01:50:00Z',
      inhold: false,
      tbdtime: true,
      tbddate: true,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 115, url: 'https://ll.thespacedevs.com/2.2.0/agencies/115/?format=json', name: 'Arianespace', type: 'Commercial' },
      rocket: { id: 179, configuration: { id: 167, launch_library_id: 18, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/167/?format=json', name: 'Vega', family: 'Vega', full_name: 'Vega', variant: '' } },
      mission: {
        id: 1377,
        launch_library_id: null,
        name: 'Pléiades Neo 4',
        description:
          'Pléiades Neo is a constellation of four optical high-resolution Earth observation satellites built and operated by Airbus. It is a dual purpose constellation, serving both civilian and military purposes. Pléiades Neo 4 is the second satellite in the constellation which is to deliver imagery with spatial resolution of 30 cm. It is launched along with several rideshare payloads.',
        launch_designator: null,
        type: 'Government/Top Secret',
        orbit: { id: 17, name: 'Sun-Synchronous Orbit', abbrev: 'SSO' },
      },
      pad: {
        id: 34,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/34/?format=json',
        agency_id: 115,
        name: 'Ariane Launch Area 1',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/ELA-1',
        map_url: 'https://www.google.com/maps/?q=5.239,-52.775',
        latitude: '5.236',
        longitude: '-52.775',
        location: {
          id: 13,
          url: 'https://ll.thespacedevs.com/2.2.0/location/13/?format=json',
          name: 'Kourou, French Guiana',
          country_code: 'GUF',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_13_20200803142412.jpg',
          total_launch_count: 152,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_34_20200803143527.jpg',
        total_launch_count: 18,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/vega_image_20201111143622.jpeg',
      infographic: null,
      program: [],
    },
    {
      id: '6476f988-3289-4065-95f4-266b86774d3d',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/6476f988-3289-4065-95f4-266b86774d3d/?format=json',
      launch_library_id: null,
      slug: 'antares-230-cygnus-crs-2-ng-16-ss-ellison-onizuka',
      name: 'Antares 230+ | Cygnus CRS-2 NG-16 (S.S. Ellison Onizuka)',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-10T21:55:00Z',
      window_end: '2021-08-10T21:55:00Z',
      window_start: '2021-08-10T21:55:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: null,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 257, url: 'https://ll.thespacedevs.com/2.2.0/agencies/257/?format=json', name: 'Northrop Grumman Innovation Systems', type: 'Commercial' },
      rocket: { id: 2886, configuration: { id: 210, launch_library_id: 241, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/210/?format=json', name: 'Antares 230+', family: 'Antares', full_name: 'Antares 230+', variant: '230+' } },
      mission: {
        id: 1302,
        launch_library_id: null,
        name: 'Cygnus CRS-2 NG-16 (S.S. Ellison Onizuka)',
        description:
          "This is the 16th planned flight of the Orbital ATK's uncrewed resupply spacecraft Cygnus and its 15th flight to the International Space Station under the Commercial Resupply Services contract with NASA.\r\nThis Cygnus spacecraft is named after American astronaut Ellison Onizuka who died in the destruction of the Space Shuttle Challenger.",
        launch_designator: null,
        type: 'Resupply',
        orbit: { id: 8, name: 'Low Earth Orbit', abbrev: 'LEO' },
      },
      pad: {
        id: 76,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/76/?format=json',
        agency_id: 44,
        name: 'Launch Area 0 A',
        info_url: null,
        wiki_url: '',
        map_url: 'http://maps.google.com/maps?q=37.8337+N,+75.4881+W',
        latitude: '37.8337',
        longitude: '-75.4881',
        location: {
          id: 21,
          url: 'https://ll.thespacedevs.com/2.2.0/location/21/?format=json',
          name: 'Wallops Island, Virginia, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_21_20200803142423.jpg',
          total_launch_count: 22,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_76_20200803143538.jpg',
        total_launch_count: 14,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/antares2520230252b_image_20191102024633.jpeg',
      infographic: null,
      program: [
        {
          id: 11,
          url: 'https://ll.thespacedevs.com/2.2.0/program/11/?format=json',
          name: 'Commercial Resupply Services',
          description:
            'Commercial Resupply Services (CRS) are a series of flights awarded by NASA for the delivery of cargo and supplies to the International Space Station.The first CRS contracts were signed in 2008 and awarded $1.6 billion to SpaceX for twelve cargo Dragon and $1.9 billion to Orbital Sciences for eight Cygnus flights, covering deliveries to 2016. The Falcon 9 and Antares rockets were also developed under the CRS program to deliver cargo spacecraft to the ISS.',
          agencies: [
            { id: 44, url: 'https://ll.thespacedevs.com/2.2.0/agencies/44/?format=json', name: 'National Aeronautics and Space Administration', type: 'Government' },
            { id: 257, url: 'https://ll.thespacedevs.com/2.2.0/agencies/257/?format=json', name: 'Northrop Grumman Innovation Systems', type: 'Commercial' },
            { id: 1020, url: 'https://ll.thespacedevs.com/2.2.0/agencies/1020/?format=json', name: 'Sierra Nevada Corporation', type: 'Commercial' },
            { id: 121, url: 'https://ll.thespacedevs.com/2.2.0/agencies/121/?format=json', name: 'SpaceX', type: 'Commercial' },
          ],
          image_url: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/commercial2520_program_20201129212219.png',
          start_date: '2008-12-23T00:00:00Z',
          end_date: null,
          info_url: null,
          wiki_url: 'https://en.wikipedia.org/wiki/Commercial_Resupply_Services#Commercial_Resupply_Services',
        },
      ],
    },
    {
      id: '397c50c5-8a2b-4ca5-807d-8911c14b7126',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/397c50c5-8a2b-4ca5-807d-8911c14b7126/?format=json',
      launch_library_id: 1131,
      slug: 'gslv-mk-ii-eos-03-gisat-1',
      name: 'GSLV Mk II | EOS-03 (GISAT-1)',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-12T00:13:00Z',
      window_end: '2021-08-12T00:13:00Z',
      window_start: '2021-08-12T00:13:00Z',
      inhold: false,
      tbdtime: true,
      tbddate: true,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 31, url: 'https://ll.thespacedevs.com/2.2.0/agencies/31/?format=json', name: 'Indian Space Research Organization', type: 'Government' },
      rocket: { id: 56, configuration: { id: 168, launch_library_id: 60, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/168/?format=json', name: 'GSLV Mk II', family: 'PSLV', full_name: 'GSLV Mk. II', variant: '' } },
      mission: {
        id: 750,
        launch_library_id: 458,
        name: 'GISAT-1',
        description:
          'GISAT-1 is an Indian earth observation satellite to be launched in geostationary orbit. It is tasked with continuous observation of Indian sub-continent and quick monitoring of natural hazards and disaster. GISAT carries an imaging payload consisting of of multi-spectral, multi-resolution from 50 m to 1.5 km. It will provide pictures of the area of interest on near real time basis including border areas.',
        launch_designator: null,
        type: 'Earth Science',
        orbit: { id: 2, name: 'Geostationary Transfer Orbit', abbrev: 'GTO' },
      },
      pad: {
        id: 82,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/82/?format=json',
        agency_id: 31,
        name: 'Satish Dhawan Space Centre Second Launch Pad',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/Satish_Dhawan_Space_Centre_Second_Launch_Pad',
        map_url: 'https://www.google.com/maps?q=13.7199,80.2304',
        latitude: '13.7199',
        longitude: '80.2304',
        location: {
          id: 14,
          url: 'https://ll.thespacedevs.com/2.2.0/location/14/?format=json',
          name: 'Sriharikota, Republic of India',
          country_code: 'IND',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_14_20200803142403.jpg',
          total_launch_count: 54,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_82_20200803143602.jpg',
        total_launch_count: 15,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/gslv2520mk2520ii_image_20190825171642.jpg',
      infographic: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/gslv2520mk252_infographic_20200805202604.png',
      program: [],
    },
    {
      id: '495fe114-753d-48b1-9d23-eb9adaa3fb23',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/495fe114-753d-48b1-9d23-eb9adaa3fb23/?format=json',
      launch_library_id: 1347,
      slug: 'atlas-v-551-stp-3',
      name: 'Atlas V 551 | STP-3',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-15T00:00:00Z',
      window_end: '2021-08-15T00:00:00Z',
      window_start: '2021-08-15T00:00:00Z',
      inhold: false,
      tbdtime: true,
      tbddate: true,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 124, url: 'https://ll.thespacedevs.com/2.2.0/agencies/124/?format=json', name: 'United Launch Alliance', type: 'Commercial' },
      rocket: { id: 111, configuration: { id: 27, launch_library_id: 37, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/27/?format=json', name: 'Atlas V 551', family: 'Atlas', full_name: 'Atlas V 551', variant: '551' } },
      mission: {
        id: 1371,
        launch_library_id: null,
        name: 'STP-3',
        description:
          "Rideshare mission with the STPSat-6 satellite and six secondary payloads for the US Air Force. STPSat-6 carries the NNSA's Space and Atmospheric Burst Reporting System-3 (SABRS-3) payload and NASA's Laser Communications Relay Demonstration (LCRD) experiment.",
        launch_designator: null,
        type: 'Dedicated Rideshare',
        orbit: { id: 1, name: 'Geostationary Orbit', abbrev: 'Direct-GEO' },
      },
      pad: {
        id: 29,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/29/?format=json',
        agency_id: null,
        name: 'Space Launch Complex 41',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_41',
        map_url: 'http://maps.google.com/maps?q=28.58341025,-80.58303644',
        latitude: '28.58341025',
        longitude: '-80.58303644',
        location: {
          id: 12,
          url: 'https://ll.thespacedevs.com/2.2.0/location/12/?format=json',
          name: 'Cape Canaveral, FL, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg',
          total_launch_count: 223,
          total_landing_count: 21,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_29_20200803143528.jpg',
        total_launch_count: 72,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/atlas2520v2520551_image_20190224012316.jpeg',
      infographic: null,
      program: [],
    },
    {
      id: '13386512-85bb-4c93-a9b0-f5eac05fbe4f',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/13386512-85bb-4c93-a9b0-f5eac05fbe4f/?format=json',
      launch_library_id: null,
      slug: 'falcon-9-block-5-dragon-crs-2-spx-23',
      name: 'Falcon 9 Block 5 | Dragon CRS-2 SpX-23',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-18T10:00:00Z',
      window_end: '2021-08-18T10:00:00Z',
      window_start: '2021-08-18T10:00:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: null,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 121, url: 'https://ll.thespacedevs.com/2.2.0/agencies/121/?format=json', name: 'SpaceX', type: 'Commercial' },
      rocket: { id: 2887, configuration: { id: 164, launch_library_id: 188, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/164/?format=json', name: 'Falcon 9 Block 5', family: 'Falcon', full_name: 'Falcon 9 Block 5', variant: 'Block 5' } },
      mission: {
        id: 1303,
        launch_library_id: null,
        name: 'Dragon CRS-2 SpX-23',
        description:
          'SpaceX will launch the cargo variant of its Dragon 2 spacecraft on their 23rd commercial resupply services mission to the International Space Station. The flight will be conducted under the second Commercial Resupply Services contract with NASA.\r\n\r\nDragon will be filled with supplies and payloads, including critical materials to directly support science and research investigations that occur onboard the orbiting laboratory.',
        launch_designator: null,
        type: 'Resupply',
        orbit: { id: 8, name: 'Low Earth Orbit', abbrev: 'LEO' },
      },
      pad: {
        id: 87,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/87/?format=json',
        agency_id: null,
        name: 'Launch Complex 39A',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/Kennedy_Space_Center_Launch_Complex_39#Launch_Pad_39A',
        map_url: 'http://maps.google.com/maps?q=28.608+N,+80.604+W',
        latitude: '28.60822681',
        longitude: '-80.60428186',
        location: {
          id: 27,
          url: 'https://ll.thespacedevs.com/2.2.0/location/27/?format=json',
          name: 'Kennedy Space Center, FL, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_27_20200803142447.jpg',
          total_launch_count: 189,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_87_20200803143537.jpg',
        total_launch_count: 132,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/falcon2520925_image_20210520085649.jpeg',
      infographic: null,
      program: [
        {
          id: 11,
          url: 'https://ll.thespacedevs.com/2.2.0/program/11/?format=json',
          name: 'Commercial Resupply Services',
          description:
            'Commercial Resupply Services (CRS) are a series of flights awarded by NASA for the delivery of cargo and supplies to the International Space Station.The first CRS contracts were signed in 2008 and awarded $1.6 billion to SpaceX for twelve cargo Dragon and $1.9 billion to Orbital Sciences for eight Cygnus flights, covering deliveries to 2016. The Falcon 9 and Antares rockets were also developed under the CRS program to deliver cargo spacecraft to the ISS.',
          agencies: [
            { id: 44, url: 'https://ll.thespacedevs.com/2.2.0/agencies/44/?format=json', name: 'National Aeronautics and Space Administration', type: 'Government' },
            { id: 257, url: 'https://ll.thespacedevs.com/2.2.0/agencies/257/?format=json', name: 'Northrop Grumman Innovation Systems', type: 'Commercial' },
            { id: 1020, url: 'https://ll.thespacedevs.com/2.2.0/agencies/1020/?format=json', name: 'Sierra Nevada Corporation', type: 'Commercial' },
            { id: 121, url: 'https://ll.thespacedevs.com/2.2.0/agencies/121/?format=json', name: 'SpaceX', type: 'Commercial' },
          ],
          image_url: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/program_images/commercial2520_program_20201129212219.png',
          start_date: '2008-12-23T00:00:00Z',
          end_date: null,
          info_url: null,
          wiki_url: 'https://en.wikipedia.org/wiki/Commercial_Resupply_Services#Commercial_Resupply_Services',
        },
      ],
    },
    {
      id: 'c185a08e-9d82-4590-a13f-213c84c865e0',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/c185a08e-9d82-4590-a13f-213c84c865e0/?format=json',
      launch_library_id: null,
      slug: 'soyuz-21bfregat-m-oneweb-9',
      name: 'Soyuz 2.1b/Fregat-M | OneWeb 9',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-20T00:00:00Z',
      window_end: '2021-08-20T00:00:00Z',
      window_start: '2021-08-20T00:00:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: null,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 115, url: 'https://ll.thespacedevs.com/2.2.0/agencies/115/?format=json', name: 'Arianespace', type: 'Commercial' },
      rocket: {
        id: 2855,
        configuration: { id: 134, launch_library_id: 153, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/134/?format=json', name: 'Soyuz 2.1b/Fregat-M', family: 'Soyuz', full_name: 'Soyuz 2.1b Fregat-M', variant: 'Fregat-M' },
      },
      mission: {
        id: 1269,
        launch_library_id: null,
        name: 'OneWeb 9',
        description:
          'A batch of 34 satellites for the OneWeb satellite constellation, which is intended to provide global Internet broadband service for individual consumers. The constellation is planned to have around 648 microsatellites (of which 60 are spares), around 150 kg each, operating in Ku-band from low Earth orbit.',
        launch_designator: null,
        type: 'Communications',
        orbit: { id: 13, name: 'Polar Orbit', abbrev: 'PO' },
      },
      pad: {
        id: 20,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/20/?format=json',
        agency_id: null,
        name: '31/6',
        info_url: null,
        wiki_url: '',
        map_url: 'http://maps.google.com/maps?q=45.996+N,+63.564+E',
        latitude: '45.996034',
        longitude: '63.564003',
        location: {
          id: 15,
          url: 'https://ll.thespacedevs.com/2.2.0/location/15/?format=json',
          name: 'Baikonur Cosmodrome, Republic of Kazakhstan',
          country_code: 'KAZ',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_15_20200803142517.jpg',
          total_launch_count: 472,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_20_20200803143516.jpg',
        total_launch_count: 80,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/soyuz25202.1b_image_20210520085931.jpeg',
      infographic: null,
      program: [],
    },
    {
      id: '30412a48-cb4d-43d6-a304-6ae5f062504f',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/30412a48-cb4d-43d6-a304-6ae5f062504f/?format=json',
      launch_library_id: 2098,
      slug: 'kuaizhou-1a-jilin-1-02d',
      name: 'Kuaizhou-1A | Jilin-1-02D',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-31T00:00:00Z',
      window_end: '2021-08-31T00:00:00Z',
      window_start: '2021-08-31T00:00:00Z',
      inhold: false,
      tbdtime: true,
      tbddate: true,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 184, url: 'https://ll.thespacedevs.com/2.2.0/agencies/184/?format=json', name: 'China Aerospace Science and Industry Corporation', type: 'Government' },
      rocket: { id: 2758, configuration: { id: 135, launch_library_id: 155, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/135/?format=json', name: 'Kuaizhou', family: 'Kuaizhou', full_name: 'Kuaizhou-1A', variant: '1A' } },
      mission: { id: 1156, launch_library_id: 1346, name: 'Jilin-1-02D', description: 'Jilin-1 is a series of Chinese commercial remote sensing satellites.', launch_designator: null, type: 'Earth Science', orbit: null },
      pad: {
        id: 71,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/71/?format=json',
        agency_id: null,
        name: 'Unknown Pad',
        info_url: null,
        wiki_url: '',
        map_url: '',
        latitude: '40.958',
        longitude: '100.291',
        location: {
          id: 17,
          url: 'https://ll.thespacedevs.com/2.2.0/location/17/?format=json',
          name: "Jiuquan, People's Republic of China",
          country_code: 'CHN',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_17_20200803142429.jpg',
          total_launch_count: 105,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_71_20200803143610.jpg',
        total_launch_count: 26,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/kuaizhou_image_20191027094423.jpeg',
      infographic: null,
      program: [],
    },
    {
      id: '343e4980-cefc-42ac-bb58-f9441f27d6d8',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/343e4980-cefc-42ac-bb58-f9441f27d6d8/?format=json',
      launch_library_id: null,
      slug: 'long-march-4c-gaofen-3-02',
      name: 'Long March 4C | Gaofen-3-02',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-31T00:00:00Z',
      window_end: '2021-08-31T00:00:00Z',
      window_start: '2021-08-31T00:00:00Z',
      inhold: false,
      tbdtime: false,
      tbddate: false,
      probability: null,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 88, url: 'https://ll.thespacedevs.com/2.2.0/agencies/88/?format=json', name: 'China Aerospace Science and Technology Corporation', type: 'Government' },
      rocket: { id: 2964, configuration: { id: 64, launch_library_id: 70, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/64/?format=json', name: 'Long March 4C', family: 'Long March 4', full_name: 'Long March 4C', variant: 'C' } },
      mission: {
        id: 1386,
        launch_library_id: null,
        name: 'Gaofen-3-02',
        description:
          'Gaofen (GF) is a series of Chinese civilian remote sensing satellites for the state-sponsored program China High-definition Earth Observation System (CHEOS).\r\n\r\nGF 3 features a multi-polarized C-band SAR at meter-level resolution, with designed lifespan of 8 years. The satellite is based on the CS-L3000B bus.',
        launch_designator: null,
        type: 'Earth Science',
        orbit: { id: 17, name: 'Sun-Synchronous Orbit', abbrev: 'SSO' },
      },
      pad: {
        id: 22,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/22/?format=json',
        agency_id: null,
        name: 'Launch Area 4 (SLS-2 / 603)',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/Jiuquan_Launch_Area_4',
        map_url: 'http://maps.google.com/maps?q=40.960556,100.298333',
        latitude: '40.960556',
        longitude: '100.298333',
        location: {
          id: 17,
          url: 'https://ll.thespacedevs.com/2.2.0/location/17/?format=json',
          name: "Jiuquan, People's Republic of China",
          country_code: 'CHN',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_17_20200803142429.jpg',
          total_launch_count: 105,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_22_20200803143437.jpg',
        total_launch_count: 58,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/long2520march25204_image_20190520170012.jpeg',
      infographic: null,
      program: [],
    },
    {
      id: '708c2b85-50d6-4baa-bd3e-fdfb0257ea50',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/708c2b85-50d6-4baa-bd3e-fdfb0257ea50/?format=json',
      launch_library_id: 2099,
      slug: 'kuaizhou-1a-jilin-1-02f',
      name: 'Kuaizhou-1A | Jilin-1-02F',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-31T00:00:00Z',
      window_end: '2021-08-31T00:00:00Z',
      window_start: '2021-08-31T00:00:00Z',
      inhold: false,
      tbdtime: true,
      tbddate: true,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 184, url: 'https://ll.thespacedevs.com/2.2.0/agencies/184/?format=json', name: 'China Aerospace Science and Industry Corporation', type: 'Government' },
      rocket: { id: 2759, configuration: { id: 135, launch_library_id: 155, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/135/?format=json', name: 'Kuaizhou', family: 'Kuaizhou', full_name: 'Kuaizhou-1A', variant: '1A' } },
      mission: { id: 1157, launch_library_id: 1347, name: 'Jilin-1-02F', description: 'Jilin-1 is a series of Chinese commercial remote sensing satellites.', launch_designator: null, type: 'Earth Science', orbit: null },
      pad: {
        id: 71,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/71/?format=json',
        agency_id: null,
        name: 'Unknown Pad',
        info_url: null,
        wiki_url: '',
        map_url: '',
        latitude: '40.958',
        longitude: '100.291',
        location: {
          id: 17,
          url: 'https://ll.thespacedevs.com/2.2.0/location/17/?format=json',
          name: "Jiuquan, People's Republic of China",
          country_code: 'CHN',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_17_20200803142429.jpg',
          total_launch_count: 105,
          total_landing_count: 0,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_71_20200803143610.jpg',
        total_launch_count: 26,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/kuaizhou_image_20191027094423.jpeg',
      infographic: null,
      program: [],
    },
    {
      id: '7323ed72-b69a-429c-8cfe-2ed454a8db28',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/7323ed72-b69a-429c-8cfe-2ed454a8db28/?format=json',
      launch_library_id: 1522,
      slug: 'atlas-v-511-ussf-8',
      name: 'Atlas V 511 | USSF-8',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-31T00:00:00Z',
      window_end: '2021-08-31T00:00:00Z',
      window_start: '2021-08-31T00:00:00Z',
      inhold: false,
      tbdtime: true,
      tbddate: true,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 124, url: 'https://ll.thespacedevs.com/2.2.0/agencies/124/?format=json', name: 'United Launch Alliance', type: 'Commercial' },
      rocket: { id: 2664, configuration: { id: 214, launch_library_id: 244, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/214/?format=json', name: 'Atlas V 511', family: '', full_name: 'Atlas V 511', variant: '' } },
      mission: null,
      pad: {
        id: 29,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/29/?format=json',
        agency_id: null,
        name: 'Space Launch Complex 41',
        info_url: null,
        wiki_url: 'https://en.wikipedia.org/wiki/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_41',
        map_url: 'http://maps.google.com/maps?q=28.58341025,-80.58303644',
        latitude: '28.58341025',
        longitude: '-80.58303644',
        location: {
          id: 12,
          url: 'https://ll.thespacedevs.com/2.2.0/location/12/?format=json',
          name: 'Cape Canaveral, FL, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_12_20200803142519.jpg',
          total_launch_count: 223,
          total_landing_count: 21,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_29_20200803143528.jpg',
        total_launch_count: 72,
      },
      webcast_live: false,
      image: null,
      infographic: null,
      program: [],
    },
    {
      id: 'bb2a5291-0aef-4c2a-8e29-93362d256fea',
      url: 'https://ll.thespacedevs.com/2.2.0/launch/bb2a5291-0aef-4c2a-8e29-93362d256fea/?format=json',
      launch_library_id: 1684,
      slug: 'firefly-alpha-maiden-flight',
      name: 'Firefly Alpha | Maiden Flight',
      status: { id: 2, name: 'TBD' },
      net: '2021-08-31T00:00:00Z',
      window_end: '2021-08-31T00:00:00Z',
      window_start: '2021-08-31T00:00:00Z',
      inhold: false,
      tbdtime: true,
      tbddate: true,
      probability: -1,
      holdreason: '',
      failreason: '',
      hashtag: null,
      launch_service_provider: { id: 265, url: 'https://ll.thespacedevs.com/2.2.0/agencies/265/?format=json', name: 'Firefly Aerospace', type: 'Commercial' },
      rocket: { id: 2210, configuration: { id: 179, launch_library_id: 216, url: 'https://ll.thespacedevs.com/2.2.0/config/launcher/179/?format=json', name: 'Firefly Alpha', family: 'Firefly Alpha', full_name: 'Firefly Alpha', variant: '' } },
      mission: {
        id: 966,
        launch_library_id: 1180,
        name: 'Maiden Flight',
        description: 'First flight of the new Firefly Alpha small sat launcher developed by Firefly Aerospace.',
        launch_designator: null,
        type: 'Test Flight',
        orbit: { id: 8, name: 'Low Earth Orbit', abbrev: 'LEO' },
      },
      pad: {
        id: 39,
        url: 'https://ll.thespacedevs.com/2.2.0/pad/39/?format=json',
        agency_id: null,
        name: 'Space Launch Complex 2W',
        info_url: null,
        wiki_url: '',
        map_url: 'http://maps.google.com/maps?q=34.7556+N,+120.6224+W',
        latitude: '34.7556',
        longitude: '-120.6224',
        location: {
          id: 11,
          url: 'https://ll.thespacedevs.com/2.2.0/location/11/?format=json',
          name: 'Vandenberg SFB, CA, USA',
          country_code: 'USA',
          map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/location_11_20200803142416.jpg',
          total_launch_count: 84,
          total_landing_count: 3,
        },
        map_image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launch_images/pad_39_20200803143542.jpg',
        total_launch_count: 18,
      },
      webcast_live: false,
      image: 'https://spacelaunchnow-prod-east.nyc3.digitaloceanspaces.com/media/launcher_images/firefly_alpha_image_20210429094607.jpg',
      infographic: null,
      program: [],
    },
  ],
};

test(`nextLaunchManager Unit Tests`, async () => {
  nextLaunchManager.init();
  nextLaunchManager.showTable();
  const tbl = document.createElement('table');
  tbl.id = 'nextLaunch-table';
  document.body.appendChild(tbl);
  nextLaunchManager.showTable();

  setUrl('http://example.com');
  nextLaunchManager.init();
  await Promise.resolve();

  nextLaunchManager.processData(resp);

  nextLaunchManager.showTable();

  settingsManager.offline = true;
  nextLaunchManager.init();
});
