import { keepTrackApi } from '@app/keepTrackApi';
import { loadPlugins } from '@app/plugins/plugins';

describe('plugins', () => {
  it('should be able to initialize all plugins', () => {
    loadPlugins(keepTrackApi, {
      debug: false,
      satInfoboxCore: true,
      AboutMenuPlugin: true,
      Collisions: true,
      DopsPlugin: true,
      FindSatPlugin: true,
      launchCalendar: true,
      newLaunch: true,
      nextLaunch: true,
      nightToggle: true,
      photoManager: true,
      screenRecorder: true,
      satChanges: false,
      stereoMap: true,
      timeMachine: true,
      initialOrbit: true,
      MissilePlugin: true,
      breakup: true,
      EditSat: true,
      constellations: true,
      countries: true,
      colorsMenu: true,
      ShortTermFences: true,
      orbitReferences: true,
      analysis: true,
      plotAnalysis: true,
      SensorFov: true,
      SensorSurvFence: true,
      satelliteFov: true,
      satelliteView: true,
      planetarium: true,
      astronomy: true,
      screenshot: true,
      WatchlistPlugin: true,
      sensor: true,
      settingsMenu: true,
      datetime: true,
      social: true,
      topMenu: true,
      classificationBar: true,
      soundManager: true,
      gamepad: true,
    });
  });
});
