import { keepTrackApi } from '@app/keepTrackApi';
import { loadPlugins } from '@app/plugins/plugins';

describe('plugins', () => {
  it('should be able to initialize all plugins', () => {
    loadPlugins(keepTrackApi, {
      debug: false,
      satInfoboxCore: true,
      AboutMenuPlugin: true,
      Collisions: true,
      DopsPlugin: true,
      FindSatPlugin: true,
      launchCalendar: true,
      NewLaunch: true,
      nextLaunch: true,
      nightToggle: true,
      photoManager: true,
      screenRecorder: true,
      satChanges: false,
      StereoMap: true,
      timeMachine: true,
      initialOrbit: true,
      MissilePlugin: true,
      Breakup: true,
      EditSat: true,
      SatConstellations: true,
      CountriesMenu: true,
      ColorMenu: true,
      ShortTermFences: true,
      orbitReferences: true,
      analysis: true,
      plotAnalysis: true,
      SensorFov: true,
      SensorSurvFence: true,
      satelliteFov: true,
      SatelliteViewPlugin: true,
      Planetarium: true,
      Astronomy: true,
      screenshot: true,
      WatchlistPlugin: true,
      SettingsMenuPlugin: true,
      DateTimeManager: true,
      SocialMedia: true,
      TopMenu: true,
      ClassificationBar: true,
      SoundManager: true,
      GamepadPlugin: true,
    });
  });
});
