import { keepTrackApi } from '@app/js/keepTrackApi';
import { loadCorePlugins } from '@app/js/plugins/plugins';

describe('plugins', () => {
  it('should be able to initialize all plugins', () => {
    loadCorePlugins(keepTrackApi, {
      debug: false,
      satInfoboxCore: true,
      updateSelectBoxCore: true,
      aboutManager: true,
      collisions: true,
      dops: true,
      findSat: true,
      launchCalendar: true,
      newLaunch: true,
      nextLaunch: true,
      nightToggle: true,
      photoManager: true,
      screenRecorder: true,
      satChanges: false,
      stereoMap: true,
      timeMachine: true,
      initialOrbit: true,
      missile: true,
      breakup: true,
      editSat: true,
      constellations: true,
      countries: true,
      colorsMenu: true,
      shortTermFences: true,
      orbitReferences: true,
      analysis: true,
      plotAnalysis: true,
      sensorFov: true,
      sensorSurv: true,
      satelliteFov: true,
      satelliteView: true,
      planetarium: true,
      astronomy: true,
      screenshot: true,
      watchlist: true,
      sensor: true,
      settingsMenu: true,
      datetime: true,
      social: true,
      topMenu: true,
      classificationBar: true,
      soundManager: true,
      gamepad: true,
      scenarioCreator: false,
    });
  });
});
