import { getEl } from '@app/lib/get-el';
// Generated by CodiumAI

import { keepTrackApi } from '@app/keepTrackApi';
import { MobileManager } from '@app/singletons/mobileManager';
import { SplashScreen } from '@app/static/splash-screen';

describe('SplashScreen_class', () => {
  beforeEach(() => {
    const shadowDiv = document.createElement('div');
    const shadow = shadowDiv.attachShadow({ mode: 'open' });
    const shadowBody = document.createElement('body');

    shadow.appendChild(shadowBody);
    SplashScreen.initLoadingScreen(shadowBody);
  });

  // Tests that the loading screen is hidden immediately when running on mobile
  it('test_hide_splash_screen_mobile', () => {
    MobileManager.checkMobileMode = jest.fn().mockReturnValue(true);
    SplashScreen.hideSplashScreen();
    // Wait for timers to finish
    jest.advanceTimersByTime(1000);
    expect(getEl('loading-screen')?.style.display).toBe('none');
  });

  // Tests that the loading screen is resized and hidden after a timeout when running on desktop
  it('test_hide_splash_screen_desktop', () => {
    keepTrackApi.getScene().earth.isUseHiRes = true;
    keepTrackApi.getScene().earth.isHiResReady = true;
    SplashScreen.hideSplashScreen();
    // Wait for timers to finish
    jest.advanceTimersByTime(1000);
    expect(getEl('loading-screen')?.style.display).toBe('none');
  });

  // Tests that loadStr() does nothing when the loader text element is not found
  it('test_load_str_element_not_found', () => {
    keepTrackApi.containerRoot.innerHTML = '<div id="loader-text"></div>';
    SplashScreen.loadStr('test');
    expect(getEl('loader-text').textContent).toBe('test');
  });
});
