/* eslint-disable dot-notation */
// Generated by CodiumAI

import { UiValidation } from '@app/app/ui/ui-validation';
import { getEl } from '@app/engine/utils/get-el';
import { KeepTrack } from '@app/keeptrack';

describe('UiValidation_class', () => {
  // Tests that all event listeners are added successfully
  it('test_init_ui_validation', () => {
    // the following event listeners may be added.
    KeepTrack.getInstance().containerRoot.innerHTML = `<div id="editSat">
            <input id="es-ecen" />
            <input id="es-day" />
            <input id="es-inc" />
            <input id="es-rasc" />
            <input id="es-meanmo" />
            <input id="es-argPe" />
            <input id="es-meana" />
            <input id="ms-lat" />
            <input id="ms-lon" />
        </div>`;
    UiValidation.initUiValidation();
    expect(getEl('editSat')?.querySelectorAll('input')).toBeTruthy();
    expect(getEl('es-ecen')).toBeTruthy();
    expect(getEl('es-day')).toBeTruthy();
    expect(getEl('es-inc')).toBeTruthy();
    expect(getEl('es-rasc')).toBeTruthy();
    expect(getEl('es-meanmo')).toBeTruthy();
    expect(getEl('es-argPe')).toBeTruthy();
    expect(getEl('es-meana')).toBeTruthy();
    expect(getEl('ms-lat')).toBeTruthy();
    expect(getEl('ms-lon')).toBeTruthy();

    UiValidation['allowPeriod_']({ code: 'Period', preventDefault: jest.fn } as unknown as KeyboardEvent);
    UiValidation['esArgPe360_']();
    (<HTMLInputElement>getEl('es-argPe')).value = '-10';
    UiValidation['esArgPe360_']();
    (<HTMLInputElement>getEl('es-argPe')).value = '500';
    UiValidation['esArgPe360_']();
    UiValidation['esDay366_']();
    (<HTMLInputElement>getEl('es-day')).value = '-10';
    UiValidation['esDay366_']();
    (<HTMLInputElement>getEl('es-day')).value = '500';
    UiValidation['esDay366_']();
    UiValidation['esInc180_']();
    (<HTMLInputElement>getEl('es-inc')).value = '-10';
    UiValidation['esInc180_']();
    (<HTMLInputElement>getEl('es-inc')).value = '500';
    UiValidation['esInc180_']();
    UiValidation['esMeana360_']();
    (<HTMLInputElement>getEl('es-meana')).value = '-10';
    UiValidation['esMeana360_']();
    (<HTMLInputElement>getEl('es-meana')).value = '500';
    UiValidation['esMeana360_']();
    UiValidation['esMeanmo18_']();
    (<HTMLInputElement>getEl('es-meanmo')).value = '-10';
    UiValidation['esMeanmo18_']();
    (<HTMLInputElement>getEl('es-meanmo')).value = '500';
    UiValidation['esMeanmo18_']();
    UiValidation['esRasc360_']();
    (<HTMLInputElement>getEl('es-rasc')).value = '-10';
    UiValidation['esRasc360_']();
    (<HTMLInputElement>getEl('es-rasc')).value = '500';
    UiValidation['esRasc360_']();
    UiValidation['msLat90_']();
    (<HTMLInputElement>getEl('ms-lat')).value = '-100';
    UiValidation['msLat90_']();
    (<HTMLInputElement>getEl('ms-lat')).value = '500';
    UiValidation['msLat90_']();
    UiValidation['msLon180_']();
    (<HTMLInputElement>getEl('ms-lon')).value = '-100';
    UiValidation['msLon180_']();
    (<HTMLInputElement>getEl('ms-lon')).value = '500';
    UiValidation['msLon180_']();

    UiValidation['validateNumOnly_']({ code: 'KeyA', ctrlKey: true, preventDefault: jest.fn } as unknown as KeyboardEvent);
    UiValidation['validateNumOnly_']({ code: 'KeyA', ctrlKey: false, preventDefault: jest.fn } as unknown as KeyboardEvent);
  });
});
