import { Camera } from '@app/engine/camera/camera';
import { CameraType } from '@app/engine/camera/camera-type';
import { Container } from '@app/engine/core/container';
import { EventBus } from '@app/engine/events/event-bus';
import { EventBusEvent } from '@app/engine/events/event-bus-events';
import { PluginRegistry } from '@app/engine/core/plugin-registry';
import { SatelliteViewPlugin } from '@app/plugins/satellite-view/satellite-view';
import { SelectSatManager } from '@app/plugins/select-sat-manager/select-sat-manager';
import { ServiceLocator } from '@app/engine/core/service-locator';
import { Singletons, ToastMsgType } from '@app/engine/core/interfaces';
import { UiManager } from '@app/app/ui/ui-manager';
import { getEl } from '@app/engine/utils/get-el';
import { mockCameraManager, mockUiManager, setupStandardEnvironment } from '@test/environment/standard-env';
import { standardPluginSuite } from '@test/generic-tests';
import { t7e } from '@app/locales/keys';
import { vi } from 'vitest';

describe('SatelliteViewPlugin', () => {
  beforeEach(() => {
    setupStandardEnvironment([SelectSatManager]);
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  standardPluginSuite(SatelliteViewPlugin, 'SatelliteViewPlugin');
});

// Generated by CodiumAI

/*
 *Code Analysis
 *
 *Main functionalities:
 *The SatelliteViewPlugin class is a plugin for the KeepTrack application that adds a satellite view feature. It allows the user to switch between a normal camera mode and a
 *satellite camera mode, where the camera is fixed to a selected satellite. The plugin adds an icon to the bottom menu that toggles the satellite view mode on and off. The plugin
 *also registers callbacks with the KeepTrack API to handle user interactions and add HTML and JS to the application.
 *
 *Methods:
 *- init(): initializes the plugin by adding HTML and JS
 *- addJs(): adds JS to the application by registering a callback with the KeepTrack API
 *- addHtml(): adds HTML to the application by registering a callback with the KeepTrack API
 *
 */

describe('SatelliteViewPlugin_class', () => {
  let selectSatManagerInstance: SelectSatManager;

  beforeEach(() => {
    PluginRegistry.unregisterAllPlugins();

    mockUiManager.toast = vi.fn();
    Container.getInstance().registerSingleton<UiManager>(Singletons.UiManager, mockUiManager);
    const selectSatManager = new SelectSatManager();

    selectSatManager.init();

    selectSatManagerInstance = PluginRegistry.getPlugin(SelectSatManager) as SelectSatManager;

    expect(selectSatManagerInstance).toBeDefined();
    expect(selectSatManagerInstance).not.toBeNull();

    if (!selectSatManagerInstance) {
      throw new Error('SelectSatManager is null');
    }
  });

  standardPluginSuite(SatelliteViewPlugin, 'SatelliteViewPlugin');

  // Tests that the addHtml method adds the correct HTML element to the DOM
  it('test_addHtml_method', () => {
    const plugin = new SatelliteViewPlugin();
    const registerSpy = vi.spyOn(EventBus.getInstance(), 'on');

    plugin.addHtml();
    EventBus.getInstance().emit(EventBusEvent.uiManagerInit);
    EventBus.getInstance().emit(EventBusEvent.uiManagerFinal);
    expect(registerSpy).toHaveBeenCalled();
    expect(getEl('bottom-icons-utility')?.innerHTML).toContain('SatelliteViewPlugin-utility-icon');
  });

  // Tests that a toast message is displayed when no satellite is selected and trying to activate Satellite Camera Mode
  it('test_bottomMenuClick_callback_no_satellite_selected', () => {
    const plugin = new SatelliteViewPlugin();
    const uiManagerInstance = ServiceLocator.getUiManager();

    selectSatManagerInstance.selectedSat = -1;
    plugin.init();
    EventBus.getInstance().emit(EventBusEvent.uiManagerInit);
    EventBus.getInstance().emit(EventBusEvent.uiManagerFinal);
    Container.getInstance().registerSingleton<Camera>(Singletons.MainCamera, mockCameraManager);
    EventBus.getInstance().emit(EventBusEvent.bottomMenuClick, plugin.bottomIconElementName);
    expect(uiManagerInstance.toast).toHaveBeenCalledWith(t7e('errorMsgs.SelectSatelliteFirst'), ToastMsgType.serious, true);
  });

  // Tests that a toast message is not displayed when a satellite is selected and trying to activate Satellite Camera Mode
  it.skip('test_bottomMenuClick_callback_satellite_selected', () => {
    const plugin = new SatelliteViewPlugin();
    const uiManagerInstance = ServiceLocator.getUiManager();

    selectSatManagerInstance.selectedSat = 1;
    plugin.init();
    EventBus.getInstance().emit(EventBusEvent.uiManagerInit);
    EventBus.getInstance().emit(EventBusEvent.uiManagerFinal);
    Container.getInstance().registerSingleton<Camera>(Singletons.MainCamera, mockCameraManager);
    EventBus.getInstance().emit(EventBusEvent.bottomMenuClick, plugin.bottomIconElementName);
    expect(uiManagerInstance.toast).not.toHaveBeenCalled();
  });

  // Tests that clicking the Satellite Camera Mode icon switches the camera to Satellite mode
  it.skip('should_switch_to_satellite_camera_mode_when_icon_clicked', () => {
    const plugin = new SatelliteViewPlugin();
    const uiManagerInstance = ServiceLocator.getUiManager();

    selectSatManagerInstance.selectedSat = 1;
    plugin.init();
    EventBus.getInstance().emit(EventBusEvent.uiManagerInit);
    EventBus.getInstance().emit(EventBusEvent.uiManagerFinal);
    const tempMockCamera = { ...mockCameraManager, cameraType: CameraType.SATELLITE_FIRST_PERSON } as Camera;

    Container.getInstance().registerSingleton<Camera>(Singletons.MainCamera, tempMockCamera);
    EventBus.getInstance().emit(EventBusEvent.bottomMenuClick, plugin.bottomIconElementName);
    expect(uiManagerInstance.toast).not.toHaveBeenCalled();
  });
});

describe('SatelliteViewPlugin methods', () => {
  let plugin: SatelliteViewPlugin;

  beforeEach(() => {
    setupStandardEnvironment([SelectSatManager]);
    plugin = new SatelliteViewPlugin();
    plugin.init();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('binds the "5" keyboard shortcut', () => {
    expect(plugin.getKeyboardShortcuts()[0].key).toBe('5');
    expect(() => plugin.getKeyboardShortcuts()[0].callback()).not.toThrow();
  });

  it('toasts and shakes when no satellite is selected', () => {
    const ssm = PluginRegistry.getPlugin(SelectSatManager) as SelectSatManager;

    ssm.selectedSat = -1;
    const shake = vi.spyOn(plugin, 'shakeBottomIcon').mockImplementation(() => undefined);
    const toast = vi.spyOn(ServiceLocator.getUiManager(), 'toast');

    plugin.bottomIconCallback();

    expect(toast).toHaveBeenCalled();
    expect(shake).toHaveBeenCalled();
  });

  it('switches to SATELLITE_FIRST_PERSON when a satellite is selected', () => {
    const ssm = PluginRegistry.getPlugin(SelectSatManager) as SelectSatManager;

    ssm.selectedSat = 0;
    vi.spyOn(plugin, 'setBottomIconToSelected').mockImplementation(() => undefined);

    plugin.bottomIconCallback();

    expect(ServiceLocator.getMainCamera().cameraType).toBe(CameraType.SATELLITE_FIRST_PERSON);
  });

  it('runs the shouldSkipSatelliteModels and updateLoop sync handlers', () => {
    expect(() => EventBus.getInstance().emit(EventBusEvent.shouldSkipSatelliteModels)).not.toThrow();

    const select = vi.spyOn(plugin, 'setBottomIconToSelected').mockImplementation(() => undefined);

    ServiceLocator.getMainCamera().cameraType = CameraType.SATELLITE_FIRST_PERSON;
    plugin.isMenuButtonActive = false;
    plugin.isIconDisabled = false;
    EventBus.getInstance().emit(EventBusEvent.updateLoop);
    expect(select).toHaveBeenCalled();

    const unselect = vi.spyOn(plugin, 'setBottomIconToUnselected').mockImplementation(() => undefined);

    ServiceLocator.getMainCamera().cameraType = CameraType.FIXED_TO_EARTH;
    plugin.isMenuButtonActive = true;
    EventBus.getInstance().emit(EventBusEvent.updateLoop);
    expect(unselect).toHaveBeenCalled();
  });
});
