import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { classifyCompat, isCompatible } from './host-version';
import { readLockfile } from './lockfile';
import { GENERATED_MANIFEST_PATH, pluginDir } from './paths';
import { readManifest, validateManifest } from './plugin-meta';
import type { KeepTrackPluginManifest, LockEntry } from './types';

const HEADER = `/**
 * AUTO-GENERATED by \`npm run plugin -- sync\`. DO NOT EDIT BY HAND.
 *
 * Regenerated from external-plugins.json + the keeptrack-plugin.json of each
 * clone under src/plugins-external/. Committed so a fresh checkout typechecks
 * and builds without running any tool; empty upstream when no external plugins
 * are installed.
 *
 * - \`externalPluginManifest\` is spread onto the end of \`pluginManifest\`, giving
 *   each external plugin its own async chunk exactly like a built-in.
 * - \`externalPluginMeta\` is read by the in-app Plugin Manager UI so it can list
 *   installed external plugins (version, repo, compat) without fetching anything
 *   at runtime. \`compatible\` is precomputed at sync time against the host
 *   package.json version.
 */
import type { PluginDescriptor } from './plugin-descriptor';

export interface ExternalPluginMetaEntry {
  /** npm-style package name from keeptrack-plugin.json \`name\`. */
  packageName: string;
  /** Plugin's own semver. */
  version: string;
  /** Repository URL for the "view source" link. */
  repoUrl: string;
  /** One-line description. */
  description: string;
  /** Declared engine compatibility range (semver). */
  engine: string;
  /** Resolved git commit the clone is pinned to. */
  commit: string;
  /** Precomputed at sync time: does \`engine\` satisfy the host version? */
  compatible: boolean;
}
`;

const EMPTY_BODY = `
export const externalPluginManifest: PluginDescriptor[] = [];

export const externalPluginMeta: Record<string, ExternalPluginMetaEntry> = {};
`;

export interface SyncReport {
  /** Plugin names present on disk and included in the generated manifest. */
  included: string[];
  /** Plugin names in the lockfile whose clone is missing (dropped from the manifest). */
  missing: string[];
  /** Plugin names present on disk but skipped because their manifest is invalid. */
  invalid: { name: string; reason: string }[];
  /** configKeys whose engine range does not satisfy the host version. */
  incompatible: { configKey: string; engine: string }[];
}

/** Strip a TS/JS extension from a repo-relative entry path and normalize to POSIX. */
function toImportSpecifier(name: string, entry: string): string {
  const posix = entry.replaceAll('\\', '/').replace(/^\.\//u, '');
  const noExt = posix.replace(/\.(?:tsx?|jsx?|mjs)$/u, '');

  return `@plugins-external/${name}/${noExt}`;
}

/**
 * Build the generated-manifest source text from the lockfile + on-disk clones.
 * Only plugins actually present on disk are included, so the file never contains
 * an import rspack cannot resolve.
 */
export function generateManifestSource(): { source: string; report: SyncReport } {
  const lock = readLockfile();
  const names = Object.keys(lock.plugins).sort((a, b) => a.localeCompare(b));
  const report: SyncReport = { included: [], missing: [], invalid: [], incompatible: [] };
  const descriptorBlocks: string[] = [];
  const metaBlocks: string[] = [];

  for (const name of names) {
    const dir = pluginDir(name);

    if (!existsSync(dir)) {
      report.missing.push(name);
      continue;
    }

    // Lenient here (prebuild path): a malformed third-party manifest is skipped
    // with a report entry rather than bricking the build. `add`/`update` are the
    // strict gates that block on validation errors.
    try {
      const manifest = readManifest(dir);
      const { errors } = validateManifest(manifest, { dir, expectedName: name });

      if (errors.length > 0) {
        report.invalid.push({ name, reason: errors[0] });
        continue;
      }

      emitPlugin(name, manifest, lock.plugins[name], descriptorBlocks, metaBlocks, report);
    } catch (e) {
      report.invalid.push({ name, reason: (e as Error).message });
    }
  }

  if (descriptorBlocks.length === 0) {
    return { source: `${HEADER}${EMPTY_BODY}`, report };
  }

  const body = `
export const externalPluginManifest: PluginDescriptor[] = [
${descriptorBlocks.join('\n')}
];

export const externalPluginMeta: Record<string, ExternalPluginMetaEntry> = {
${metaBlocks.join('\n')}
};
`;

  return { source: `${HEADER}${body}`, report };
}

// eslint-disable-next-line max-params
function emitPlugin(
  name: string,
  manifest: KeepTrackPluginManifest,
  lockEntry: LockEntry,
  descriptorBlocks: string[],
  metaBlocks: string[],
  report: SyncReport,
): void {
  report.included.push(name);

  for (const p of manifest.plugins) {
    const spec = toImportSpecifier(name, p.entry);
    const cfg = JSON.stringify(p.defaultConfig);
    const alwaysEnabled = p.alwaysEnabled ? '\n    alwaysEnabled: true,' : '';

    descriptorBlocks.push(
      `  // ${name}@${manifest.version} (${lockEntry.commit.slice(0, 7)})\n` +
      `  {\n` +
      `    configKey: '${p.configKey}',\n` +
      `    ossImport: () => import(/* @vite-ignore */ '${spec}'),\n` +
      `    ossClassName: '${p.className}',\n` +
      `    defaultConfig: ${cfg},${alwaysEnabled}\n` +
      `  },`,
    );

    if (!isCompatible(manifest.engine)) {
      report.incompatible.push({ configKey: p.configKey, engine: manifest.engine });
    }

    const meta = {
      packageName: manifest.name,
      version: manifest.version,
      repoUrl: manifest.repository ?? lockEntry.url,
      description: manifest.description ?? '',
      engine: manifest.engine,
      commit: lockEntry.commit,
      compatible: classifyCompat(manifest.engine) === 'ok',
    };

    metaBlocks.push(`  '${p.configKey}': ${JSON.stringify(meta)},`);
  }
}

/** Regenerate and write the committed generated manifest. Returns the sync report. */
export function writeGeneratedManifest(): SyncReport {
  const { source, report } = generateManifestSource();

  writeFileSync(GENERATED_MANIFEST_PATH, source, 'utf8');

  return report;
}

/** True if the on-disk generated manifest already matches what sync would write. */
export function isGeneratedManifestInSync(): boolean {
  const { source } = generateManifestSource();
  const current = existsSync(GENERATED_MANIFEST_PATH) ? readFileSync(GENERATED_MANIFEST_PATH, 'utf8') : '';

  return current === source;
}
