export const countryCodeList = {
  'Afghanistan': 'AF',
  'Algeria': 'ALG',
  'Argentina': 'AR|ARGN',
  'Australia': 'AU|AUS',
  'Austria': 'AT|ASRA',
  'Azerbaijan': 'AZ|AZER',
  'Belarus': 'BY|BELA',
  'Belgium': 'B|BEL',
  'Bolivia': 'BOL',
  'Brazil': 'BR|BRAZ',
  'Canada': 'CA',
  'Chile': 'CHLE',
  'China': 'CN|PRC',
  'Colombia': 'CO|COL',
  'Czechoslovakia': 'CZ|CZCH',
  'Denmark': 'DK|DEN',
  'Egypt': 'EG|EGYP',
  'Estonia': 'EE|EST',
  'European Space Agency': 'ESA|I-ESA',
  'Finland': 'FI|FIN',
  'France': 'F|FR',
  'Germany': 'D|GER',
  'Globalstar': 'GLOB|ORB',
  'Greece': 'GR|GREC',
  'Hong Kong': 'HK',
  'Hungary': 'HU|HUN',
  'India': 'IN|IND',
  'Indonesia': 'ID|INDO',
  'Inmarsat': 'IM',
  'International': 'ISS',
  'Intelsat': 'ITSO',
  'Iran': 'IR|IRAN',
  'Iraq': 'IQ|IRAQ',
  'Ireland': 'IE',
  'Israel': 'IL|ISRA',
  'Italy': 'I|IT',
  'Japan': 'J|JPN',
  'Jordan': 'JOR',
  'Kazakhstan': 'KZ|KAZ',
  'Kuwait': 'KWT',
  'Laos': 'LAOS',
  'Lithuania': 'LTU',
  'Luxembourg': 'LUXE',
  'Malaysia': 'MALA',
  'Mauritius': 'MUS',
  'Mexico': 'MX|MEX',
  'Moldova': 'MDA',
  'Mongolia': 'MNG',
  'Morocco': 'MA',
  'NATO': 'NATO',
  'Netherlands': 'NL|NETH',
  'New Zealand': 'NZ',
  'Nigeria': 'NG|NIG',
  'North Korea': 'KP|NKOR',
  'Norway': 'N|NOR',
  'O3B': 'O3B',
  'Peru': 'PE|PERU',
  'Philippines': 'PH|RP',
  'Poland': 'PL|POL',
  'Portugal': 'PT|POR',
  'Russia': 'RU|SU|CIS',
  'Saudi Arabia': 'SA|SAUD',
  'Singapore': 'SG|SING',
  'South Africa': 'ZA',
  'South Korea': 'KR|SKOR',
  'Spain': 'E|SPN',
  'Sweden': 'S|SWED',
  'Switzerland': 'CH|SWTZ',
  'Thailand': 'T|THAI',
  'Turkey': 'TR|TURK',
  'Ukraine': 'UKR',
  'United Arab Emirates': 'AE|UAE',
  'United Kingdom': 'UK',
  'United States': 'US|USA',
  'Uruguay': 'UY|URY',
  'Venezuela': 'VE|VENZ',
  'Vietnam': 'VN|VTNM',
};

/**
 * An array of country names with satellites.
 */
export const countryNameList = Object.keys(countryCodeList);

export const countryMapList = {
  'AAT': 'AAT',
  'ADG': 'Adygea',
  'AF': 'Afganistan',
  'AG': 'Antigua',
  'AGUK': 'Antigua',
  'AM': 'Armenia',
  'ANTN': 'Neth. Antilles',
  'AO': 'Angola',
  'AQ': 'Antarctica',
  'AR': 'Argentina',
  'ARV': 'Arg. Antarctic',
  'AT': 'Austria',
  'AU': 'Australia',
  'AZ': 'Azerbaijan',
  'B': 'Belgium',
  'BASH': 'Bashkiria',
  'BAT': 'BAT',
  'BB': 'Barbados',
  'BBUK': 'Barbados',
  'BD': 'Bangladesh',
  'BG': 'Bulgaria',
  'BGN': 'PR Bulgaria',
  'BM': 'Bermuda',
  'BO': 'Bolivia',
  'BR': 'Brazil',
  'BS': 'Bahamas',
  'BT': 'Bhutan',
  'BY': 'Belarus',
  'CA': 'Canada',
  'CD': 'DR Congo',
  'CH': 'Switzerland',
  'CI': 'Ivory Coast',
  'CK': 'Cook Islands',
  'CL': 'Chile',
  'CM': 'Cameroon',
  'CN': 'China',
  'CO': 'Colombia',
  'COLP': 'Congo',
  'CR': 'Costa Rica',
  'CSFR': 'Czechoslovakia',
  'CSSR': 'Czechoslovakia',
  'CU': 'Cuba',
  'CYM': 'Cayman Is.',
  'CYMRU': 'Wales',
  'CZ': 'Czech Republic',
  'D': 'Germany',
  'DAG': 'Dagestan',
  'DD': 'East Germany',
  'DK': 'Denmark',
  'DML': 'Queen Maud Land',
  'DR': 'Germany (Reich)',
  'DX': 'Germany (occ.)',
  'DZ': 'Algeria',
  'E': 'Spain',
  'EC': 'Ecuador',
  'EE': 'Estonia',
  'EG': 'Egypt',
  'ENG': 'England',
  'ESCN': 'Canary Is',
  'ET': 'Ethiopia',
  'F': 'France',
  'FI': 'Finland',
  'GE': 'Georgia',
  'GH': 'Ghana',
  'GI': 'Gibraltar',
  'GL': 'Greenland',
  'GR': 'Greece',
  '': 'GRD  Grenada',
  'GT': 'Guatemala',
  'GU': 'Guam',
  'GUF': 'French Guiana',
  'HK': 'China(Hong Kong)',
  'HKUK': 'Hong Kong',
  'HU': 'Hungary',
  'I': 'Italy',
  'I-ARAB': 'Arabsat',
  'I-CSC1': 'COSPAS-SARSAT',
  'I-ELDO': 'European Launcher Development Organization',
  'I-ESRO': 'European Space Research Organization',
  'I-EUM': 'EUMETSAT',
  'I-EU': 'EU',
  'I-EUT': 'EUTELSAT',
  'I-INM': 'INMARSAT',
  'I-INT': 'INTELSAT',
  'I-ISS': 'ISS',
  'I-NATO': 'North Atlantic Treaty Organization',
  'I-RASC': 'RASCOM',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IN': 'India',
  'IQ': 'Iraq',
  'IR': 'Iran',
  'IS': 'Iceland',
  'J': 'Japan',
  'JO': 'Jordan',
  'KE': 'Kenya',
  'KI': 'Kiribati',
  'KG': 'Kyrgyzstan',
  'KGSR': 'Kyrgyz SSR',
  'KH': 'Cambodia',
  'KORS': 'Neth. Antilles',
  'KORSA': 'Neth. Antilles',
  'KP': 'North Korea',
  'KR': 'South Korea',
  'KW': 'Kuwait',
  'KZ': 'Kazakhstan',
  'L': 'Luxembourg',
  'LA': 'Laos',
  'LB': 'Lebanon',
  'LK': 'Sri Lanka',
  'LT': 'Lithuania',
  'LV': 'Latvia',
  'LY': 'Libya',
  'MA': 'Morocco',
  'MC': 'Monaco',
  'MD': 'Moldova',
  'MH': 'Marshall Is.',
  'MN': 'Mongolia',
  'MR': 'Mauritania',
  'MU': 'Mauritius',
  'MV': 'Maldives',
  'MX': 'Mexico',
  'MY': 'Malaysia',
  'MYM': 'Myanmar',
  'N': 'Norway',
  'NG': 'Nigeria',
  'NL': 'Netherlands',
  'NP': 'Nepal',
  'NZ': 'New Zealand',
  'NZRD': 'Ross Dep.',
  'P': 'Portugal',
  'PAR': 'Panama',
  'PCZ': 'Canal Zone',
  'PE': 'Peru',
  'PG': 'Papua New Guinea',
  'PK': 'Pakistan',
  'PH': 'Phillipines',
  'PL': 'Poland',
  'PLRL': 'Poland',
  'PR': 'Puerto Rico',
  'PT': 'Portugal',
  'PY': 'Paraguay',
  'QA': 'Qatar',
  'RO': 'Romania',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'S': 'Sweden',
  'SA': 'Saudi Arabia',
  'SCOT': 'Scotland',
  'SD': 'Sudan',
  'SG': 'Singapore',
  'SH': 'St Helena',
  'SI': 'Slovenia',
  'SK': 'Slovakia',
  'SR': 'Suriname',
  'SU': 'USSR',
  'SY': 'Syria',
  'T': 'Thailand',
  'TC': 'Turks and Caicos',
  'TF': 'French SAL',
  'TJ': 'Tajikistan',
  'TM': 'Turkmenistan',
  'TN': 'Tunisia',
  'TO': 'Tonga',
  'TR': 'Turkey',
  'TTPI': 'TTPI',
  'TUVA': 'Tuva',
  'TW': 'Taiwan',
  'UA': 'Ukraine',
  'UAE': 'United Arab Emirates',
  'UK': 'United Kingdom',
  'UM': 'Wake I.',
  'US': 'United States',
  'UY': 'Uruguay',
  'UZ': 'Uzbekistan',
  'VE': 'Venezuela',
  'VN': 'Vietnam',
  'YE': 'Yemen',
  'ZA': 'South Africa',
  'ZR': 'Zaire',
  'ANALSAT': 'Analyst Satellite',
  'SAUD': 'Saudi Arabia',
  'AB': 'Saudi Arabia',
  'AC': 'AsiaSat Corp',
  'ALG': 'Algeria',
  'ALL': 'All',
  'ARGN': 'Argentina',
  'ASRA': 'Austria',
  'AUS': 'Australia',
  'AZER': 'Azerbaijan',
  'BEL': 'Belgium',
  'BELA': 'Belarus',
  'BERM': 'Bermuda',
  'BOL': 'Bolivia',
  'BRAZ': 'Brazil',
  'CHBZ': 'China/Brazil',
  'CHLE': 'Chile',
  'CIS': 'USSR/Russia',
  'COL': 'Colombia',
  'CZCH': 'Czechoslovakia',
  'DEN': 'Denmark',
  'ECU': 'Ecuador',
  'EGYP': 'Egypt',
  'ESA': 'European Space Agency',
  'I-ESA': 'European Space Agency',
  'EST': 'Estonia',
  'EUME': 'EUMETSAT',
  'EUTE': 'EUTELSAT',
  'FIN': 'Finland',
  'FGER': 'France/Germany',
  'FR': 'France',
  'FRIT': 'France/Italy',
  'GER': 'Germany',
  'GLOB': 'United States',
  'GREC': 'Greece',
  'HUN': 'Hungary',
  'IM': 'United Kingdom',
  'IND': 'India',
  'INDO': 'Indonesia',
  'IRAN': 'Iran',
  'IRAQ': 'Iraq',
  'ISRA': 'Israel',
  'ISS': 'International',
  'IT': 'Italy',
  'ITSO': 'Luxembourg',
  'JPN': 'Japan',
  'KAZ': 'Kazakhstan',
  'LAOS': 'Laos',
  'LTU': 'Lithuania',
  'LUXE': 'Luxembourg',
  'MALA': 'Malaysia',
  'MEX': 'Mexico',
  'NATO': 'North Atlantic Treaty Org',
  'NETH': 'Netherlands',
  'NICO': 'United States',
  'NIG': 'Nigeria',
  'NKOR': 'North Korea',
  'NOR': 'Norway',
  'O3B': 'Luxembourg',
  'ORB': 'United States',
  'PAKI': 'Pakistan',
  'PERU': 'Peru',
  'POL': 'Poland',
  'POR': 'Portugal',
  'PRC': 'China',
  'RASC': 'Mauritius',
  'ROC': 'Taiwan',
  'Taiwan': 'Taiwan',
  'ROM': 'Romania',
  'SAFR': 'South Africa',
  'SEAL': 'Russia',
  'RP': 'Philippines',
  'SES': 'Luxembourg',
  'SING': 'Singapore',
  'SKOR': 'South Korea',
  'SPN': 'Spain',
  'STCT': 'Singapore/Taiwan',
  'SWED': 'Sweden',
  'SWTZ': 'Switzerland',
  'THAI': 'Thailand',
  'TMMC': 'Turkmenistan/Monaco',
  'TURK': 'Turkey',
  'UKR': 'Ukraine',
  'URY': 'Uruguay',
  'USA': 'United States',
  'USBZ': 'United States/Brazil',
  'VENZ': 'Venezuela',
  'VTNM': 'Vietnam',
  'TBD': 'Unknown',
};

export const launchSiteMap = {
  ANALSAT: {
    site: 'Analyst Satellite',
    sitec: 'Analyst Satellite',
  },
  AFETR: {
    site: 'Cape Canaveral SFS',
    sitec: 'United States',
  },
  AFWTR: {
    site: 'Vandenberg AFB',
    sitec: 'United States',
  },
  CAS: {
    site: 'Canary Islands',
    sitec: 'United States',
  },
  FRGUI: {
    site: 'French Guiana',
    sitec: 'French Guiana',
  },
  HGSTR: {
    site: 'Hammaguira STR',
    sitec: 'Algeria',
  },
  KSCUT: {
    site: 'Uchinoura Space Center',
    sitec: 'Japan',
  },
  KYMTR: {
    site: 'Kapustin Yar MSC',
    sitec: 'Russia',
  },
  PKMTR: {
    site: 'Plesetsk MSC',
    sitec: 'Russia',
  },
  WSC: {
    site: 'Wenchang SLC',
    sitec: 'China',
  },
  SNMLP: {
    site: 'San Marco LP',
    sitec: 'Kenya',
  },
  SRI: {
    site: 'Satish Dhawan SC',
    sitec: 'India',
  },
  TNSTA: {
    site: 'Tanegashima SC',
    sitec: 'Japan',
  },
  TTMTR: {
    site: 'Baikonur Cosmodrome',
    sitec: 'Kazakhstan',
  },
  WLPIS: {
    site: 'Wallops Island',
    sitec: 'United States',
  },
  WOMRA: {
    site: 'Woomera',
    sitec: 'Australia',
  },
  VOSTO: {
    site: 'Vostochny Cosmodrome',
    sitec: 'Russia',
  },
  PMRF: {
    site: 'PMRF Barking Sands',
    sitec: 'United States',
  },
  SEAL: {
    site: 'Sea Launch Odyssey',
    sitec: 'Russia',
  },
  KWAJ: {
    site: 'Kwajalein',
    sitec: 'United States',
  },
  ERAS: {
    site: 'Pegasus East',
    sitec: 'United States',
  },
  JSC: {
    site: 'Jiuquan SLC',
    sitec: 'China',
  },
  SVOB: {
    site: 'Svobodny',
    sitec: 'Russia',
  },
  TSC: {
    site: 'Taiyaun SC',
    sitec: 'China',
  },
  WRAS: {
    site: 'Pegasus West',
    sitec: 'United States',
  },
  XSC: {
    site: 'Xichang SC',
    sitec: 'China',
  },
  YAVNE: {
    site: 'Yavne',
    sitec: 'Israel',
  },
  OREN: {
    site: 'Orenburg',
    sitec: 'Russia',
  },
  SADOL: {
    site: 'Submarine Launch',
    sitec: 'Russia',
  },
  KODAK: {
    site: 'Kodiak Island',
    sitec: 'United States',
  },
  SEM: {
    site: 'Semnan',
    sitec: 'Iran',
  },
  YUN: {
    site: 'Sohae SLS',
    sitec: 'North Korea',
  },
  TNGH: {
    site: 'Tonghae SLG',
    sitec: 'North Korea',
  },
  NSC: {
    site: 'Naro Space Center',
    sitec: 'South Korea',
  },
  RLLC: {
    site: 'Rocket Labs LC',
    sitec: 'New Zealand',
  },
  AMH: {
    site: "A' Mhòine",
    sitec: 'Scotland',
  },
  ALC: {
    site: 'Alcântara Launch Center',
    sitec: 'Brazil',
  },
};
