export const rocketUrls = [
  { rocket: 'Vanugard', url: 'https://en.wikipedia.org/wiki/Vanguard_(rocket)' },
  { rocket: 'Juno II', url: 'https://en.wikipedia.org/wiki/Juno_II' },
  { rocket: 'Thor Able II', url: 'https://en.wikipedia.org/wiki/Thor-Able' },
  { rocket: 'Thor Ablestar', url: 'https://en.wikipedia.org/wiki/Thor-Ablestar' },
  { rocket: 'Thor Delta', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Atlas Agena B', url: 'https://en.wikipedia.org/wiki/Atlas-Agena' },
  { rocket: 'Scout X-2M', url: 'https://en.wikipedia.org/wiki/Scout_(rocket_family)' },
  { rocket: 'Thor Agena B', url: 'https://en.wikipedia.org/wiki/Thor-Agena' },
  { rocket: 'Thor Delta B', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Scout X-3', url: 'https://en.wikipedia.org/wiki/Scout_(rocket_family)' },
  { rocket: 'Thor SLV-2A Age', url: 'https://en.wikipedia.org/wiki/Thor-Agena' },
  { rocket: 'Atlas Agena D', url: 'https://en.wikipedia.org/wiki/Atlas-Agena' },
  { rocket: 'Atlas Centaur', url: 'https://en.wikipedia.org/wiki/Atlas-Centaur' },
  { rocket: 'Scout X-4', url: 'https://en.wikipedia.org/wiki/Scout_(rocket_family)' },
  { rocket: 'Thor SLV-2 Agena D', url: 'https://en.wikipedia.org/wiki/Thor-Agena' },
  { rocket: 'Thor SLV-2 Agen', url: 'https://en.wikipedia.org/wiki/Thor-Agena' },
  { rocket: 'Thor SLV-2 Agena B', url: 'https://en.wikipedia.org/wiki/Thor-Agena' },
  { rocket: 'Vostok 8K72', url: 'https://en.wikipedia.org/wiki/Vostok_(rocket_family)' },
  { rocket: 'Vostok 8K72K', url: 'https://en.wikipedia.org/wiki/Vostok_(rocket_family)' },
  { rocket: 'Thor Delta D', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Vostok 8A92M', url: 'https://en.wikipedia.org/wiki/Vostok_(rocket_family)' },
  { rocket: 'Thor Delta C', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Titan IIIA', url: 'https://en.wikipedia.org/wiki/Titan_IIIA' },
  { rocket: 'Atlas SLV-3 Age', url: 'https://en.wikipedia.org/wiki/Atlas-Agena' },
  { rocket: 'Atlas SLV-3 Agena D', url: 'https://en.wikipedia.org/wiki/Atlas-Agena' },
  { rocket: 'Kosmos 65S3', url: 'https://en.wikipedia.org/wiki/Kosmos-2I' },
  { rocket: 'Scout B', url: 'https://en.wikipedia.org/wiki/Scout_(rocket_family)' },
  { rocket: 'Thor Burner 1', url: 'https://en.wikipedia.org/wiki/Thor-Burner' },
  { rocket: 'Atlas D', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Titan IIIC', url: 'https://en.wikipedia.org/wiki/Titan_IIIC' },
  { rocket: 'Thor Delta E', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Diamant A', url: 'https://en.wikipedia.org/wiki/Diamant' },
  { rocket: 'Scout A', url: 'https://en.wikipedia.org/wiki/Scout_(rocket_family)' },
  { rocket: 'Thor SLV-2A Agena B', url: 'https://en.wikipedia.org/wiki/Thor-Agena' },
  { rocket: 'Thor SLV-2A Agena D', url: 'https://en.wikipedia.org/wiki/Thor-Agena' },
  { rocket: 'Thor Burner 2', url: 'https://en.wikipedia.org/wiki/Thor-Burner' },
  { rocket: 'Thor Delta E1', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Kosmos 11K65M', url: 'https://en.wikipedia.org/wiki/Kosmos-2I' },
  { rocket: 'Tsiklon-2A', url: 'https://en.wikipedia.org/wiki/Tsyklon-2' },
  { rocket: 'Atlas F', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Thor Delta J', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Atlas SLV-3A Ag', url: 'https://en.wikipedia.org/wiki/Atlas-Agena' },
  { rocket: 'Thor Delta N', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Atlas SLV-3C Ce', url: 'https://en.wikipedia.org/wiki/Atlas-Agena' },
  { rocket: 'Atlas SLV-3C Centaur', url: 'https://en.wikipedia.org/wiki/Atlas-Centaur' },
  { rocket: 'Thorad SLV-2G A', url: 'https://en.wikipedia.org/wiki/Thorad-Agena' },
  { rocket: 'Thorad SLV-2G Agena D', url: 'https://en.wikipedia.org/wiki/Thorad-Agena' },
  { rocket: 'Thor Delta M', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Thor Delta N6', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Chang Zheng 1', url: 'https://en.wikipedia.org/wiki/Long_March_1' },
  { rocket: 'Tsiklon-2', url: 'https://en.wikipedia.org/wiki/Tsyklon-2' },
  { rocket: 'Proton-K/D', url: 'https://en.wikipedia.org/wiki/Proton-K' },
  { rocket: 'Mu-4S', url: 'https://en.wikipedia.org/wiki/Mu_(rocket_family)' },
  { rocket: 'Soyuz 11A511L', url: 'https://en.wikipedia.org/wiki/Soyuz_(rocket)' },
  { rocket: 'Scout B-1', url: 'https://en.wikipedia.org/wiki/Scout_(rocket_family)' },
  { rocket: 'Thor Burner 2A', url: 'https://en.wikipedia.org/wiki/Thor-Burner' },
  { rocket: 'Black Arrow', url: 'https://en.wikipedia.org/wiki/Black_Arrow' },
  { rocket: 'Molniya 8K78M', url: 'https://en.wikipedia.org/wiki/Molniya_(rocket)' },
  { rocket: 'Delta 0900', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 1604', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Atlas Burner 2', url: 'https://en.wikipedia.org/wiki/Atlas-Burner' },
  { rocket: 'Delta 0300', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 1914', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Titan 33B', url: 'https://en.wikipedia.org/wiki/Titan_33B' },
  { rocket: 'Atlas SLV-3D Centaur', url: 'https://en.wikipedia.org/wiki/Atlas-Centaur' },
  { rocket: 'Titan IIID', url: 'https://en.wikipedia.org/wiki/Titan_IIID' },
  { rocket: 'Scout A-1', url: 'https://en.wikipedia.org/wiki/Scout_(rocket_family)' },
  { rocket: 'Scout D-1', url: 'https://en.wikipedia.org/wiki/Scout_(rocket_family)' },
  { rocket: 'Proton-K/DM', url: 'https://en.wikipedia.org/wiki/Proton-K' },
  { rocket: 'Delta 2914', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Atlas F/PTS', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Delta 2310', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Atlas SLV-3D Ce', url: 'https://en.wikipedia.org/wiki/Atlas-Agena' },
  { rocket: 'Delta 2313', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Diamant BP.4', url: 'https://en.wikipedia.org/wiki/Diamant' },
  { rocket: 'Delta 1410', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 2910', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'N-1', url: 'https://en.wikipedia.org/wiki/N1_(rocket)' },
  { rocket: 'Delta 3914', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 2913', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Atlas F/MSD', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Thor DSV-2U', url: 'https://en.wikipedia.org/wiki/Thorad-Agena' },
  { rocket: 'Mu-3H', url: 'https://en.wikipedia.org/wiki/Mu_(rocket_family)' },
  { rocket: 'Atlas F/SVS', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Tsiklon-3', url: 'https://en.wikipedia.org/wiki/Tsyklon-3' },
  { rocket: 'Atlas F/Agena D', url: 'https://en.wikipedia.org/wiki/Atlas-Agena' },
  { rocket: 'Titan 34B', url: 'https://en.wikipedia.org/wiki/Titan_34B' },
  { rocket: 'N-2', url: 'https://en.wikipedia.org/wiki/N2_(rocket)' },
  { rocket: 'Scout G-1', url: 'https://en.wikipedia.org/wiki/Scout_(rocket_family)' },
  { rocket: 'Ariane 1', url: 'https://en.wikipedia.org/wiki/Ariane_1' },
  { rocket: 'Delta 3913', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 3910/PAM', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 3920', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 3920/PAM', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Proton-K/DM-2', url: 'https://en.wikipedia.org/wiki/Proton-K' },
  { rocket: 'Delta 3924', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Titan 34D/IUS', url: 'https://en.wikipedia.org/wiki/Titan_34D' },
  { rocket: 'Space Shuttle', url: 'https://en.wikipedia.org/wiki/Space_Shuttle' },
  { rocket: 'Atlas E', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Delta 3910', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Atlas H', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Proton-K/D-1', url: 'https://en.wikipedia.org/wiki/Proton-K' },
  { rocket: 'Titan 34D', url: 'https://en.wikipedia.org/wiki/Titan_34D' },
  { rocket: 'Atlas E/SGS-2', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Chang Zheng 3', url: 'https://en.wikipedia.org/wiki/Long_March_3' },
  { rocket: 'Titan 34D/Trans,', url: 'https://en.wikipedia.org/wiki/Titan_34D' },
  { rocket: 'Ariane 3', url: 'https://en.wikipedia.org/wiki/Ariane_3' },
  { rocket: 'Atlas E/OIS', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Atlas G Centaur', url: 'https://en.wikipedia.org/wiki/Atlas-Centaur' },
  { rocket: 'Zenit-2', url: 'https://en.wikipedia.org/wiki/Zenit_(rocket_family)' },
  { rocket: 'H-1', url: 'https://en.wikipedia.org/wiki/H-I' },
  { rocket: 'Ariane 2', url: 'https://en.wikipedia.org/wiki/Ariane_2' },
  { rocket: 'Soyuz-U', url: 'https://en.wikipedia.org/wiki/Soyuz_(rocket)' },
  { rocket: 'Ariane 44LP', url: 'https://en.wikipedia.org/wiki/Ariane_4' },
  { rocket: 'Chang Zheng 4', url: 'https://en.wikipedia.org/wiki/Long_March_4' },
  { rocket: 'Delta 6925', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Mu-3S-II', url: 'https://en.wikipedia.org/wiki/Mu_(rocket_family)' },
  { rocket: 'Ariane 44L', url: 'https://en.wikipedia.org/wiki/Ariane_4' },
  { rocket: 'Titan 402A/IUS', url: 'https://en.wikipedia.org/wiki/Titan_II' },
  { rocket: 'Delta 5920-8', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Commercial Tita', url: 'https://en.wikipedia.org/wiki/Titan_II' },
  { rocket: 'Commercial Titan 3', url: 'https://en.wikipedia.org/wiki/Titan_III' },
  { rocket: 'Ariane 40', url: 'https://en.wikipedia.org/wiki/Ariane_4' },
  { rocket: 'Atlas I', url: 'https://en.wikipedia.org/wiki/Atlas_I' },
  { rocket: 'Pegasus', url: 'https://en.wikipedia.org/wiki/Pegasus_(rocket)' },
  { rocket: 'Atlas E Altair', url: 'https://en.wikipedia.org/wiki/Atlas_(rocket_family)' },
  { rocket: 'Delta 6925-8', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 4925-8', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Molniya 8K78M-P', url: 'https://en.wikipedia.org/wiki/Molniya_(rocket)' },
  { rocket: 'Molniya 8K78M-PVB', url: 'https://en.wikipedia.org/wiki/Molniya_(rocket)' },
  { rocket: 'Ariane 42P', url: 'https://en.wikipedia.org/wiki/Ariane_4' },
  { rocket: 'Delta 7925', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Ariane 44P', url: 'https://en.wikipedia.org/wiki/Ariane_4' },
  { rocket: 'Atlas II', url: 'https://en.wikipedia.org/wiki/Atlas_II' },
  { rocket: 'Chang Zheng 2E', url: 'https://en.wikipedia.org/wiki/Long_March_2' },
  { rocket: 'Chang Zheng 2C', url: 'https://en.wikipedia.org/wiki/Long_March_2' },
  { rocket: 'Start-1', url: 'https://en.wikipedia.org/wiki/Start-1' },
  { rocket: 'Ariane 42L', url: 'https://en.wikipedia.org/wiki/Ariane_4' },
  { rocket: 'Atlas IIAS', url: 'https://en.wikipedia.org/wiki/Atlas_II' },
  { rocket: 'Proton-K/DM-2M', url: 'https://en.wikipedia.org/wiki/Proton-K' },
  { rocket: 'H-II', url: 'https://en.wikipedia.org/wiki/H-II' },
  { rocket: 'Titan 401A/Cent', url: 'https://en.wikipedia.org/wiki/Titan_III' },
  { rocket: 'Chang Zheng 3A', url: 'https://en.wikipedia.org/wiki/Long_March_3' },
  { rocket: 'Delta 7925-8', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Pegasus/HAPS', url: 'https://en.wikipedia.org/wiki/Pegasus_(rocket)' },
  { rocket: 'Atlas IIA', url: 'https://en.wikipedia.org/wiki/Atlas_II' },
  { rocket: 'PSLV', url: 'https://en.wikipedia.org/wiki/Polar_Satellite_Launch_Vehicle' },
  { rocket: 'Rokot', url: 'https://en.wikipedia.org/wiki/Rokot' },
  { rocket: 'Pegasus H', url: 'https://en.wikipedia.org/wiki/Pegasus_(rocket)' },
  { rocket: 'Delta 7920-10', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 7925-10', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Pegasus XL', url: 'https://en.wikipedia.org/wiki/Pegasus_(rocket)' },
  { rocket: 'M-V', url: 'https://en.wikipedia.org/wiki/M-V' },
  { rocket: 'Titan 402B/IUS', url: 'https://en.wikipedia.org/wiki/Titan_II' },
  { rocket: 'Titan II SLV', url: 'https://en.wikipedia.org/wiki/Titan_II' },
  { rocket: 'Delta 7920-10C', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Proton-K/17S40', url: 'https://en.wikipedia.org/wiki/Proton-K' },
  { rocket: 'Chang Zheng 2C-', url: 'https://en.wikipedia.org/wiki/Long_March_2' },
  { rocket: 'Chang Zheng 3B', url: 'https://en.wikipedia.org/wiki/Long_March_3' },
  { rocket: 'Ariane 5G', url: 'https://en.wikipedia.org/wiki/Ariane_5' },
  { rocket: 'Pegasus XL/HAPS', url: 'https://en.wikipedia.org/wiki/Pegasus_(rocket)' },
  { rocket: 'Delta 7925-9.5', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Taurus 2210', url: 'https://en.wikipedia.org/wiki/Taurus_(rocket)' },
  { rocket: 'Delta 7420-10C', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'ARPA Taurus', url: 'https://en.wikipedia.org/wiki/Taurus_(rocket)' },
  { rocket: 'Delta 7326-9.5', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Proton-K', url: 'https://en.wikipedia.org/wiki/Proton-K' },
  { rocket: 'Delta 7426-9.5', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Soyuz-U-PVB', url: 'https://en.wikipedia.org/wiki/Soyuz_(rocket)' },
  { rocket: 'Zenit-3SL', url: 'https://en.wikipedia.org/wiki/Zenit_(rocket_family)' },
  { rocket: 'Dnepr', url: 'https://en.wikipedia.org/wiki/Dnepr_(rocket)' },
  { rocket: 'Delta 8930', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Chang Zheng 4B', url: 'https://en.wikipedia.org/wiki/Long_March_4' },
  { rocket: 'Delta 7320-10', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Athena-2', url: 'https://en.wikipedia.org/wiki/Athena_(rocket_family)' },
  { rocket: 'Taurus 2110', url: 'https://en.wikipedia.org/wiki/Taurus_(rocket)' },
  { rocket: 'Minotaur I', url: 'https://en.wikipedia.org/wiki/Minotaur_I' },
  { rocket: 'Minotaur 1', url: 'https://en.wikipedia.org/wiki/Minotaur_I' },
  { rocket: 'Taurus 1110', url: 'https://en.wikipedia.org/wiki/Taurus_(rocket)' },
  { rocket: 'Proton-K/Briz-M', url: 'https://en.wikipedia.org/wiki/Proton-K' },
  { rocket: 'Titan 403B', url: 'https://en.wikipedia.org/wiki/Titan_III' },
  { rocket: 'Titan 401B/Cent', url: 'https://en.wikipedia.org/wiki/Titan_III' },
  { rocket: 'Proton-M/Briz-M', url: 'https://en.wikipedia.org/wiki/Proton-M' },
  { rocket: 'GSLV Mk I', url: 'https://en.wikipedia.org/wiki/Geosynchronous_Satellite_Launch_Vehicle_Mk_I' },
  { rocket: 'H-IIA 202', url: 'https://en.wikipedia.org/wiki/H-IIA' },
  { rocket: 'Athena-1', url: 'https://en.wikipedia.org/wiki/Athena_(rocket_family)' },
  { rocket: 'H-IIA 2024', url: 'https://en.wikipedia.org/wiki/H-IIA' },
  { rocket: 'Delta 7920-10L', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Atlas V 401', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Delta 4M+(4,2)', url: 'https://en.wikipedia.org/wiki/Delta_IV' },
  { rocket: 'Delta 4M', url: 'https://en.wikipedia.org/wiki/Delta_IV' },
  { rocket: 'Atlas 3B', url: 'https://en.wikipedia.org/wiki/Atlas_III' },
  { rocket: 'Atlas V 521', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Soyuz-FG', url: 'https://en.wikipedia.org/wiki/Soyuz_(rocket)' },
  { rocket: 'Atlas 3A', url: 'https://en.wikipedia.org/wiki/Atlas_III' },
  { rocket: 'Taurus 3210', url: 'https://en.wikipedia.org/wiki/Taurus_(rocket)' },
  { rocket: 'Ariane 5G+', url: 'https://en.wikipedia.org/wiki/Ariane_5' },
  { rocket: 'Delta 7320-10C', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 4H', url: 'https://en.wikipedia.org/wiki/Delta_IV' },
  { rocket: 'Ariane 5ECA', url: 'https://en.wikipedia.org/wiki/Ariane_5' },
  { rocket: 'H-IIA 2022', url: 'https://en.wikipedia.org/wiki/H-IIA' },
  { rocket: 'Atlas V 431', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Chang Zheng 2D', url: 'https://en.wikipedia.org/wiki/Long_March_2' },
  { rocket: 'Ariane 5GS', url: 'https://en.wikipedia.org/wiki/Ariane_5' },
  { rocket: 'Atlas V 411', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Chang Zheng 4C', url: 'https://en.wikipedia.org/wiki/Long_March_4' },
  { rocket: 'Soyuz-2-1A', url: 'https://en.wikipedia.org/wiki/Soyuz-2' },
  { rocket: 'H-IIA 204', url: 'https://en.wikipedia.org/wiki/H-IIA' },
  { rocket: 'Soyuz-2-1B', url: 'https://en.wikipedia.org/wiki/Soyuz-2' },
  { rocket: 'Delta 7925-10C', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Zenit-2M', url: 'https://en.wikipedia.org/wiki/Zenit_(rocket_family)' },
  { rocket: 'Atlas V 421', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Proton-M/DM-2', url: 'https://en.wikipedia.org/wiki/Proton-M' },
  { rocket: 'Chang Zheng 3C', url: 'https://en.wikipedia.org/wiki/Long_March_3' },
  { rocket: 'Zenit-3SLB', url: 'https://en.wikipedia.org/wiki/Zenit_(rocket_family)' },
  { rocket: 'Delta 7920H', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Falcon 1', url: 'https://en.wikipedia.org/wiki/Falcon_1' },
  { rocket: 'PSLV-XL', url: 'https://en.wikipedia.org/wiki/Polar_Satellite_Launch_Vehicle' },
  { rocket: 'Delta 7925-10L', url: 'https://en.wikipedia.org/wiki/Delta_(rocket)' },
  { rocket: 'Delta 4M+(5,4)', url: 'https://en.wikipedia.org/wiki/Delta_IV' },
  { rocket: 'Atlas V 531', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Minotaur IV', url: 'https://en.wikipedia.org/wiki/Minotaur_IV' },
  { rocket: 'Falcon 9', url: 'https://en.wikipedia.org/wiki/Falcon_9' },
  { rocket: 'Zenit-3SLBF', url: 'https://en.wikipedia.org/wiki/Zenit_(rocket_family)' },
  { rocket: 'Minotaur IV+', url: 'https://en.wikipedia.org/wiki/Minotaur_IV' },
  { rocket: 'Soyuz-ST-B', url: 'https://en.wikipedia.org/wiki/Soyuz-2' },
  { rocket: 'Soyuz-ST-A', url: 'https://en.wikipedia.org/wiki/Soyuz-2' },
  { rocket: 'Vega', url: 'https://en.wikipedia.org/wiki/Vega_(rocket)' },
  { rocket: 'Atlas V 551', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Atlas SLV-3A Agena D', url: 'https://en.wikipedia.org/wiki/Atlas-Agena' },
  { rocket: 'Unha-3', url: 'https://en.wikipedia.org/wiki/Unha' },
  { rocket: 'Strela', url: 'https://en.wikipedia.org/wiki/Strela_(rocket)' },
  { rocket: 'Epsilon', url: 'https://en.wikipedia.org/wiki/Epsilon_(rocket)' },
  { rocket: 'Atlas V 501', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Soyuz-2-1V', url: 'https://en.wikipedia.org/wiki/Soyuz-2' },
  { rocket: 'GSLV Mk II', url: 'https://en.wikipedia.org/wiki/Geosynchronous_Satellite_Launch_Vehicle_Mk_II' },
  { rocket: 'Angara A5', url: 'https://en.wikipedia.org/wiki/Angara_(rocket_family)' },
  { rocket: 'Chang Zheng 3C/', url: 'https://en.wikipedia.org/wiki/Long_March_3' },
  { rocket: 'Chang Zheng 3B/', url: 'https://en.wikipedia.org/wiki/Long_March_3' },
  { rocket: 'Chang Zheng 3B/YZ-1', url: 'https://en.wikipedia.org/wiki/Long_March_3' },
  { rocket: 'Proton-M/DM-3', url: 'https://en.wikipedia.org/wiki/Proton-M' },
  { rocket: 'Chang Zheng 6', url: 'https://en.wikipedia.org/wiki/Long_March_6' },
  { rocket: 'Chang Zheng 11', url: 'https://en.wikipedia.org/wiki/Long_March_11' },
  { rocket: 'Chang Zheng 3C/YZ-1', url: 'https://en.wikipedia.org/wiki/Long_March_3' },
  { rocket: 'Chang Zheng 5/Y', url: 'https://en.wikipedia.org/wiki/Long_March_5' },
  { rocket: 'Chang Zheng 5/YZ-2', url: 'https://en.wikipedia.org/wiki/Long_March_5' },
  { rocket: 'Ariane 5ES', url: 'https://en.wikipedia.org/wiki/Ariane_5' },
  { rocket: 'Atlas V 541', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Antares 230', url: 'https://en.wikipedia.org/wiki/Antares_(rocket)' },
  { rocket: 'Kuaizhou-1A', url: 'https://en.wikipedia.org/wiki/Kuaizhou-1' },
  { rocket: 'GSLV Mk III', url: 'https://en.wikipedia.org/wiki/Geosynchronous_Satellite_Launch_Vehicle_Mk_III' },
  { rocket: 'Minotaur-C 3210', url: 'https://en.wikipedia.org/wiki/Minotaur-C' },
  { rocket: 'Electron', url: 'https://en.wikipedia.org/wiki/Electron_(rocket)' },
  { rocket: 'Change Zheng 2C/', url: 'https://en.wikipedia.org/wiki/Long_March_2' },
  { rocket: 'Chang Zheng 2D/', url: 'https://en.wikipedia.org/wiki/Long_March_2' },
  { rocket: 'PSLV-DL', url: 'https://en.wikipedia.org/wiki/Polar_Satellite_Launch_Vehicle' },
  { rocket: 'Delta 4M+(5,2)', url: 'https://en.wikipedia.org/wiki/Delta_IV' },
  { rocket: 'PSLV-QL', url: 'https://en.wikipedia.org/wiki/Polar_Satellite_Launch_Vehicle' },
  { rocket: 'Falcon Heavy', url: 'https://en.wikipedia.org/wiki/Falcon_Heavy' },
  { rocket: 'Ariane 5ECA+', url: 'https://en.wikipedia.org/wiki/Ariane_5' },
  { rocket: 'Jielong-1', url: 'https://en.wikipedia.org/wiki/Jielong_(rocket_family)' },
  { rocket: 'Chang Zheng 5', url: 'https://en.wikipedia.org/wiki/Long_March_5' },
  { rocket: 'Chang Zheng 8', url: 'https://en.wikipedia.org/wiki/Long_March_8' },
  { rocket: 'LauncherOne', url: 'https://en.wikipedia.org/wiki/LauncherOne' },
  { rocket: 'Chang Zheng 7A', url: 'https://en.wikipedia.org/wiki/Long_March_7' },
  { rocket: 'Chang Zheng 5B', url: 'https://en.wikipedia.org/wiki/Long_March_5' },
  { rocket: 'Antares 230+', url: 'https://en.wikipedia.org/wiki/Antares_(rocket)' },
  { rocket: 'Gushenxing 1', url: 'https://en.wikipedia.org/wiki/Smart_Dragon' },
  { rocket: 'Atlas V 511', url: 'https://en.wikipedia.org/wiki/Atlas_V' },
  { rocket: 'Qased', url: 'https://en.wikipedia.org/wiki/Qased_(rocket)' },
  { rocket: 'Astra Rocket 3.', url: 'https://en.wikipedia.org/wiki/Astra_(rocket)' },
  { rocket: 'Chang Zheng 6A', url: 'https://en.wikipedia.org/wiki/Long_March_6' },
  { rocket: 'Nuri', url: 'https://en.wikipedia.org/wiki/Nuri_(rocket)' },
  { rocket: 'Vega C', url: 'https://en.wikipedia.org/wiki/Vega_(rocket)' },
  { rocket: 'Lijian-1', url: 'https://en.wikipedia.org/wiki/Lijian' },
  { rocket: 'LVM3', url: 'https://en.wikipedia.org/wiki/Geosynchronous_Satellite_Launch_Vehicle_Mk_III' },
  { rocket: 'Kuaizhou-11', url: 'https://en.wikipedia.org/wiki/Kuaizhou-11' },
  { rocket: 'Jielong-3', url: 'https://en.wikipedia.org/wiki/Jielong_(rocket_family)' },
  { rocket: 'SSLV', url: 'https://en.wikipedia.org/wiki/Small_Satellite_Launch_Vehicle' },
  { rocket: 'Tianlong 2', url: 'https://en.wikipedia.org/wiki/Tianlong_(rocket)' },
  { rocket: 'Zhuque-2', url: 'https://en.wikipedia.org/wiki/Zhuque_(rocket_family)' },
  { rocket: 'Firefly Alpha', url: 'https://en.wikipedia.org/wiki/Firefly_Aerospace' },
  { rocket: 'Proton-M', url: 'https://en.wikipedia.org/wiki/Proton-M' },
  { rocket: 'Chang Zheng 7', url: 'https://en.wikipedia.org/wiki/Long_March_7' },
  { rocket: 'Chang Zheng 2F', url: 'https://en.wikipedia.org/wiki/Long_March_2F' },
];
