/**
 * Submarine launch positioning for scripted mass raids.
 *
 * The raid sim files bake every launcher's trajectory from a fixed homeport placeholder
 * (the "Ohio Sub" shots start over North Dakota). At load time each nation's SLBM
 * launchers are gathered onto a realistic number of hulls - never more than the class's
 * real fleet - and each hull is placed at a distinct open-ocean patrol point spread
 * across that class's operating basins. Every launcher on a hull then re-flies from that
 * point to its own baked target (see {@link planSubmarineBoats}); the trajectory itself
 * is regenerated by the caller with `ballistic-trajectory.generateBallisticTrajectory`.
 *
 * This keeps the submarine COUNT realistic (a raid never implies 100 boats) while
 * spreading those boats widely instead of stacking them in one patrol box.
 */

/** Broad ocean basin a patrol box sits in; fleets patrol a subset of basins. */
export type OceanBasin = 'atlantic' | 'arctic' | 'pacific' | 'indian';

/** A rectangular patch of open ocean (deep water, clear of coasts) usable as an SSBN patrol box. */
export interface OceanRegion {
  name: string;
  ocean: OceanBasin;
  latMin: number;
  latMax: number;
  lonMin: number;
  lonMax: number;
}

/**
 * Curated open-ocean SSBN patrol boxes, deliberately many and widely separated so a
 * nation's boats spread across its operating areas rather than clustering. Every box is
 * deep water away from land; a random point inside any of them is at sea.
 */
export const OCEAN_PATROL_REGIONS: readonly OceanRegion[] = [
  // North Atlantic (US / UK / France / Russia surface routes)
  { name: 'West Atlantic Basin', ocean: 'atlantic', latMin: 33, latMax: 39, lonMin: -66, lonMax: -58 },
  { name: 'Sargasso Sea', ocean: 'atlantic', latMin: 26, latMax: 32, lonMin: -58, lonMax: -48 },
  { name: 'Newfoundland Basin', ocean: 'atlantic', latMin: 43, latMax: 49, lonMin: -42, lonMax: -34 },
  { name: 'Mid-Atlantic North', ocean: 'atlantic', latMin: 38, latMax: 44, lonMin: -46, lonMax: -38 },
  { name: 'Mid-Atlantic South', ocean: 'atlantic', latMin: 28, latMax: 35, lonMin: -44, lonMax: -36 },
  { name: 'Northeast Atlantic', ocean: 'atlantic', latMin: 48, latMax: 54, lonMin: -26, lonMax: -16 },
  { name: 'West European Basin', ocean: 'atlantic', latMin: 43, latMax: 47, lonMin: -17, lonMax: -11 },
  { name: 'Rockall Trough', ocean: 'atlantic', latMin: 55, latMax: 58, lonMin: -16, lonMax: -11 },
  { name: 'Labrador Sea', ocean: 'atlantic', latMin: 56, latMax: 60, lonMin: -50, lonMax: -44 },
  { name: 'Iceland Basin', ocean: 'atlantic', latMin: 60, latMax: 63, lonMin: -22, lonMax: -14 },
  // Arctic / Norwegian (Russian bastions)
  { name: 'Norwegian Sea', ocean: 'arctic', latMin: 66, latMax: 70, lonMin: -3, lonMax: 6 },
  { name: 'Greenland Sea', ocean: 'arctic', latMin: 72, latMax: 76, lonMin: -6, lonMax: 2 },
  { name: 'Barents Approach', ocean: 'arctic', latMin: 73, latMax: 77, lonMin: 28, lonMax: 40 },
  { name: 'Nansen Basin', ocean: 'arctic', latMin: 82, latMax: 85, lonMin: 60, lonMax: 100 },
  { name: 'Central Arctic', ocean: 'arctic', latMin: 84, latMax: 88, lonMin: 20, lonMax: 80 },
  // North Pacific (US / China / Russia)
  { name: 'Gulf of Alaska', ocean: 'pacific', latMin: 49, latMax: 55, lonMin: -148, lonMax: -138 },
  { name: 'Northeast Pacific', ocean: 'pacific', latMin: 41, latMax: 47, lonMin: -138, lonMax: -128 },
  { name: 'East Pacific', ocean: 'pacific', latMin: 30, latMax: 38, lonMin: -134, lonMax: -124 },
  { name: 'Off California', ocean: 'pacific', latMin: 29, latMax: 35, lonMin: -129, lonMax: -124 },
  { name: 'Central North Pacific', ocean: 'pacific', latMin: 32, latMax: 40, lonMin: -162, lonMax: -150 },
  { name: 'Mid Pacific', ocean: 'pacific', latMin: 22, latMax: 30, lonMin: -158, lonMax: -148 },
  { name: 'Emperor Seamounts', ocean: 'pacific', latMin: 38, latMax: 44, lonMin: 168, lonMax: 178 },
  { name: 'Western North Pacific', ocean: 'pacific', latMin: 40, latMax: 46, lonMin: 152, lonMax: 162 },
  { name: 'Kuril Approach', ocean: 'pacific', latMin: 44, latMax: 48, lonMin: 154, lonMax: 162 },
  { name: 'Shatsky Rise', ocean: 'pacific', latMin: 30, latMax: 36, lonMin: 156, lonMax: 164 },
  { name: 'Philippine Sea', ocean: 'pacific', latMin: 16, latMax: 24, lonMin: 130, lonMax: 140 },
  // Indian Ocean (no current fleet patrols here, but kept for range fallbacks)
  { name: 'Arabian Sea', ocean: 'indian', latMin: 12, latMax: 18, lonMin: 62, lonMax: 68 },
  { name: 'Bay of Bengal', ocean: 'indian', latMin: 10, latMax: 16, lonMin: 86, lonMax: 92 },
];

/** Beyond this great-circle range (km) an SLBM shot is filtered out as implausible. */
const MAX_SLBM_RANGE_KM = 11_000;
const EARTH_RADIUS_KM = 6371;
const DEG2RAD = Math.PI / 180;

/** True when a raid entry's description marks it as a submarine launch (e.g. "Ohio Sub (Trident II)"). */
export const isSubmarineLaunch = (desc: string | undefined): boolean => /\bsub\b/iu.test(desc ?? '');

/** A ballistic-missile submarine class: fleet size, tubes per boat, missile range, and patrol basins. */
export interface SubFleet {
  /** Number of hulls in the class - the hard cap on distinct launch positions. */
  fleetSize: number;
  /** Missile tubes per boat (informational; the raid may fire fewer). */
  capacity: number;
  /** Missile range (km) - targets beyond this are unreachable from the boat. */
  rangeKm: number;
  /** Ocean basins this class patrols (e.g. Chinese boats stay in the Pacific). */
  oceans: readonly OceanBasin[];
}

/**
 * SSBN classes keyed by the launcher name in the raid `desc` (the text before the
 * " (", e.g. "Ohio Sub (Trident II)" -> "Ohio Sub"). `fleetSize` is the real number of
 * boats, so a raid never implies more submarines than exist.
 */
export const SUBMARINE_FLEETS: Readonly<Record<string, SubFleet>> = {
  // USA - Trident II D5, near-global reach from Atlantic & Pacific patrols.
  'Ohio Sub': { fleetSize: 14, capacity: 20, rangeKm: 12_000, oceans: ['atlantic', 'pacific'] },
  // Russia - Bulava, Borei / Borei-A, Northern & Pacific fleets (6 of the 12-boat SSBN force).
  'Borei Sub': { fleetSize: 6, capacity: 16, rangeKm: 9_000, oceans: ['arctic', 'atlantic', 'pacific'] },
  // Russia - Sineva / Layner, Delta IV, Northern Fleet with longer legs (the other 6 SSBNs).
  'Delta IV Sub': { fleetSize: 6, capacity: 16, rangeKm: 11_000, oceans: ['arctic', 'atlantic'] },
  // China - Type 094 / 094A Jin-class (9 SSBNs), JL-2/JL-3 from the Pacific bastions.
  'Type 092 Sub': { fleetSize: 9, capacity: 12, rangeKm: 10_000, oceans: ['pacific'] },
  // UK - Trident II, North Atlantic.
  'Vanguard Sub': { fleetSize: 4, capacity: 16, rangeKm: 12_000, oceans: ['atlantic'] },
  // France - M51, North Atlantic.
  'Triomphant Sub': { fleetSize: 4, capacity: 16, rangeKm: 10_000, oceans: ['atlantic'] },
  // North Korea - experimental, short-ranged, near-shore Pacific.
  'Sinpo Sub': { fleetSize: 1, capacity: 6, rangeKm: 2_000, oceans: ['pacific'] },
};

/** Fallback fleet for an unrecognized submarine class. */
const DEFAULT_FLEET: SubFleet = { fleetSize: 4, capacity: 16, rangeKm: 10_000, oceans: ['atlantic', 'pacific'] };

/** The submarine class of a raid entry: the launcher name before the " (" in its `desc`. */
export const subClassOf = (desc: string | undefined): string => (desc ?? '').split(' (')[0].trim();

/** A submarine-launched raid entry awaiting a launch position (keeps its own baked target). */
export interface SubLaunchEntry {
  /** Index of this entry in the raid array (used to map the result back). */
  index: number;
  desc: string;
  /** The entry's baked target - used only to pick the nearest in-range boat. */
  targetLat: number;
  targetLon: number;
}

interface LatLon {
  lat: number;
  lon: number;
}

/** A random point uniformly inside an ocean region. */
const randomPointInRegion = (region: OceanRegion, rng: () => number): LatLon => ({
  lat: region.latMin + rng() * (region.latMax - region.latMin),
  lon: region.lonMin + rng() * (region.lonMax - region.lonMin),
});

/** Fisher-Yates shuffle into a new array, driven by the injected rng. */
const shuffled = <T>(items: readonly T[], rng: () => number): T[] => {
  const out = items.slice();

  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));

    [out[i], out[j]] = [out[j], out[i]];
  }

  return out;
};

/**
 * Plan a launch position for every submarine-launched raid entry.
 *
 * Entries are grouped by boat class and placed on `min(fleetSize, count)` distinct hulls -
 * i.e. the whole fleet deploys when there are enough missiles, so the boats spread as
 * widely as the class really can, but never more hulls than exist. Each hull sits at a
 * distinct random point in one of its class's patrol basins (Chinese boats stay in the
 * Pacific, Russian boats reach the Arctic, etc.), preferring basins in range of the
 * group's targets. Every entry is then assigned to the nearest hull that can range its
 * own baked target, so a boat's missiles stay geographically sensible.
 *
 * Returns a map from entry index -> its `{ launchLat, launchLon }`. `rng` is injectable
 * for deterministic tests. Targets are NOT modified here - each entry keeps the aimpoint
 * the generator baked, so RV labels stay correct.
 */
export const planSubmarineBoats = (entries: readonly SubLaunchEntry[], rng: () => number = Math.random): Map<number, { launchLat: number; launchLon: number }> => {
  const byClass = new Map<string, SubLaunchEntry[]>();

  for (const entry of entries) {
    const cls = subClassOf(entry.desc);
    const group = byClass.get(cls);

    if (group) {
      group.push(entry);
    } else {
      byClass.set(cls, [entry]);
    }
  }

  const result = new Map<number, { launchLat: number; launchLon: number }>();

  for (const [cls, group] of byClass) {
    const fleet = SUBMARINE_FLEETS[cls] ?? DEFAULT_FLEET;
    const basinRegions = OCEAN_PATROL_REGIONS.filter((r) => fleet.oceans.includes(r.ocean));
    const regions = basinRegions.length > 0 ? basinRegions : OCEAN_PATROL_REGIONS.slice();
    // Prefer patrol boxes within missile range of at least one target the group is striking.
    const inRange = regions.filter((r) => group.some((e) => greatCircleKm(regionCenterLat(r), regionCenterLon(r), e.targetLat, e.targetLon) <= fleet.rangeKm));
    const useRegions = shuffled(inRange.length > 0 ? inRange : regions, rng);

    // Deploy the whole fleet (up to one boat per missile) so the hulls spread out.
    const boatCount = Math.max(1, Math.min(fleet.fleetSize, group.length));
    const boats = Array.from({ length: boatCount }, (_unused, i) => randomPointInRegion(useRegions[i % useRegions.length], rng));
    const load = new Array<number>(boatCount).fill(0);

    for (const entry of group) {
      // Spread each boat's fire: among the hulls that can range this target, pick the
      // least-loaded one (falling back to the single nearest hull if none is in range).
      // Load-balancing is what actually surfaces the whole fleet - a pure "nearest boat"
      // rule collapses onto one hull whenever the targets cluster.
      let chosen = -1;

      for (let b = 0; b < boatCount; b++) {
        if (greatCircleKm(boats[b].lat, boats[b].lon, entry.targetLat, entry.targetLon) > fleet.rangeKm) {
          continue;
        }
        if (chosen === -1 || load[b] < load[chosen]) {
          chosen = b;
        }
      }

      if (chosen === -1) {
        chosen = nearestBoat(boats, entry.targetLat, entry.targetLon);
      }

      load[chosen]++;
      result.set(entry.index, { launchLat: boats[chosen].lat, launchLon: boats[chosen].lon });
    }
  }

  return result;
};

/** Index of the boat closest (great-circle) to a target lat/lon. */
const nearestBoat = (boats: readonly { lat: number; lon: number }[], targetLat: number, targetLon: number): number => {
  let chosen = -1;
  let nearestDist = Infinity;

  for (let b = 0; b < boats.length; b++) {
    const d = greatCircleKm(boats[b].lat, boats[b].lon, targetLat, targetLon);

    if (d < nearestDist) {
      nearestDist = d;
      chosen = b;
    }
  }

  return chosen;
};

/** Great-circle distance (km) between two lat/lon points on a spherical Earth. */
const greatCircleKm = (lat1: number, lon1: number, lat2: number, lon2: number): number => {
  const dLat = (lat2 - lat1) * DEG2RAD;
  const dLon = (lon2 - lon1) * DEG2RAD;
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(lat1 * DEG2RAD) * Math.cos(lat2 * DEG2RAD) * Math.sin(dLon / 2) ** 2;

  return 2 * EARTH_RADIUS_KM * Math.asin(Math.min(1, Math.sqrt(a)));
};

/** Center latitude of an ocean region. */
const regionCenterLat = (r: OceanRegion): number => (r.latMin + r.latMax) / 2;
/** Center longitude of an ocean region. */
const regionCenterLon = (r: OceanRegion): number => (r.lonMin + r.lonMax) / 2;

/**
 * Pick a random open-ocean launch point for a single submarine firing at the given target.
 *
 * Regions within a plausible SLBM range of the target are the candidates (falling back to
 * the single nearest region if the target is unusually remote); one is chosen at random
 * and a uniform random point inside it is returned. `rng` is injectable so tests are
 * deterministic. Used for one-off relocations; mass raids use {@link planSubmarineBoats}.
 */
export const randomOceanLaunchPoint = (targetLat: number, targetLon: number, rng: () => number = Math.random): { lat: number; lon: number } => {
  const distTo = (r: OceanRegion): number => greatCircleKm(regionCenterLat(r), regionCenterLon(r), targetLat, targetLon);
  let candidates = OCEAN_PATROL_REGIONS.filter((r) => distTo(r) <= MAX_SLBM_RANGE_KM);

  if (candidates.length === 0) {
    // Target unusually remote: fall back to the single nearest region.
    candidates = [[...OCEAN_PATROL_REGIONS].sort((a, b) => distTo(a) - distTo(b))[0]];
  }

  const region = candidates[Math.floor(rng() * candidates.length)];

  return {
    lat: region.latMin + rng() * (region.latMax - region.latMin),
    lon: region.lonMin + rng() * (region.lonMax - region.lonMin),
  };
};
