import { vi } from 'vitest';
// Generated by Qodo Gen

import { CatalogManager } from '@app/app/data/catalog-manager';
import { OrbitManager } from '@app/app/rendering/orbit-manager';
import { SatMath } from '@app/app/analysis/sat-math';
import { UiManager } from '@app/app/ui/ui-manager';
import { GetSatType, ToastMsgType } from '@app/engine/core/interfaces';
import { ServiceLocator } from '@app/engine/core/service-locator';
import { TimeManager } from '@app/engine/core/time-manager';
import { CreateSat } from '@app/plugins/create-sat/create-sat';
import { FormatTle, Sgp4 } from '@ootk/src/main';

describe('CreateSat', () => {

  // Creating a satellite with valid parameters should add it to the catalog
  it('should add a satellite to the catalog when valid parameters are provided', () => {
    // Mock dependencies
    const mockCatalogManager = {
      sccNum2Id: vi.fn().mockReturnValue(12345),
      getObject: vi.fn().mockReturnValue({
        isSatellite: () => true,
      }),
      objectCache: [],
      satCruncherThread: {
        sendSatEdit: vi.fn(),
      },
      seedDotPosition: vi.fn(),
    };

    const mockOrbitManager = {
      changeOrbitBufferData: vi.fn(),
    };

    const mockUiManager = {
      doSearch: vi.fn(),
      toast: vi.fn(),
    };

    const mockTimeManager = {
      simulationTimeObj: new Date(),
    };

    // Mock Sgp4 and FormatTle
    const mockSatrec = {};

    Sgp4.createSatrec = vi.fn().mockReturnValue(mockSatrec);
    Sgp4.propagate = vi.fn().mockReturnValue({
      position: { x: 1, y: 2, z: 3 },
      velocity: { x: 0.1, y: 0.2, z: 0.3 },
    });

    FormatTle.createTle = vi.fn().mockReturnValue({
      tle1: '1 39280U 13055R   15046.42575068  .30789804  00000-0  57707-2 0  9996',
      tle2: '2 39280 080.8897 122.4763 0060411 007.5143 351.4794 16.26612222 73510',
    });

    SatMath.altitudeCheck = vi.fn().mockReturnValue(500);

    // Mock DOM elements
    document.getElementById = vi.fn().mockImplementation((id) => {
      const element = document.createElement('input');

      element.id = id;
      element.value = '12345';

      return element;
    });

    // Mock keepTrackApi
    vi.spyOn(ServiceLocator, 'getCatalogManager').mockReturnValue(mockCatalogManager as unknown as CatalogManager);
    vi.spyOn(ServiceLocator, 'getOrbitManager').mockReturnValue(mockOrbitManager as unknown as OrbitManager);
    vi.spyOn(ServiceLocator, 'getUiManager').mockReturnValue(mockUiManager as unknown as UiManager);
    vi.spyOn(ServiceLocator, 'getTimeManager').mockReturnValue(mockTimeManager as unknown as TimeManager);

    // Mock the validation CreateSat[validateInputs_] method to always return false
    // eslint-disable-next-line dot-notation
    CreateSat['validateInputs_'] = vi.fn().mockReturnValue(false);

    // Call the method under test
    // eslint-disable-next-line dot-notation
    CreateSat['createSatSubmit_']();

    // Assertions
    // sccNum2Id now receives the raw form string (no parseInt) so alpha-5 and
    // extended IDs survive; the mock still resolves it to internal id 12345.
    expect(mockCatalogManager.sccNum2Id).toHaveBeenCalledWith('12345');
    expect(mockCatalogManager.getObject).toHaveBeenCalledWith(12345, GetSatType.EXTRA_ONLY);
    expect(FormatTle.createTle).toHaveBeenCalled();
    expect(Sgp4.createSatrec).toHaveBeenCalledWith(
      '1 39280U 13055R   15046.42575068  .30789804  00000-0  57707-2 0  9996',
      '2 39280 080.8897 122.4763 0060411 007.5143 351.4794 16.26612222 73510',
    );

    expect(SatMath.altitudeCheck).toHaveBeenCalledWith(mockSatrec, mockTimeManager.simulationTimeObj);
    expect(Sgp4.propagate).toHaveBeenCalledWith(mockSatrec, 0);
    expect(mockCatalogManager.satCruncherThread.sendSatEdit).toHaveBeenCalledWith(
      12345,
      '1 39280U 13055R   15046.42575068  .30789804  00000-0  57707-2 0  9996',
      '2 39280 080.8897 122.4763 0060411 007.5143 351.4794 16.26612222 73510',
      true,
    );
    expect(mockOrbitManager.changeOrbitBufferData).toHaveBeenCalledWith(12345,
      '1 39280U 13055R   15046.42575068  .30789804  00000-0  57707-2 0  9996',
      '2 39280 080.8897 122.4763 0060411 007.5143 351.4794 16.26612222 73510',
    );
    expect(mockUiManager.doSearch).toHaveBeenCalledWith('12345');
    expect(mockCatalogManager.objectCache[12345]).toBeDefined();
  });

  // Creating a satellite with parameters that result in sub-orbital trajectory should show error toast
  it('should show error toast when satellite parameters result in sub-orbital trajectory', () => {
    // Mock dependencies
    const mockCatalogManager = {
      sccNum2Id: vi.fn().mockReturnValue(12345),
      getObject: vi.fn().mockReturnValue({
        isSatellite: () => true,
      }),
      objectCache: [],
      satCruncherThread: {
        sendSatEdit: vi.fn(),
      },
      seedDotPosition: vi.fn(),
    };

    const mockOrbitManager = {
      changeOrbitBufferData: vi.fn(),
    };

    const mockUiManager = {
      toast: vi.fn(),
      doSearch: vi.fn(),
    };

    const mockTimeManager = {
      simulationTimeObj: new Date(),
    };

    // Mock Sgp4 and FormatTle
    const mockSatrec = {};

    Sgp4.createSatrec = vi.fn().mockReturnValue(mockSatrec);

    FormatTle.createTle = vi.fn().mockReturnValue({
      tle1: '1 39280U 13055R   15046.42575068  .30789804  00000-0  57707-2 0  9996',
      tle2: '2 39280 080.8897 122.4763 0060411 007.5143 351.4794 16.26612222 73510',
    });

    // Mock altitude check to return a value less than 1 (sub-orbital)
    SatMath.altitudeCheck = vi.fn().mockReturnValue(0.5);

    // Mock DOM elements
    document.getElementById = vi.fn().mockImplementation((id) => {
      const element = document.createElement('input');

      element.id = id;
      element.value = '12345';
      element.style = '';

      return element;
    });

    // Mock keepTrackApi
    vi.spyOn(ServiceLocator, 'getCatalogManager').mockReturnValue(mockCatalogManager as unknown as CatalogManager);
    vi.spyOn(ServiceLocator, 'getOrbitManager').mockReturnValue(mockOrbitManager as unknown as OrbitManager);
    vi.spyOn(ServiceLocator, 'getUiManager').mockReturnValue(mockUiManager as unknown as UiManager);
    vi.spyOn(ServiceLocator, 'getTimeManager').mockReturnValue(mockTimeManager as unknown as TimeManager);

    // Call the method under test
    // eslint-disable-next-line dot-notation
    CreateSat['createSatSubmit_']();

    // Assertions
    // sccNum2Id now receives the raw form string (no parseInt) so alpha-5 and
    // extended IDs survive; the mock still resolves it to internal id 12345.
    expect(mockCatalogManager.sccNum2Id).toHaveBeenCalledWith('12345');
    expect(mockCatalogManager.getObject).toHaveBeenCalledWith(12345, GetSatType.EXTRA_ONLY);
    expect(FormatTle.createTle).toHaveBeenCalled();
    expect(Sgp4.createSatrec).toHaveBeenCalledWith(
      '1 39280U 13055R   15046.42575068  .30789804  00000-0  57707-2 0  9996',
      '2 39280 080.8897 122.4763 0060411 007.5143 351.4794 16.26612222 73510',
    );
    expect(SatMath.altitudeCheck).toHaveBeenCalledWith(mockSatrec, mockTimeManager.simulationTimeObj);

    // Verify the toast was shown with the error message
    expect(mockUiManager.toast).toHaveBeenCalledWith(
      expect.any(String),
      ToastMsgType.caution,
      true,
    );

    // Verify that the satellite was not added to the catalog
    expect(mockCatalogManager.satCruncherThread.sendSatEdit).not.toHaveBeenCalled();
    expect(mockOrbitManager.changeOrbitBufferData).not.toHaveBeenCalled();
    expect(mockUiManager.doSearch).not.toHaveBeenCalled();
  });
});
