import { keepTrackApi } from '@app/js/api/keepTrackApi';
import { defaultSat, keepTrackApiStubs } from '../../api/apiMocks';
import { KeepTrackPrograms, SatObject } from '../../api/keepTrackTypes';
import * as satMath from '../satMath';

keepTrackApi.programs = <KeepTrackPrograms>(<unknown>{ ...keepTrackApi.programs, ...keepTrackApiStubs.programs });

// @ponicode
describe('satMath.distance', () => {
  test('0', () => {
    let result: any = satMath.distanceString(
      {
        ...defaultSat,
        ...(<SatObject>(<unknown>{
          position: { x: 1, y: 550, z: 350 },
          static: true,
          TLE1: 'Foo bar',
          TLE2: 'Hello, world!',
          sccNum: 'MT',
          active: false,
          C: 'rgb(0.1,0.2,0.3)',
          LS: 'B/.',
          LV: 'Spectacled Caiman',
          ON: '2021-07-29T17:54:41.653Z',
          OT: 1,
          R: 'TestUpperCase@Example.com',
          URL: 'https://api.telegram.org/bot',
          O: 'bed-free@tutanota.de',
          U: 'something@example.com',
          P: 'green',
          LM: 'Spectacled Caiman',
          DM: 'Nile Crocodile',
          Pw: '4.0.0-beta1\t',
          Li: 'fake',
          Con: 'fake',
          M: 'hsl(10%,20%,40%)',
          S1: 'user1+user2@mycompany.com',
          S2: 'something.example.com',
          S3: 'bed-free@tutanota.de',
          S4: 'user1+user2@mycompany.com',
          S5: 'bed-free@tutanota.de',
          S6: 'ponicode.com',
          S7: 'ponicode.com',
          inclination: 30,
          lon: 56784,
          perigee: 12345,
          apogee: 12,
          period: 56784,
          meanMotion: 1000,
          semimajorAxis: 4,
          eccentricity: -0.5,
          raan: 0,
          argPe: 987650,
          inView: -100,
          velocity: { total: 10000, x: 100, y: 70, z: 550 },
          getTEARR: '1.0.0',
          getAltitude: true,
          getDirection: false,
          vmag: 1,
          id: 0,
        })),
      },
      {
        ...defaultSat,
        ...(<SatObject>(<unknown>{
          position: { x: 4, y: 4, z: 30 },
          static: false,
          TLE1: 'This is a Text',
          TLE2: 'Foo bar',
          sccNum: 'MT',
          active: true,
          C: 'rgb(0.1,0.2,0.3)',
          LS: '₹',
          LV: 'Australian Freshwater Crocodile',
          ON: '2021-07-29T23:03:48.812Z',
          OT: 12345,
          R: 'ponicode.com',
          URL: 'ponicode.com',
          O: 'bed-free@tutanota.de',
          U: 'email@Google.com',
          P: 'black',
          LM: 'Dwarf Crocodile',
          DM: 'Dwarf Crocodile',
          Pw: '^5.0.0',
          Li: 'a',
          Con: 'fake',
          M: '#F00',
          S1: 'something@example.com',
          S2: 'something@example.com',
          S3: 'bed-free@tutanota.de',
          S4: 'TestUpperCase@Example.com',
          S5: 'TestUpperCase@Example.com',
          S6: 'ponicode.com',
          S7: 'bed-free@tutanota.de',
          inclination: 30,
          lon: 12345,
          perigee: 987650,
          apogee: 987650,
          period: 12,
          meanMotion: 1000,
          semimajorAxis: 64,
          eccentricity: -0.5,
          raan: 0,
          argPe: 12,
          inView: -5.48,
          velocity: { total: 10000, x: 550, y: 320, z: 400 },
          getTEARR: false,
          getAltitude: 350,
          getDirection: 'Southwest',
          vmag: 0,
          id: 0,
        })),
      }
    );
    expect(result).toMatchSnapshot();
  });

  test('1', () => {
    let result: any = satMath.distanceString(
      {
        ...defaultSat,
        ...(<SatObject>(<unknown>{
          position: { x: 350, y: 550, z: 1 },
          static: true,
          TLE1: 'Hello, world!',
          TLE2: 'Foo bar',
          sccNum: '₹',
          active: true,
          C: 'rgb(0.1,0.2,0.3)',
          LS: '£',
          LV: 'Australian Freshwater Crocodile',
          ON: '2021-07-30T00:05:36.818Z',
          OT: 12,
          R: 'something@example.com',
          URL: 'https://api.telegram.org/bot',
          O: 'ponicode.com',
          U: 'TestUpperCase@Example.com',
          P: '#F00',
          LM: 'Saltwater Crocodile',
          DM: 'Australian Freshwater Crocodile',
          Pw: 'v4.0.0-rc.4',
          Li: 'fake',
          Con: 'fake',
          M: '#FF00FF',
          S1: 'email@Google.com',
          S2: 'bed-free@tutanota.de',
          S3: 'TestUpperCase@Example.com',
          S4: 'something.example.com',
          S5: 'user@host:300',
          S6: 'email@Google.com',
          S7: 'ponicode.com',
          inclination: 5,
          lon: 12345,
          perigee: 12345,
          apogee: 987650,
          period: 56784,
          meanMotion: 5000.0,
          semimajorAxis: 2,
          eccentricity: -1.0,
          raan: 0,
          argPe: 100,
          inView: -100,
          velocity: { total: 300, x: 380, y: 400, z: 400 },
          getTEARR: '4.0.0-beta1\t',
          getAltitude: true,
          getDirection: false,
          vmag: 100,
          id: 0,
        })),
      },
      {
        ...defaultSat,
        ...(<SatObject>(<unknown>{
          position: { x: 50, y: 70, z: 320 },
          static: true,
          TLE1: 'Foo bar',
          TLE2: 'Hello, world!',
          sccNum: 'лв',
          active: true,
          C: 'red',
          LS: '£',
          LV: 'Dwarf Crocodile',
          ON: '2021-07-29T23:03:48.812Z',
          OT: 12,
          R: 'user@host:300',
          URL: 'https://api.telegram.org/',
          O: 'ponicode.com',
          U: 'ponicode.com',
          P: 'rgb(0.1,0.2,0.3)',
          LM: 'Australian Freshwater Crocodile',
          DM: 'Nile Crocodile',
          Pw: '4.0.0-beta1\t',
          Li: 'c',
          Con: '9876',
          M: 'green',
          S1: 'TestUpperCase@Example.com',
          S2: 'bed-free@tutanota.de',
          S3: 'something.example.com',
          S4: 'something.example.com',
          S5: 'user@host:300',
          S6: 'user1+user2@mycompany.com',
          S7: 'something.example.com',
          inclination: 30,
          lon: 987650,
          perigee: 56784,
          apogee: 12,
          period: 12345,
          meanMotion: 9999,
          semimajorAxis: 4,
          eccentricity: 0.0,
          raan: 56784,
          argPe: 12,
          inView: 1,
          velocity: { total: 10000, x: 70, y: 410, z: 520 },
          getTEARR: true,
          getAltitude: 30,
          getDirection: 'Southeast',
          vmag: -100,
          id: 0,
        })),
      }
    );
    expect(result).toMatchSnapshot();
  });
});
