import { defaultSat, defaultSensor, keepTrackApiStubs } from '@app/js/api/apiMocks';
import { keepTrackApi } from '@app/js/api/keepTrackApi';
import { KeepTrackPrograms } from '@app/js/api/keepTrackTypes';
import * as findBestPass from '@app/js/satMath/find/findBestPass';
import * as apiMocks from '../../../api/apiMocks';
import * as SpaceObjectType from '../../../api/SpaceObjectType';
import * as checkIsInView from '../../lookangles/checkIsInView';

keepTrackApi.programs = <KeepTrackPrograms>(<unknown>{ ...keepTrackApi.programs, ...keepTrackApiStubs.programs });

// @ponicode
describe('findBestPass.findBestPass', () => {
  test('0', () => {
    let param2: any = [
      {
        static: true,
        linkIridium: true,
        linkGalileo: false,
        linkStarlink: true,
        obsmaxel2: 1,
        obsmaxrange2: 30,
        obsminrange2: 350,
        obsminel2: 70,
        obsmaxaz2: -100,
        obsminaz2: 100,
        alt: 50,
        beamwidth: 24,
        changeObjectInterval: -5.48,
        country: 'US',
        lat: -90,
        linkAehf: true,
        linkWgs: false,
        lon: -45,
        name: 'George',
        observerGd: { lat: 45, lon: 180, alt: 1 },
        obsmaxaz: -100,
        obsmaxel: 100,
        obsmaxrange: 100,
        obsminaz: 1,
        obsminel: -1.0,
        obsminrange: 1,
        shortName: 'www.google.com',
        staticNum: 10,
        sun: '4.0.0-beta1\t',
        type: SpaceObjectType.SpaceObjectType.PAYLOAD_OWNER,
        url: 'https://twitter.com/path?abc',
        volume: true,
        zoom: "['39.2233', '-78.8613']",
      },
      {
        static: false,
        linkIridium: true,
        linkGalileo: false,
        linkStarlink: false,
        obsmaxel2: -5.48,
        obsmaxrange2: 70,
        obsminrange2: 4,
        obsminel2: 320,
        obsmaxaz2: -100,
        obsminaz2: 1,
        alt: 1,
        beamwidth: 480,
        changeObjectInterval: -5.48,
        country: 'US',
        lat: 45,
        linkAehf: false,
        linkWgs: true,
        lon: 45,
        name: 'Jean-Philippe',
        observerGd: { lat: -45, lon: 90, alt: 1 },
        obsmaxaz: -5.48,
        obsmaxel: 1,
        obsmaxrange: 70,
        obsminaz: 0,
        obsminel: -1.0,
        obsminrange: 100,
        shortName: 'http://www.croplands.org/account/confirm?t=',
        staticNum: 10,
        sun: 'v1.2.4',
        type: SpaceObjectType.SpaceObjectType.PAYLOAD_OWNER,
        url: 'ponicode.com',
        volume: false,
        zoom: "['41.1994', '-115.9206']",
      },
    ];
    let result: any = findBestPass.findBestPass(apiMocks.defaultSat, param2);
    expect(result).toMatchSnapshot();
  });

  test('1', () => {
    let param2: any = [
      {
        static: true,
        linkIridium: true,
        linkGalileo: true,
        linkStarlink: false,
        obsmaxel2: 100,
        obsmaxrange2: 1,
        obsminrange2: 30,
        obsminel2: 70,
        obsmaxaz2: -5.48,
        obsminaz2: 100,
        alt: 5,
        beamwidth: 30,
        changeObjectInterval: -5.48,
        country: 'United States',
        lat: 45,
        linkAehf: true,
        linkWgs: true,
        lon: 180,
        name: 'Jean-Philippe',
        observerGd: { lat: 0, lon: 0, alt: 1 },
        obsmaxaz: 1,
        obsmaxel: -5.48,
        obsmaxrange: 4,
        obsminaz: 100,
        obsminel: 1.0,
        obsminrange: 1,
        shortName: 'http://base.com',
        staticNum: 1,
        sun: '4.0.0-beta1\t',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'Www.GooGle.com',
        volume: false,
        zoom: "['61.0865', '-144.7750']",
      },
      {
        static: true,
        linkIridium: false,
        linkGalileo: true,
        linkStarlink: false,
        obsmaxel2: 0,
        obsmaxrange2: 550,
        obsminrange2: 30,
        obsminel2: 50,
        obsmaxaz2: 1,
        obsminaz2: -100,
        alt: 5,
        beamwidth: 255,
        changeObjectInterval: 100,
        country: 'China',
        lat: 0,
        linkAehf: true,
        linkWgs: false,
        lon: 90,
        name: 'Michael',
        observerGd: { lat: -180, lon: 180, alt: 50 },
        obsmaxaz: 0,
        obsmaxel: -5.48,
        obsmaxrange: 70,
        obsminaz: 100,
        obsminel: 10.23,
        obsminrange: 1,
        shortName: 'https://api.telegram.org/',
        staticNum: 1000,
        sun: 'v1.2.4',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'https://twitter.com/path?abc',
        volume: true,
        zoom: "['-19.3366', '-46.1477']",
      },
      {
        static: true,
        linkIridium: false,
        linkGalileo: true,
        linkStarlink: false,
        obsmaxel2: 1,
        obsmaxrange2: 520,
        obsminrange2: 100,
        obsminel2: 400,
        obsmaxaz2: -100,
        obsminaz2: -100,
        alt: 5,
        beamwidth: 544,
        changeObjectInterval: 100,
        country: 'France',
        lat: -45,
        linkAehf: false,
        linkWgs: false,
        lon: -180,
        name: 'Pierre Edouard',
        observerGd: { lat: 0, lon: -45, alt: 3 },
        obsmaxaz: 0,
        obsmaxel: 0,
        obsmaxrange: 100,
        obsminaz: -100,
        obsminel: -1.0,
        obsminrange: -100,
        shortName: 'https://twitter.com/path?abc',
        staticNum: 1000,
        sun: '1.0.0',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'www.google.com',
        volume: true,
        zoom: "['41.1994', '-115.9206']",
      },
      {
        static: false,
        linkIridium: false,
        linkGalileo: false,
        linkStarlink: false,
        obsmaxel2: -5.48,
        obsmaxrange2: 320,
        obsminrange2: 50,
        obsminel2: 100,
        obsmaxaz2: 100,
        obsminaz2: 1,
        alt: 3,
        beamwidth: 390,
        changeObjectInterval: 1,
        country: 'GB',
        lat: -90,
        linkAehf: true,
        linkWgs: false,
        lon: -180,
        name: 'Michael',
        observerGd: { lat: 45, lon: 180, alt: 1 },
        obsmaxaz: 1,
        obsmaxel: 100,
        obsmaxrange: 30,
        obsminaz: -100,
        obsminel: 0.0,
        obsminrange: -100,
        shortName: 'Www.GooGle.com',
        staticNum: 10,
        sun: '4.0.0-beta1\t',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'ponicode.com',
        volume: true,
        zoom: "['-19.3366', '-46.1477']",
      },
      {
        static: false,
        linkIridium: false,
        linkGalileo: false,
        linkStarlink: false,
        obsmaxel2: 0,
        obsmaxrange2: 30,
        obsminrange2: 410,
        obsminel2: 70,
        obsmaxaz2: 100,
        obsminaz2: 100,
        alt: 3,
        beamwidth: 544,
        changeObjectInterval: -5.48,
        country: 'GB',
        lat: 180,
        linkAehf: false,
        linkWgs: true,
        lon: -90,
        name: 'George',
        observerGd: { lat: 90, lon: 0, alt: 1 },
        obsmaxaz: 1,
        obsmaxel: 0,
        obsmaxrange: 380,
        obsminaz: 100,
        obsminel: -29.45,
        obsminrange: -100,
        shortName: 'http://www.croplands.org/account/confirm?t=',
        staticNum: 1000,
        sun: 'v4.0.0-rc.4',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'Www.GooGle.com',
        volume: true,
        zoom: "['-19.3366', '-46.1477']",
      },
    ];
    let result: any = findBestPass.findBestPass(apiMocks.defaultSat, param2);
    expect(result).toMatchSnapshot();
  });

  test('2', () => {
    let param2: any = [
      {
        static: false,
        linkIridium: false,
        linkGalileo: false,
        linkStarlink: true,
        obsmaxel2: -5.48,
        obsmaxrange2: 50,
        obsminrange2: 400,
        obsminel2: 520,
        obsmaxaz2: 1,
        obsminaz2: -100,
        alt: 50,
        beamwidth: 16,
        changeObjectInterval: 1,
        country: 'FR',
        lat: -180,
        linkAehf: true,
        linkWgs: false,
        lon: 45,
        name: 'Michael',
        observerGd: { lat: -45, lon: -45, alt: 3 },
        obsmaxaz: -5.48,
        obsmaxel: -100,
        obsmaxrange: 70,
        obsminaz: -100,
        obsminel: -29.45,
        obsminrange: -5.48,
        shortName: 'https://',
        staticNum: 1,
        sun: '^5.0.0',
        type: SpaceObjectType.SpaceObjectType.RADAR_MEASUREMENT,
        url: 'ponicode.com',
        volume: true,
        zoom: "['-84.8577', '134.8560']",
      },
      {
        static: false,
        linkIridium: false,
        linkGalileo: false,
        linkStarlink: true,
        obsmaxel2: 0,
        obsmaxrange2: 520,
        obsminrange2: 550,
        obsminel2: 350,
        obsmaxaz2: -100,
        obsminaz2: 100,
        alt: 5,
        beamwidth: 25,
        changeObjectInterval: 100,
        country: 'United States',
        lat: -180,
        linkAehf: true,
        linkWgs: true,
        lon: -90,
        name: 'Anas',
        observerGd: { lat: -90, lon: 0, alt: 1 },
        obsmaxaz: -100,
        obsmaxel: 1,
        obsmaxrange: 380,
        obsminaz: -100,
        obsminel: 0.0,
        obsminrange: 0,
        shortName: 'http://example.com/showcalendar.html?token=CKF50YzIHxCTKMAg',
        staticNum: 1000,
        sun: '^5.0.0',
        type: SpaceObjectType.SpaceObjectType.RADAR_MEASUREMENT,
        url: 'https://',
        volume: true,
        zoom: "['39.2233', '-78.8613']",
      },
    ];
    let result: any = findBestPass.findBestPass(apiMocks.defaultSat, param2);
    expect(result).toMatchSnapshot();
  });

  test('3', () => {
    let param2: any = [
      {
        static: false,
        linkIridium: true,
        linkGalileo: true,
        linkStarlink: true,
        obsmaxel2: -100,
        obsmaxrange2: 400,
        obsminrange2: 90,
        obsminel2: 4,
        obsmaxaz2: 0,
        obsminaz2: 100,
        alt: 3,
        beamwidth: 80.0,
        changeObjectInterval: -5.48,
        country: 'United States',
        lat: 0,
        linkAehf: true,
        linkWgs: false,
        lon: -180,
        name: 'Anas',
        observerGd: { lat: 45, lon: 180, alt: 3 },
        obsmaxaz: 0,
        obsmaxel: 1,
        obsmaxrange: 90,
        obsminaz: -100,
        obsminel: -29.45,
        obsminrange: -100,
        shortName: 'http://example.com/showcalendar.html?token=CKF50YzIHxCTKMAg',
        staticNum: 1000,
        sun: '4.0.0-beta1\t',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'http://base.com',
        volume: false,
        zoom: "['39.2233', '-78.8613']",
      },
      {
        static: false,
        linkIridium: true,
        linkGalileo: false,
        linkStarlink: false,
        obsmaxel2: 0,
        obsmaxrange2: 90,
        obsminrange2: 400,
        obsminel2: 4,
        obsmaxaz2: 100,
        obsminaz2: 1,
        alt: 50,
        beamwidth: 24000,
        changeObjectInterval: 0,
        country: 'United States',
        lat: 0,
        linkAehf: false,
        linkWgs: true,
        lon: 45,
        name: 'Jean-Philippe',
        observerGd: { lat: -180, lon: -180, alt: 50 },
        obsmaxaz: -5.48,
        obsmaxel: -5.48,
        obsmaxrange: 400,
        obsminaz: -5.48,
        obsminel: -0.5,
        obsminrange: -5.48,
        shortName: 'http://example.com/showcalendar.html?token=CKF50YzIHxCTKMAg',
        staticNum: 1,
        sun: '4.0.0-beta1\t',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'Www.GooGle.com',
        volume: false,
        zoom: "['41.1994', '-115.9206']",
      },
      {
        static: false,
        linkIridium: true,
        linkGalileo: true,
        linkStarlink: true,
        obsmaxel2: 1,
        obsmaxrange2: 50,
        obsminrange2: 550,
        obsminel2: 410,
        obsmaxaz2: 1,
        obsminaz2: 100,
        alt: 5,
        beamwidth: 2048,
        changeObjectInterval: 100,
        country: 'France',
        lat: 45,
        linkAehf: false,
        linkWgs: false,
        lon: -180,
        name: 'Edmond',
        observerGd: { lat: -90, lon: 0, alt: 3 },
        obsmaxaz: -100,
        obsmaxel: -5.48,
        obsmaxrange: 100,
        obsminaz: -5.48,
        obsminel: 0.5,
        obsminrange: 100,
        shortName: 'Www.GooGle.com',
        staticNum: 10,
        sun: '1.0.0',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'Www.GooGle.com',
        volume: true,
        zoom: "['39.2233', '-78.8613']",
      },
      {
        static: false,
        linkIridium: false,
        linkGalileo: false,
        linkStarlink: false,
        obsmaxel2: -100,
        obsmaxrange2: 70,
        obsminrange2: 100,
        obsminel2: 70,
        obsmaxaz2: -5.48,
        obsminaz2: 1,
        alt: 5,
        beamwidth: 0,
        changeObjectInterval: 100,
        country: 'United States',
        lat: 90,
        linkAehf: true,
        linkWgs: false,
        lon: -45,
        name: 'Edmond',
        observerGd: { lat: 90, lon: -90, alt: 50 },
        obsmaxaz: -5.48,
        obsmaxel: 0,
        obsmaxrange: 350,
        obsminaz: 0,
        obsminel: 1.0,
        obsminrange: -5.48,
        shortName: 'http://example.com/showcalendar.html?token=CKF50YzIHxCTKMAg',
        staticNum: 10,
        sun: 'v4.0.0-rc.4',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'www.google.com',
        volume: false,
        zoom: "['-84.8577', '134.8560']",
      },
      {
        static: true,
        linkIridium: true,
        linkGalileo: true,
        linkStarlink: true,
        obsmaxel2: 0,
        obsmaxrange2: 380,
        obsminrange2: 100,
        obsminel2: 520,
        obsmaxaz2: 0,
        obsminaz2: 1,
        alt: 5,
        beamwidth: 200,
        changeObjectInterval: 100,
        country: 'FR',
        lat: 180,
        linkAehf: false,
        linkWgs: false,
        lon: 0,
        name: 'Jean-Philippe',
        observerGd: { lat: 0, lon: -180, alt: 3 },
        obsmaxaz: 0,
        obsmaxel: -100,
        obsmaxrange: 400,
        obsminaz: 1,
        obsminel: 1.0,
        obsminrange: 0,
        shortName: 'https://twitter.com/path?abc',
        staticNum: 1000,
        sun: 'v1.2.4',
        type: SpaceObjectType.SpaceObjectType.ROCKET_BODY,
        url: 'www.google.com',
        volume: true,
        zoom: "['-19.3366', '-46.1477']",
      },
    ];
    let result: any = findBestPass.findBestPass(apiMocks.defaultSat, param2);
    expect(result).toMatchSnapshot();
  });

  test('4', () => {
    let param2: any = [
      {
        static: true,
        linkIridium: true,
        linkGalileo: false,
        linkStarlink: false,
        obsmaxel2: 1,
        obsmaxrange2: 50,
        obsminrange2: 100,
        obsminel2: 400,
        obsmaxaz2: -100,
        obsminaz2: 100,
        alt: 50,
        beamwidth: 200,
        changeObjectInterval: 0,
        country: 'China',
        lat: 90,
        linkAehf: true,
        linkWgs: true,
        lon: 45,
        name: 'Edmond',
        observerGd: { lat: -180, lon: -180, alt: 3 },
        obsmaxaz: 100,
        obsmaxel: 100,
        obsmaxrange: 550,
        obsminaz: -100,
        obsminel: 0.5,
        obsminrange: 100,
        shortName: 'https://accounts.google.com/o/oauth2/revoke?token=%s',
        staticNum: 1000,
        sun: '1.0.0',
        type: SpaceObjectType.SpaceObjectType.LAUNCH_SITE,
        url: 'https://',
        volume: true,
        zoom: "['39.2233', '-78.8613']",
      },
      {
        static: false,
        linkIridium: false,
        linkGalileo: true,
        linkStarlink: false,
        obsmaxel2: 100,
        obsmaxrange2: 4,
        obsminrange2: 380,
        obsminel2: 50,
        obsmaxaz2: -5.48,
        obsminaz2: 100,
        alt: 50,
        beamwidth: 24,
        changeObjectInterval: 100,
        country: 'France',
        lat: -90,
        linkAehf: false,
        linkWgs: true,
        lon: -90,
        name: 'Michael',
        observerGd: { lat: -180, lon: 90, alt: 1 },
        obsmaxaz: 0,
        obsmaxel: 0,
        obsmaxrange: 320,
        obsminaz: -100,
        obsminel: 1.0,
        obsminrange: 1,
        shortName: 'https://api.telegram.org/',
        staticNum: 1,
        sun: '4.0.0-beta1\t',
        type: SpaceObjectType.SpaceObjectType.LAUNCH_SITE,
        url: 'ponicode.com',
        volume: true,
        zoom: "['-19.3366', '-46.1477']",
      },
      {
        static: true,
        linkIridium: true,
        linkGalileo: true,
        linkStarlink: true,
        obsmaxel2: 100,
        obsmaxrange2: 350,
        obsminrange2: 30,
        obsminel2: 100,
        obsmaxaz2: 1,
        obsminaz2: 1,
        alt: 1,
        beamwidth: 2048,
        changeObjectInterval: 100,
        country: 'France',
        lat: 45,
        linkAehf: false,
        linkWgs: true,
        lon: 90,
        name: 'George',
        observerGd: { lat: -180, lon: -90, alt: 1 },
        obsmaxaz: 0,
        obsmaxel: 0,
        obsmaxrange: 1,
        obsminaz: 1,
        obsminel: 0.5,
        obsminrange: 0,
        shortName: 'https://accounts.google.com/o/oauth2/revoke?token=%s',
        staticNum: 1000,
        sun: '^5.0.0',
        type: SpaceObjectType.SpaceObjectType.LAUNCH_SITE,
        url: 'https://twitter.com/path?abc',
        volume: false,
        zoom: "['-84.8577', '134.8560']",
      },
      {
        static: false,
        linkIridium: true,
        linkGalileo: true,
        linkStarlink: false,
        obsmaxel2: -100,
        obsmaxrange2: 1,
        obsminrange2: 4,
        obsminel2: 4,
        obsmaxaz2: -100,
        obsminaz2: 1,
        alt: 3,
        beamwidth: 9,
        changeObjectInterval: -5.48,
        country: 'US',
        lat: 180,
        linkAehf: true,
        linkWgs: false,
        lon: -180,
        name: 'Anas',
        observerGd: { lat: 180, lon: -180, alt: 3 },
        obsmaxaz: -100,
        obsmaxel: -5.48,
        obsmaxrange: 520,
        obsminaz: -100,
        obsminel: 10.23,
        obsminrange: 0,
        shortName: 'https://accounts.google.com/o/oauth2/revoke?token=%s',
        staticNum: 1,
        sun: '4.0.0-beta1\t',
        type: SpaceObjectType.SpaceObjectType.LAUNCH_SITE,
        url: 'http://base.com',
        volume: true,
        zoom: "['-19.3366', '-46.1477']",
      },
      {
        static: false,
        linkIridium: false,
        linkGalileo: false,
        linkStarlink: true,
        obsmaxel2: 0,
        obsmaxrange2: 70,
        obsminrange2: 520,
        obsminel2: 520,
        obsmaxaz2: 0,
        obsminaz2: 1,
        alt: 3,
        beamwidth: 12,
        changeObjectInterval: -5.48,
        country: 'US',
        lat: 0,
        linkAehf: true,
        linkWgs: false,
        lon: -180,
        name: 'George',
        observerGd: { lat: 180, lon: 180, alt: 5 },
        obsmaxaz: 1,
        obsmaxel: 0,
        obsmaxrange: 30,
        obsminaz: -100,
        obsminel: -1.0,
        obsminrange: -100,
        shortName: 'www.google.com',
        staticNum: 1000,
        sun: 'v1.2.4',
        type: SpaceObjectType.SpaceObjectType.LAUNCH_SITE,
        url: 'https://',
        volume: false,
        zoom: "['61.0865', '-144.7750']",
      },
    ];
    let result: any = findBestPass.findBestPass(apiMocks.defaultSat, param2);
    expect(result).toMatchSnapshot();
  });

  it('should handle a varierty of results 1', () => {
    const result = () => findBestPass.findBestPass(defaultSat, []);
    expect(result).not.toThrow();
  });

  it('should handle a varierty of results 8', () => {
    jest
      .spyOn(checkIsInView, 'checkIsInView')
      .mockImplementationOnce(() => true)
      .mockImplementationOnce(() => false)
      .mockImplementationOnce(() => true)
      .mockImplementationOnce(() => true);
    const result = () => findBestPass.findBestPass(defaultSat, [defaultSensor]);
    expect(result).not.toThrow();
  });
});
