
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/**
 * The current application version
 * Generated on: 2025-05-02T22:43:53.537Z
 */
export const VERSION = '10.5.2';

/**
 * Build timestamp
 */
export const BUILD_TIMESTAMP = 1746225833537;

/**
 * Build date
 */
export const BUILD_DATE = '2025-05-02T22:43:53.537Z';
