import { SensorObject } from '@app/js/interfaces';
import { SpaceObjectType } from '@app/js/lib/space-object-type';
import { Degrees, Kilometers, Milliseconds } from 'ootk';

export interface SensorList {
  [key: string]: SensorObject;
}

const sensors_: SensorList = {
  COD: {
    id: 0,
    name: 'Cape Cod SFS, Massachusetts',
    shortName: 'COD',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>41.754785,
    lon: <Degrees>-70.539151,
    alt: <Kilometers>0.060966,
    obsminaz: <Degrees>347,
    obsmaxaz: <Degrees>227,
    obsminel: <Degrees>3,
    obsmaxel: <Degrees>85,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>5556,
    changeObjectInterval: <Milliseconds>1000,
    beamwidth: <Degrees>2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
    linkAehf: true,
    linkWgs: true,
    zoom: 'leo',
    url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte004.en.html',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  BLE: {
    id: 0,
    name: 'Beale AFB, California',
    shortName: 'BLE',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>39.136064,
    lon: <Degrees>-121.351237,
    alt: <Kilometers>0.112, // Open Street Maps
    obsminaz: <Degrees>126,
    obsmaxaz: <Degrees>6,
    obsminel: <Degrees>3,
    obsmaxel: <Degrees>85,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>5556,
    changeObjectInterval: <Milliseconds>1000,
    beamwidth: <Degrees>2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
    linkAehf: true,
    linkWgs: true,
    zoom: 'leo',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  CLR: {
    id: 0,
    name: 'Clear SFS, Alaska',
    shortName: 'CLR',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>64.290556,
    lon: <Degrees>-149.186944,
    alt: <Kilometers>0.175, // Open Street Maps
    obsminaz: <Degrees>184,
    obsmaxaz: <Degrees>64,
    obsminel: <Degrees>3,
    obsmaxel: <Degrees>85,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>5556,
    changeObjectInterval: <Milliseconds>1000,
    beamwidth: <Degrees>2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
    linkAehf: true,
    linkWgs: true,
    zoom: 'leo',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  EGL: {
    id: 0,
    name: 'Eglin AFB, Florida',
    shortName: 'EGL',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>30.572411,
    lon: <Degrees>-86.214836,
    alt: <Kilometers>0.039, // Open Street Maps
    obsminaz: <Degrees>120,
    obsmaxaz: <Degrees>240,
    obsminel: <Degrees>3,
    obsmaxel: <Degrees>105,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>200000,
    changeObjectInterval: <Milliseconds>1000,
    zoom: 'geo',
    beamwidth: <Degrees>1.4, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
    url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte002.en.html',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  FYL: {
    id: 0,
    name: 'RAF Fylingdales, United Kingdom',
    shortName: 'FYL',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>54.361758,
    lon: <Degrees>-0.670051,
    alt: <Kilometers>0.26, // Open Street Maps
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>3,
    obsmaxel: <Degrees>85,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>5556,
    changeObjectInterval: <Milliseconds>1000,
    beamwidth: <Degrees>2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
    linkAehf: true,
    linkWgs: true,
    zoom: 'leo',
    country: 'United Kingdom',
    sun: 'No Impact',
    volume: false,
  },
  CAV: {
    id: 0,
    name: 'Cavalier SFS, North Dakota',
    shortName: 'CAV',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>48.724567,
    lon: <Degrees>-97.899755,
    alt: <Kilometers>0.352, // Open Street Maps
    obsminaz: <Degrees>298,
    obsmaxaz: <Degrees>78,
    obsminel: <Degrees>1.9,
    obsmaxel: <Degrees>95,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>3300, // 1,780 Nm http://www.fortwiki.com/Cavalier_Air_Force_Station
    changeObjectInterval: <Milliseconds>1000,
    beamwidth: <Degrees>1.2, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
    linkAehf: true,
    zoom: 'leo',
    url: 'https://mostlymissiledefense.com/2012/04/12/parcs-cavalier-radar-april-12-2012/',
    country: 'United States',
    sun: 'No Impact',
    volume: true,
  },
  THL: {
    id: 0,
    name: 'Thule AFB, Greenland',
    shortName: 'THL',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>76.570322,
    lon: <Degrees>-68.299211,
    alt: <Kilometers>0.392, // Open Street Maps
    obsminaz: <Degrees>297,
    obsmaxaz: <Degrees>177,
    obsminel: <Degrees>3,
    obsmaxel: <Degrees>85,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>5556,
    changeObjectInterval: <Milliseconds>1000,
    beamwidth: <Degrees>2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
    linkAehf: true,
    linkWgs: true,
    zoom: 'leo',
    url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte004.en.html',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  CDN: {
    id: 0,
    name: 'Cobra Dane, Alaska',
    shortName: 'CDN',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>52.737,
    lon: <Degrees>174.092,
    alt: <Kilometers>0.066, // Open Street Maps
    obsminaz: <Degrees>251, // TODO: Need to find an open-source reference
    obsmaxaz: <Degrees>27,
    obsminel: <Degrees>2,
    obsmaxel: <Degrees>80,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>4200,
    // obsminaz2: <Degrees>251,
    // obsmaxaz2: <Degrees>27,
    // obsminel2: <Degrees>30,
    // obsmaxel2: <Degrees>80,
    // obsminrange2: <Kilometers>200,
    // obsmaxrange2: <Kilometers>4200,
    changeObjectInterval: <Milliseconds>1000,
    linkWgs: true,
    zoom: 'leo',
    url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte004.en.html',
    country: 'United States',
    sun: 'No Impact',
    volume: true,
  },
  ALT: {
    id: 0,
    name: 'ALTAIR, Kwajalein Atoll',
    shortName: 'ALT',
    type: SpaceObjectType.MECHANICAL,
    lat: <Degrees>8.716667,
    lon: <Degrees>167.733333,
    alt: <Kilometers>0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>1,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>200000,
    changeObjectInterval: <Milliseconds>20000,
    linkAehf: true,
    linkWgs: true,
    zoom: 'geo',
    url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte005.en.html',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  MMW: {
    id: 0,
    name: 'Millimeter Wave Radar, Kwajalein Atoll',
    shortName: 'MMW',
    type: SpaceObjectType.MECHANICAL,
    lat: <Degrees>8.756668,
    lon: <Degrees>167.773334,
    alt: <Kilometers>0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>1,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>2500,
    changeObjectInterval: <Milliseconds>20000,
    linkAehf: false,
    linkWgs: false,
    zoom: 'leo',
    url: '',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  ALC: {
    id: 0,
    name: 'ALCOR Radar, Kwajalein Atoll',
    shortName: 'ALC',
    type: SpaceObjectType.MECHANICAL,
    lat: <Degrees>8.716668,
    lon: <Degrees>167.773334,
    alt: <Kilometers>0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>1,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>2300,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>20000,
    linkAehf: false,
    linkWgs: false,
    url: '',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  TDX: {
    id: 0,
    name: 'TRADEX Radar, Kwajalein Atoll',
    shortName: 'TDX',
    type: SpaceObjectType.MECHANICAL,
    lat: <Degrees>8.756668,
    lon: <Degrees>167.733334,
    alt: <Kilometers>0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>1,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    linkAehf: false,
    linkWgs: false,
    url: '',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  MIL: {
    id: 0,
    name: 'Millstone, Massachusetts',
    shortName: 'MIL',
    type: SpaceObjectType.MECHANICAL,
    lat: <Degrees>42.6233,
    lon: <Degrees>-71.4882,
    alt: <Kilometers>0.131,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>1,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: 'https://mostlymissiledefense.com/2012/05/05/space-surveillance-sensors-millstone-hill-radar/',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  DGC: {
    id: 0,
    name: 'Diego Garcia',
    shortName: 'DGC',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>-7.29648,
    lon: <Degrees>72.390153,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>20,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: 'https://mostlymissiledefense.com/2012/08/20/space-surveillance-sensors-geodss-ground-based-electro-optical-deep-space-surveillance-system-august-20-2012/',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  MAU: {
    id: 0,
    name: 'Maui, Hawaii',
    shortName: 'MAU',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>20.70835,
    lon: <Degrees>-156.257595,
    alt: <Kilometers>3.0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>20,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: 'https://mostlymissiledefense.com/2012/08/20/space-surveillance-sensors-geodss-ground-based-electro-optical-deep-space-surveillance-system-august-20-2012/',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  SOC: {
    id: 0,
    name: 'Socorro, New Mexico',
    shortName: 'SOC',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>33.817233,
    lon: <Degrees>-106.659961,
    alt: <Kilometers>1.24,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>20,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: 'https://mostlymissiledefense.com/2012/08/20/space-surveillance-sensors-geodss-ground-based-electro-optical-deep-space-surveillance-system-august-20-2012/',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  ASC: {
    id: 0,
    name: 'Ascension Island, United Kingdom',
    shortName: 'ASC',
    type: SpaceObjectType.MECHANICAL,
    lat: <Degrees>-7.969444,
    lon: <Degrees>-14.393889,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>1,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: '',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  GLB: {
    id: 0,
    name: 'Globus II, NOR',
    shortName: 'GLB',
    type: SpaceObjectType.MECHANICAL,
    lat: <Degrees>70.3671,
    lon: <Degrees>31.1271,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>1,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: '',
    country: 'Norway',
    sun: 'No Impact',
    volume: false,
  },
  HOL: {
    id: 0,
    name: 'C-Band (Holt) Radar, Australia',
    shortName: 'HOL',
    type: SpaceObjectType.MECHANICAL,
    lat: <Degrees>-21.816195,
    lon: <Degrees>114.165637,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>1,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: '',
    country: 'Australia',
    sun: 'No Impact',
    volume: false,
  },

  // //////////////
  // TPY-2 RADARS
  // //////////////

  HAR: {
    id: 0,
    name: 'Har Keren TPY-2, Israel',
    shortName: 'HAR',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>30.995807,
    lon: <Degrees>34.496062,
    alt: <Kilometers>0.173,
    obsminaz: <Degrees>5,
    obsmaxaz: <Degrees>125,
    obsminel: <Degrees>5,
    obsmaxel: <Degrees>95,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>2000,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: '',
    country: 'Israel',
    sun: 'No Impact',
    volume: false,
  },
  QTR: {
    id: 0,
    name: 'Centcom TPY-2, Qatar',
    shortName: 'QTR',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>25.31598,
    lon: <Degrees>51.146515,
    alt: <Kilometers>0.01,
    obsminaz: <Degrees>335,
    obsmaxaz: <Degrees>95,
    obsminel: <Degrees>0,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>2000,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: '',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },
  KUR: {
    id: 0,
    name: 'Kürecik Radar Station, Turkey',
    shortName: 'KUR',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>38.349444,
    lon: <Degrees>37.793611,
    alt: <Kilometers>1.969,
    obsminaz: <Degrees>40,
    obsmaxaz: <Degrees>160,
    obsminel: <Degrees>0,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>2000,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: '',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },

  SHA: {
    id: 0,
    name: 'Shariki Communication Site, Japan',
    shortName: 'SHA',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>40.88809,
    lon: <Degrees>140.337698,
    alt: <Kilometers>0.01,
    obsminaz: <Degrees>230,
    obsmaxaz: <Degrees>350,
    obsminel: <Degrees>0,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>2000,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: '',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },

  KCS: {
    id: 0,
    name: 'Kyogamisaki Communication Site, Japan',
    shortName: 'KCS',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>35.766667,
    lon: <Degrees>135.195278,
    alt: <Kilometers>0.01,
    obsminaz: <Degrees>210,
    obsmaxaz: <Degrees>330,
    obsminel: <Degrees>0,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>2000,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: '',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },

  SBX: {
    id: 0,
    name: 'Sea-Based X-Band Radar, Pacific Ocean',
    shortName: 'SBX',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>36.5012,
    lon: <Degrees>169.6941,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>275,
    obsmaxaz: <Degrees>300,
    obsminel: <Degrees>0,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>4025,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: '',
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },

  // //////////////////////
  // LEO LABS
  // //////////////////////

  MSR: {
    id: 0,
    name: 'Midland Space Radar, Texas',
    shortName: 'MSR',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>31.9643,
    lon: <Degrees>-103.233245,
    alt: <Kilometers>0.855,
    obsminaz: <Degrees>70,
    obsmaxaz: <Degrees>72,
    obsminel: <Degrees>30,
    obsmaxel: <Degrees>91, // 91 to ensure visual overlap
    obsminrange: <Kilometers>100,
    obsmaxrange: <Kilometers>1800,
    obsminaz2: <Degrees>250,
    obsmaxaz2: <Degrees>252,
    obsminel2: <Degrees>30,
    obsmaxel2: <Degrees>91, // 91 to ensure visual overlap
    obsminrange2: <Kilometers>100,
    obsmaxrange2: <Kilometers>1800,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: 'https://platform.leolabs.space/sites/msr',
    country: 'United States',
    sun: 'No Impact',
    volume: true,
  },

  PFISR: {
    id: 0,
    name: 'Poker Flat Incoherent Scatter Radar, Alaska',
    shortName: 'PFISR',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>65.130029,
    lon: <Degrees>-147.470992,
    alt: <Kilometers>0.23,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>45,
    obsmaxel: <Degrees>90, // 91 to ensure visual overlap
    obsminrange: <Kilometers>100,
    obsmaxrange: <Kilometers>1800,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: 'https://platform.leolabs.space/sites/pfisr',
    country: 'United States',
    sun: 'No Impact',
    volume: true,
  },

  KSR: {
    id: 0,
    name: 'Kiwi Space Radar, New Zealand',
    shortName: 'KSR',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>-45.038725,
    lon: <Degrees>170.095673,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>269,
    obsmaxaz: <Degrees>271,
    obsminel: <Degrees>20,
    obsmaxel: <Degrees>91,
    obsminrange: <Kilometers>100,
    obsmaxrange: <Kilometers>1800,
    obsminaz2: <Degrees>89,
    obsmaxaz2: <Degrees>91,
    obsminel2: <Degrees>20,
    obsmaxel2: <Degrees>91,
    obsminrange2: <Kilometers>100,
    obsmaxrange2: <Kilometers>1800,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: 'https://platform.leolabs.space/sites/ksr',
    country: 'United States',
    sun: 'No Impact',
    volume: true,
  },

  CRSR: {
    id: 0,
    name: 'Costa Rica Space Radar, Costa Rica',
    shortName: 'CRSR',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>10.611782670733335, // https://www.radartutorial.eu/19.kartei/02.surv/karte087.en.html
    lon: <Degrees>-85.52869380341954,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>209,
    obsmaxaz: <Degrees>211,
    obsminel: <Degrees>20,
    obsmaxel: <Degrees>180, // NOTE: Not sure why this looks correct, but 200 goes into the earth
    obsminrange: <Kilometers>100,
    obsmaxrange: <Kilometers>3000,
    obsminaz2: <Degrees>119,
    obsmaxaz2: <Degrees>121,
    obsminel2: <Degrees>20,
    obsmaxel2: <Degrees>180, // NOTE: Not sure why this looks correct, but 200 goes into the earth
    obsminrange2: <Kilometers>100,
    obsmaxrange2: <Kilometers>3000,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    url: 'https://platform.leolabs.space/sites/crsr',
    country: 'United States',
    sun: 'No Impact',
    volume: true,
  },

  // //////////////////////
  // ESOC RADARS
  // //////////////////////
  GRV: {
    id: 0,
    name: 'Grand Réseau Adapté à la Veille Spatiale, France',
    shortName: 'GRV',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>47.347778,
    lon: <Degrees>5.51638,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>90,
    obsmaxaz: <Degrees>270,
    obsminel: <Degrees>20,
    obsmaxel: <Degrees>40,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>1700, // http://emits.sso.esa.int/emits-doc/AO5059RD1.pdf
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>20000,
    url: '',
    country: 'France',
    sun: 'No Impact',
    volume: true,
  },
  TIR: {
    id: 0,
    name: 'Tracking and Imaging Radar, Germany',
    shortName: 'TIR',
    type: SpaceObjectType.MECHANICAL,
    lat: <Degrees>50.6166,
    lon: <Degrees>7.1296,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>1.5, // http://www.issfd.org/ISSFD_2012/ISSFD23_CRSD2_3.pdf
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000, // http://emits.sso.esa.int/emits-doc/AO5059RD1.pdf
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: '',
    country: 'Germany',
    sun: 'No Impact',
    volume: false,
  },
  NRC: {
    id: 0,
    name: 'Croce del Nord, Italy',
    shortName: 'NRC',
    type: SpaceObjectType.BISTATIC_RADIO_TELESCOPE,
    lat: <Degrees>44.5208,
    lon: <Degrees>11.6469,
    alt: <Kilometers>0.025,
    obsminaz: <Degrees>89.1,
    obsmaxaz: <Degrees>90.9,
    obsminel: <Degrees>45,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>1700,
    obsminaz2: <Degrees>179.1,
    obsmaxaz2: <Degrees>180.9,
    obsminel2: <Degrees>45,
    obsmaxel2: <Degrees>90,
    obsminrange2: <Kilometers>0,
    obsmaxrange2: <Kilometers>1700,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>20000,
    url: '',
    country: 'Italy',
    sun: 'No Impact',
    volume: false,
  },
  TRO: {
    id: 0,
    name: 'RAF Troodos, United Kingdom',
    shortName: 'TRO',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>34.912778,
    lon: <Degrees>32.883889,
    alt: <Kilometers>0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>10,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: '',
    country: 'United Kingdom',
    sun: 'No Impact',
    volume: false,
  },
  SDT: {
    id: 0,
    name: 'ESA Space Debris Telescope, Spain',
    shortName: 'SDT',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>28.3,
    lon: <Degrees>-16.5097,
    alt: <Kilometers>0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>10,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    url: '',
    country: 'Spain',
    sun: 'No Impact',
    volume: false,
  },

  // //////////////////////
  // RUSSIAN RADARS
  // //////////////////////
  ARM: {
    id: 0,
    name: 'Armavir, Russia',
    shortName: 'ARM',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>44.925106,
    lon: <Degrees>40.983894,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>55, // All Information via russianforces.org
    obsmaxaz: <Degrees>295,
    obsminel: <Degrees>2,
    obsmaxel: <Degrees>60,
    obsminrange: <Kilometers>100,
    obsmaxrange: <Kilometers>4200,
    changeObjectInterval: <Milliseconds>1000,
    country: 'Russia',
    sun: 'No Impact',
    volume: false,

    zoom: 'leo',
  },
  BAL: {
    id: 0,
    name: 'Balkhash, Russia',
    shortName: 'BAL',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>46.603076,
    lon: <Degrees>74.530985,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>91, // All Information via russianforces.org
    obsmaxaz: <Degrees>151,
    obsminel: <Degrees>5.5,
    obsmaxel: <Degrees>34.5,
    obsminrange: <Kilometers>385,
    obsmaxrange: <Kilometers>4600,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'Russia',
    sun: 'No Impact',
    volume: false,
  },
  GAN: {
    id: 0,
    name: 'Gantsevichi, Russia',
    shortName: 'GAN',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>52.85,
    lon: <Degrees>26.48,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>190, // All Information via russianforces.org
    obsmaxaz: <Degrees>310,
    obsminel: <Degrees>3,
    obsmaxel: <Degrees>80,
    obsminrange: <Kilometers>300,
    obsmaxrange: <Kilometers>6500,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'Russia',
    sun: 'No Impact',
    volume: false,
  },
  LEK: {
    id: 0,
    name: 'Lekhtusi, Russia',
    shortName: 'LEK',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>60.275458,
    lon: <Degrees>30.546017,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>245,
    obsmaxaz: <Degrees>355,
    obsminel: <Degrees>2,
    obsmaxel: <Degrees>70,
    obsminrange: <Kilometers>100,
    obsmaxrange: <Kilometers>4200,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'Russia',
    sun: 'No Impact',
    volume: false,
  },
  MIS: {
    id: 0,
    name: 'Mishelevka-D, Russia',
    shortName: 'MIS',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>52.8555,
    lon: <Degrees>103.2317,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>41, // All Information via russianforces.org
    obsmaxaz: <Degrees>219,
    obsminel: <Degrees>5.5,
    obsmaxel: <Degrees>34.5,
    obsminrange: <Kilometers>250,
    obsmaxrange: <Kilometers>4600,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'Russia',
    sun: 'No Impact',
    volume: false,
  },
  OLE: {
    id: 0,
    name: 'Olenegorsk, Russia',
    shortName: 'OLE',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>68.1141,
    lon: <Degrees>33.9102,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>280, // All Information via russianforces.org
    obsmaxaz: <Degrees>340,
    obsminel: <Degrees>5.5,
    obsmaxel: <Degrees>34.5,
    obsminrange: <Kilometers>250,
    obsmaxrange: <Kilometers>4600,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'Russia',
    sun: 'No Impact',
    volume: false,
  },
  PEC: {
    id: 0,
    name: 'Pechora, Russia',
    shortName: 'PEC',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>65.21,
    lon: <Degrees>57.295,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>305, // All Information via russianforces.org
    obsmaxaz: <Degrees>55,
    obsminel: <Degrees>2,
    obsmaxel: <Degrees>55,
    obsminrange: <Kilometers>300,
    obsmaxrange: <Kilometers>7200,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'Russia',
    sun: 'No Impact',
    volume: false,
  },
  PIO: {
    id: 0,
    name: 'Pionersky, Russia',
    shortName: 'PIO',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>54.857294,
    lon: <Degrees>20.18235,
    alt: <Kilometers>0.0,
    obsminaz: <Degrees>187.5, // All Information via russianforces.org
    obsmaxaz: <Degrees>292.5,
    obsminel: <Degrees>2,
    obsmaxel: <Degrees>60,
    obsminrange: <Kilometers>100,
    obsmaxrange: <Kilometers>4200,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'Russia',
    sun: 'No Impact',
    volume: false,
  },
  // XUA: { // Not operational anymore
  //   id: 0,
  //   name: 'Xuanhua, China',
  //   shortName: 'XUA',
  //   type: SpaceObjectType.PHASED_ARRAY_RADAR,
  //   lat: <Degrees>40.446944,
  //   lon: <Degrees>115.116389,
  //   alt: <Kilometers>1.6,
  //   obsminaz: <Degrees>300, // Information via global ssa sensors amos 2010.pdf (sinodefence.com/special/airdefense/project640.asp)
  //   obsmaxaz: <Degrees>60, // Information via global ssa sensors amos 2010.pdf (sinodefence.com/special/airdefense/project640.asp)
  //   obsminel: <Degrees>2, // Information via globalsecurity.org
  //   obsmaxel: <Degrees>80, // Information via globalsecurity.org
  //   obsminrange: <Kilometers>300,
  //   obsmaxrange: <Kilometers>3000, // Information via global ssa sensors amos 2010.pdf (sinodefence.com/special/airdefense/project640.asp)
  //   zoom: 'leo',
  //   changeObjectInterval: <Milliseconds>1000,
  //   country: 'China',
  //   sun: 'No Impact',
  //   volume: false,
  // },
  XIN: {
    id: 0,
    name: 'Xingjiang, China', // Korla
    shortName: 'XIN',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>41.64131987863126, // https://hfasia.blogspot.com/2017/02/blog-post_50.html
    lon: <Degrees>86.23695312232473,
    alt: <Kilometers>0.993, // https://www.freemaptools.com/elevation-finder.htm
    obsminaz: <Degrees>0, // https://www.globalsecurity.org/space/world/china/images/xinjiang-radar-image-2018-1-s.jpg
    obsmaxaz: <Degrees>360, // It is on a rotatable platform
    obsminel: <Degrees>3, // Assumed same characteristics as AN/FPS-115
    obsmaxel: <Degrees>85,
    obsminrange: <Kilometers>200, // Assumed same characteristics as AN/FPS-115
    obsmaxrange: <Kilometers>5556, // Assumed same characteristics as AN/FPS-115
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'China',
    sun: 'No Impact',
    volume: false,
  },
  ZHE: {
    id: 0,
    name: 'Zhejiang, China',
    shortName: 'ZHE',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>30.28661248844618, // https://hfasia.blogspot.com/2017/02/blog-post_50.html
    lon: <Degrees>119.12859385017512,
    alt: <Kilometers>1.342, // https://www.freemaptools.com/elevation-finder.htm
    obsminaz: <Degrees>60,
    obsmaxaz: <Degrees>300,
    obsminel: <Degrees>2,
    obsmaxel: <Degrees>80,
    obsminrange: <Kilometers>300,
    obsmaxrange: <Kilometers>3000,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'China',
    sun: 'No Impact',
    volume: false,
  },
  HEI: {
    id: 0,
    name: 'Heilongjiang, China',
    shortName: 'HEI',
    type: SpaceObjectType.PHASED_ARRAY_RADAR, // https://www.globalsecurity.org/wmd/world/china/lpar-x.htm
    lat: <Degrees>46.528164,
    lon: <Degrees>130.755235,
    alt: <Kilometers>0.241, // https://www.freemaptools.com/elevation-finder.htm
    obsminaz: <Degrees>135, // X-Band https://www.globalsecurity.org/wmd/world/china/lpar-x.htm
    obsmaxaz: <Degrees>225, // Assumed +/- 45 degrees
    obsminel: <Degrees>3,
    obsmaxel: <Degrees>65,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>3000,
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'China',
    sun: 'No Impact',
    volume: false,
  },
  SHD: {
    id: 0,
    name: 'Shandong, China', // P-Band (225 Mhz - 390 Mhz)
    shortName: 'SHD',
    type: SpaceObjectType.PHASED_ARRAY_RADAR, // https://www.globalsecurity.org/wmd/world/china/lpar-p.htm
    lat: <Degrees>36.023072,
    lon: <Degrees>118.093115,
    alt: <Kilometers>0.694, // https://www.freemaptools.com/elevation-finder.htm
    obsminaz: <Degrees>343.9, // Two Faces Boresight ~163.9 and ~103.9 degrees
    // https://www.omnicalculator.com/other/azimuth (163.9 degrees if aimed at Taipei)
    obsmaxaz: <Degrees>223.9, // https://www.defensenews.com/global/asia-pacific/2022/04/18/new-chinese-radar-looks-towards-japan-satellite-image-shows/
    obsminel: <Degrees>3,
    obsmaxel: <Degrees>85,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>5500, // ~10,000 Transceivers
    zoom: 'leo',
    changeObjectInterval: <Milliseconds>1000,
    country: 'China',
    sun: 'No Impact',
    volume: false,
  },

  // Telescopes
  MLS: {
    id: 0,
    name: 'Mount Lemmon Survey, Arizona',
    shortName: 'MLS',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>32.442,
    lon: <Degrees>-110.789,
    alt: <Kilometers>2.791,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>10,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },

  PMO: {
    id: 0,
    name: 'Purple Mountain Observatory, China',
    shortName: 'PMO',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>32.064946,
    lon: <Degrees>118.829677,
    alt: <Kilometers>0.267,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>10,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    country: 'China',
    sun: 'No Impact',
    volume: false,
  },

  PO: {
    id: 0,
    name: 'Palomar Observatory, California',
    shortName: 'PO',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>33.3564,
    lon: <Degrees>-116.865,
    alt: <Kilometers>1.712,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>10,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    country: 'United States',
    sun: 'No Impact',
    volume: false,
  },

  LSO: {
    id: 0,
    name: 'La Sagra Observatory, Spain',
    shortName: 'LSO',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>37.9839,
    lon: <Degrees>-2.5644,
    alt: <Kilometers>0,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>10,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    country: 'Spain',
    sun: 'No Impact',
    volume: false,
  },

  // ISON Sensors
  MAY: {
    id: 0,
    name: 'Mayhill, New Mexico',
    shortName: 'MAY',
    type: SpaceObjectType.OPTICAL,
    lat: <Degrees>32.9039,
    lon: <Degrees>-105.5289,
    alt: <Kilometers>2.225,
    obsminaz: <Degrees>0,
    obsmaxaz: <Degrees>360,
    obsminel: <Degrees>10,
    obsmaxel: <Degrees>90,
    obsminrange: <Kilometers>0,
    obsmaxrange: <Kilometers>200000,
    zoom: 'geo',
    changeObjectInterval: <Milliseconds>20000,
    country: 'USA',
    sun: 'No Impact',
    volume: false,
  },
  TAI: {
    id: 0,
    name: 'Surveillance Radar Program, Taiwan',
    shortName: 'TAI',
    type: SpaceObjectType.PHASED_ARRAY_RADAR,
    lat: <Degrees>24.499,
    lon: <Degrees>121.072,
    alt: <Kilometers>0.060966, // Find accurate altitude
    obsminaz: <Degrees>0, // Appears to be 3 faced
    obsmaxaz: <Degrees>360, // https://www.google.com/maps/place/24%C2%B029'45.6%22N+121%C2%B004'15.6%22E/@24.4985462,121.0709751,154m/data=!3m1!1e3!4m5!3m4!1s0x0:0xe0073e890dc05d63!8m2!3d24.496!4d121.071
    obsminel: <Degrees>-1, // "Tracks surface ships" https://www.globalsecurity.org/military/world/taiwan/air-defense-over.htm
    obsmaxel: <Degrees>85,
    obsminrange: <Kilometers>200,
    obsmaxrange: <Kilometers>5556,
    changeObjectInterval: <Milliseconds>1000,
    linkAehf: false,
    linkWgs: false,
    zoom: 'leo',
    url: 'https://fas.org/man/eprint/leshan.pdf',
    country: 'Taiwan',
    sun: 'No Impact',
    volume: false,
  },
};

let i = 0;
for (const sensor in sensors_) {
  sensors_[sensor].staticNum = i;
  i++;
}

export { sensors_ as sensors };
