import { vi } from 'vitest';
// Generated by CodiumAI

import { PluginRegistry } from '@app/engine/core/plugin-registry';
import { ServiceLocator } from '@app/engine/core/service-locator';
import { EventBus } from '@app/engine/events/event-bus';
import { EventBusEvent } from '@app/engine/events/event-bus-events';
import { UrlManager } from '@app/engine/input/url-manager';
import { SelectSatManager } from '@app/plugins/select-sat-manager/select-sat-manager';
import { BaseObject, CatalogSource } from '@ootk/src/main';
import { setupStandardEnvironment } from '@test/environment/standard-env';

/**
 * Mock window.location for testing using vi.stubGlobal
 * Note: These tests may need refactoring as JSDOM's window.location is non-configurable
 * and may not properly reflect the stubbed global.location value.
 */
function mockWindowLocation(url: string) {
  const urlObj = new URL(url);

  vi.stubGlobal('location', {
    href: urlObj.href,
    origin: urlObj.origin,
    protocol: urlObj.protocol,
    host: urlObj.host,
    hostname: urlObj.hostname,
    port: urlObj.port,
    pathname: urlObj.pathname,
    search: urlObj.search,
    hash: urlObj.hash,
    ancestorOrigins: [],
    assign: vi.fn(),
    reload: vi.fn(),
    replace: vi.fn(),
    toString: () => urlObj.href,
  });
}

describe('UrlManager_class', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  // Tests that URL parameters with valid satellite and search values are parsed correctly
  // TODO: These tests need refactoring - JSDOM's window.location is non-configurable in Vitest
  // Consider refactoring UrlManager to accept location as a dependency for better testability
  it.skip('should_parse_valid_satellite_and_search_params', () => {
    const url = 'http://localhost:5544/?sat=25544&search=ISS&rate=1.0&date=1630512000000';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const expectedSelectedSat = 25544;
    const expectedCurrentSearch = 'ISS';
    const expectedPropRate = 1;
    // const expectedStaticOffset = 1630512000000 - Date.now();
    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();
    const timeManagerInstance = ServiceLocator.getTimeManager();

    vi.spyOn(window.history, 'replaceState').mockImplementation(() => {
      // noop
    });
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }

    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.sccNum2Id = (objNum: number) => objNum;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    EventBus.getInstance().emit(EventBusEvent.uiManagerInit);
    EventBus.getInstance().emit(EventBusEvent.uiManagerFinal);

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(selectedSatelliteManager.selectSat).toHaveBeenCalledWith(expectedSelectedSat);
    expect(uiManagerInstance.doSearch).toHaveBeenCalledWith(expectedCurrentSearch);
    expect(timeManagerInstance.propRate).toBe(expectedPropRate);
    // TODO: Handle the timer in parse_valid_params

    // expect(timeManagerInstance.staticOffset).toBe(expectedStaticOffset);
  });

  // Tests that intldes parameter with valid value is parsed correctly
  // TODO: Needs refactoring for Vitest - see test above
  it.skip('test_parse_valid_params', () => {
    const url = 'http://localhost:5544/?intldes=1988-064A';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const expectedSelectedSat = 10;
    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();

    vi.spyOn(window.history, 'replaceState').mockImplementation(() => {
      // noop
    });
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }

    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.intlDes2id = () => 10;
    catalogManagerInstance.getObject = () => ({ id: '10', sccNum: '25544', active: true }) as unknown as BaseObject;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(selectedSatelliteManager.selectSat).toHaveBeenCalledWith(expectedSelectedSat);
  });

  // Tests that URL parameters valid but satellite not found
  // TODO: Needs refactoring for Vitest - see test above
  it.skip('test_parse_valid_params_sat_not_found', () => {
    const url = 'http://localhost:5544/?intldes=1988-064A';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();

    vi.spyOn(window.history, 'replaceState').mockImplementation(() => {
      // noop
    });
    uiManagerInstance.toast = vi.fn();
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }

    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.intlDes2id = () => null;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(uiManagerInstance.toast).toHaveBeenCalled();
  });

  // Tests that URL parameters valid but satellite not found2
  // TODO: Needs refactoring for Vitest - see test above
  it.skip('test_parse_valid_params_sat_not_found2', () => {
    const url = 'http://localhost:5544/?sat=99999';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();

    vi.spyOn(window.history, 'replaceState').mockImplementation(() => {
      // noop
    });
    uiManagerInstance.toast = vi.fn();
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }

    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.sccNum2Id = () => null;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(uiManagerInstance.toast).toHaveBeenCalled();
  });

  // Tests that URL parameters with empty parameters are parsed correctly
  it('test_parse_empty_params', () => {
    const url = 'http://localhost:5544/';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const expectedSelectedSat = 25544;
    const expectedCurrentSearch = 'ISS';
    const expectedPropRate = 1;
    const expectedStaticOffset = 1630512000000 - Date.now();
    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();
    const timeManagerInstance = ServiceLocator.getTimeManager();

    vi.spyOn(window.history, 'replaceState').mockImplementation(() => {
      // noop
    });
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }
    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.sccNum2Id = (objNum: number) => objNum;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(selectedSatelliteManager.selectSat).not.toHaveBeenCalledWith(expectedSelectedSat);
    expect(uiManagerInstance.doSearch).not.toHaveBeenCalledWith(expectedCurrentSearch);
    expect(timeManagerInstance.propRate).toBe(expectedPropRate);
    expect(timeManagerInstance.staticOffset).not.toBe(expectedStaticOffset);
  });

  // Tests that URL parameters with invalid parameters are not parsed
  // TODO: Needs refactoring for Vitest - see test above
  it.skip('test_parse_invalid_params', () => {
    const url = 'http://localhost:5544/?sat=invalid&search=ISS&rate=invalid&date=invalid';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const expectedSelectedSat = 25544;
    const expectedCurrentSearch = 'ISS';
    const expectedPropRate = 1;
    const expectedStaticOffset = 1630512000000 - Date.now();
    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();
    const timeManagerInstance = ServiceLocator.getTimeManager();

    vi.spyOn(window.history, 'replaceState').mockImplementation(() => {
      // noop
    });
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }
    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.sccNum2Id = (objNum: number) => objNum;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(selectedSatelliteManager.selectSat).not.toHaveBeenCalledWith(expectedSelectedSat);
    expect(uiManagerInstance.doSearch).toHaveBeenCalledWith(expectedCurrentSearch);
    expect(timeManagerInstance.propRate).toBe(expectedPropRate);
    expect(timeManagerInstance.staticOffset).not.toBe(expectedStaticOffset);
  });

  // Test missile params are parsed correctly
  it.todo('test_parse_missile_params');
});

/*
 * Pure-logic coverage for the JSC Vimpel deep-link paths. These deliberately
 * avoid window.location (non-configurable under JSDOM/Vitest) by exercising
 * the extracted helpers and the sat-param handler directly.
 */
describe('UrlManager Vimpel sat param', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  describe('buildSatParamValue', () => {
    it('returns the sccNum for a NORAD-cataloged satellite', () => {
      expect(UrlManager.buildSatParamValue({ sccNum: '25544', altId: '', source: CatalogSource.CELESTRAK })).toBe('25544');
    });

    it('returns JV<altId> for a Vimpel satellite without a sccNum', () => {
      expect(UrlManager.buildSatParamValue({ sccNum: '', altId: '12345', source: CatalogSource.VIMPEL })).toBe('JV12345');
    });

    it('prefers the sccNum even when an altId is present', () => {
      expect(UrlManager.buildSatParamValue({ sccNum: '25544', altId: '12345', source: CatalogSource.VIMPEL })).toBe('25544');
    });

    it('does not use the altId when the source is not Vimpel', () => {
      expect(UrlManager.buildSatParamValue({ sccNum: '', altId: 'EXTERNAL_SAT', source: CatalogSource.CELESTRAK })).toBeNull();
    });

    it('returns null for null input or a satellite with no shareable id', () => {
      expect(UrlManager.buildSatParamValue(null)).toBeNull();
      expect(UrlManager.buildSatParamValue({ sccNum: '', altId: '', source: CatalogSource.VIMPEL })).toBeNull();
    });
  });

  describe('parseVimpelSatParam', () => {
    it('extracts the altId from a JV-prefixed value', () => {
      expect(UrlManager.parseVimpelSatParam('JV12345')).toBe('12345');
    });

    it('is case-insensitive and tolerates surrounding whitespace', () => {
      expect(UrlManager.parseVimpelSatParam(' jv12345 ')).toBe('12345');
    });

    it('returns null for a plain NORAD sccNum', () => {
      expect(UrlManager.parseVimpelSatParam('25544')).toBeNull();
    });

    it('returns null for an alpha-5 id (one letter + four digits)', () => {
      expect(UrlManager.parseVimpelSatParam('T0001')).toBeNull();
    });

    it('returns null for a bare or empty JV prefix', () => {
      expect(UrlManager.parseVimpelSatParam('JV')).toBeNull();
      expect(UrlManager.parseVimpelSatParam('JV  ')).toBeNull();
      expect(UrlManager.parseVimpelSatParam('')).toBeNull();
    });
  });

  it('round-trips: a generated Vimpel sat param parses back to the same altId', () => {
    const value = UrlManager.buildSatParamValue({ sccNum: '', altId: '9906205', source: CatalogSource.VIMPEL });

    expect(value).toBe('JV9906205');
    expect(UrlManager.parseVimpelSatParam(value!)).toBe('9906205');
  });

  describe('handleSatParam_ Vimpel routing', () => {
    // Access the private handler without going through parseGetVariables
    // (which reads window.location).
    const callHandleSatParam = (val: string) => {
      (UrlManager as unknown as { handleSatParam_(v: string): void }).handleSatParam_(val);
    };

    it('selects the Vimpel object resolved from a JV-prefixed sat param', () => {
      setupStandardEnvironment([SelectSatManager]);

      const catalogManagerInstance = ServiceLocator.getCatalogManager();
      const selectSatManager = PluginRegistry.getPlugin(SelectSatManager);

      expect(selectSatManager).not.toBeNull();
      if (!selectSatManager) {
        throw new Error('SelectSatManager is null');
      }

      selectSatManager.selectSat = vi.fn();
      catalogManagerInstance.vimpelId2Id = vi.fn((altId: string) => (altId === '12345' ? 42 : null));
      catalogManagerInstance.sccNum2Id = vi.fn(() => null);

      callHandleSatParam('JV12345');

      expect(catalogManagerInstance.vimpelId2Id).toHaveBeenCalledWith('12345');
      expect(selectSatManager.selectSat).toHaveBeenCalledWith(42);
      // The sccNum path must not run for a JV-prefixed value.
      expect(catalogManagerInstance.sccNum2Id).not.toHaveBeenCalled();
    });

    it('toasts when a JV-prefixed sat param does not resolve', () => {
      setupStandardEnvironment([SelectSatManager]);

      const catalogManagerInstance = ServiceLocator.getCatalogManager();
      const uiManagerInstance = ServiceLocator.getUiManager();
      const selectSatManager = PluginRegistry.getPlugin(SelectSatManager);

      expect(selectSatManager).not.toBeNull();
      if (!selectSatManager) {
        throw new Error('SelectSatManager is null');
      }

      selectSatManager.selectSat = vi.fn();
      uiManagerInstance.toast = vi.fn();
      catalogManagerInstance.vimpelId2Id = vi.fn(() => null);

      callHandleSatParam('JV99999');

      expect(uiManagerInstance.toast).toHaveBeenCalled();
      expect(selectSatManager.selectSat).not.toHaveBeenCalled();
    });
  });
});
