import { vi } from 'vitest';
// Generated by CodiumAI

import { PluginRegistry } from '@app/engine/core/plugin-registry';
import { EventBusEvent } from '@app/engine/events/event-bus-events';
import { UrlManager } from '@app/engine/input/url-manager';
import { SelectSatManager } from '@app/plugins/select-sat-manager/select-sat-manager';
import { BaseObject } from '@ootk/src/main';
import { setupStandardEnvironment } from '@test/environment/standard-env';
import { ServiceLocator } from '@app/engine/core/service-locator';
import { EventBus } from '@app/engine/events/event-bus';

/**
 * Mock window.location for testing using vi.stubGlobal
 * Note: These tests may need refactoring as JSDOM's window.location is non-configurable
 * and may not properly reflect the stubbed global.location value.
 */
function mockWindowLocation(url: string) {
  const urlObj = new URL(url);

  vi.stubGlobal('location', {
    href: urlObj.href,
    origin: urlObj.origin,
    protocol: urlObj.protocol,
    host: urlObj.host,
    hostname: urlObj.hostname,
    port: urlObj.port,
    pathname: urlObj.pathname,
    search: urlObj.search,
    hash: urlObj.hash,
    ancestorOrigins: [],
    assign: vi.fn(),
    reload: vi.fn(),
    replace: vi.fn(),
    toString: () => urlObj.href,
  });
}

describe('UrlManager_class', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  // Tests that URL parameters with valid satellite and search values are parsed correctly
  // TODO: These tests need refactoring - JSDOM's window.location is non-configurable in Vitest
  // Consider refactoring UrlManager to accept location as a dependency for better testability
  it.skip('should_parse_valid_satellite_and_search_params', () => {
    const url = 'http://localhost:5544/?sat=25544&search=ISS&rate=1.0&date=1630512000000';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const expectedSelectedSat = 25544;
    const expectedCurrentSearch = 'ISS';
    const expectedPropRate = 1;
    // const expectedStaticOffset = 1630512000000 - Date.now();
    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();
    const timeManagerInstance = ServiceLocator.getTimeManager();

    // eslint-disable-next-line no-empty-function
    vi.spyOn(window.history, 'replaceState').mockImplementation(() => { });
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }

    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.sccNum2Id = (objNum: number) => objNum;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    EventBus.getInstance().emit(EventBusEvent.uiManagerInit);
    EventBus.getInstance().emit(EventBusEvent.uiManagerFinal);

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(selectedSatelliteManager.selectSat).toHaveBeenCalledWith(expectedSelectedSat);
    expect(uiManagerInstance.doSearch).toHaveBeenCalledWith(expectedCurrentSearch);
    expect(timeManagerInstance.propRate).toBe(expectedPropRate);
    // TODO: Handle the timer in parse_valid_params

    // expect(timeManagerInstance.staticOffset).toBe(expectedStaticOffset);
  });

  // Tests that intldes parameter with valid value is parsed correctly
  // TODO: Needs refactoring for Vitest - see test above
  it.skip('test_parse_valid_params', () => {
    const url = 'http://localhost:5544/?intldes=1988-064A';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const expectedSelectedSat = 10;
    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();

    // eslint-disable-next-line no-empty-function
    vi.spyOn(window.history, 'replaceState').mockImplementation(() => { });
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }

    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.intlDes2id = () => 10;
    catalogManagerInstance.getObject = () => ({ id: '10', sccNum: '25544', active: true }) as unknown as BaseObject;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(selectedSatelliteManager.selectSat).toHaveBeenCalledWith(expectedSelectedSat);
  });

  // Tests that URL parameters valid but satellite not found
  // TODO: Needs refactoring for Vitest - see test above
  it.skip('test_parse_valid_params_sat_not_found', () => {
    const url = 'http://localhost:5544/?intldes=1988-064A';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();

    // eslint-disable-next-line no-empty-function
    vi.spyOn(window.history, 'replaceState').mockImplementation(() => { });
    uiManagerInstance.toast = vi.fn();
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }

    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.intlDes2id = () => null;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(uiManagerInstance.toast).toHaveBeenCalled();
  });

  // Tests that URL parameters valid but satellite not found2
  // TODO: Needs refactoring for Vitest - see test above
  it.skip('test_parse_valid_params_sat_not_found2', () => {
    const url = 'http://localhost:5544/?sat=99999';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();

    // eslint-disable-next-line no-empty-function
    vi.spyOn(window.history, 'replaceState').mockImplementation(() => { });
    uiManagerInstance.toast = vi.fn();
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }

    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.sccNum2Id = () => null;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(uiManagerInstance.toast).toHaveBeenCalled();
  });

  // Tests that URL parameters with empty parameters are parsed correctly
  it('test_parse_empty_params', () => {
    const url = 'http://localhost:5544/';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const expectedSelectedSat = 25544;
    const expectedCurrentSearch = 'ISS';
    const expectedPropRate = 1;
    const expectedStaticOffset = 1630512000000 - Date.now();
    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();
    const timeManagerInstance = ServiceLocator.getTimeManager();

    // eslint-disable-next-line no-empty-function
    vi.spyOn(window.history, 'replaceState').mockImplementation(() => { });
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }
    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.sccNum2Id = (objNum: number) => objNum;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(selectedSatelliteManager.selectSat).not.toHaveBeenCalledWith(expectedSelectedSat);
    expect(uiManagerInstance.doSearch).not.toHaveBeenCalledWith(expectedCurrentSearch);
    expect(timeManagerInstance.propRate).toBe(expectedPropRate);
    expect(timeManagerInstance.staticOffset).not.toBe(expectedStaticOffset);
  });

  // Tests that URL parameters with invalid parameters are not parsed
  // TODO: Needs refactoring for Vitest - see test above
  it.skip('test_parse_invalid_params', () => {
    const url = 'http://localhost:5544/?sat=invalid&search=ISS&rate=invalid&date=invalid';

    setupStandardEnvironment([SelectSatManager]);
    mockWindowLocation(url);

    const expectedSelectedSat = 25544;
    const expectedCurrentSearch = 'ISS';
    const expectedPropRate = 1;
    const expectedStaticOffset = 1630512000000 - Date.now();
    const catalogManagerInstance = ServiceLocator.getCatalogManager();
    const uiManagerInstance = ServiceLocator.getUiManager();
    const timeManagerInstance = ServiceLocator.getTimeManager();

    // eslint-disable-next-line no-empty-function
    vi.spyOn(window.history, 'replaceState').mockImplementation(() => { });
    const selectedSatelliteManager = PluginRegistry.getPlugin(SelectSatManager);

    expect(selectedSatelliteManager).toBeDefined();
    expect(selectedSatelliteManager).not.toBeNull();

    if (!selectedSatelliteManager) {
      throw new Error('SelectedSatelliteManager is null');
    }
    selectedSatelliteManager.selectSat = vi.fn();
    catalogManagerInstance.sccNum2Id = (objNum: number) => objNum;
    uiManagerInstance.doSearch = vi.fn();
    uiManagerInstance.searchManager.hideResults = vi.fn();

    UrlManager.parseGetVariables(settingsManager);
    EventBus.getInstance().emit(EventBusEvent.onKeepTrackReady);

    expect(selectedSatelliteManager.selectSat).not.toHaveBeenCalledWith(expectedSelectedSat);
    expect(uiManagerInstance.doSearch).toHaveBeenCalledWith(expectedCurrentSearch);
    expect(timeManagerInstance.propRate).toBe(expectedPropRate);
    expect(timeManagerInstance.staticOffset).not.toBe(expectedStaticOffset);
  });

  // Test missile params are parsed correctly
  it.todo('test_parse_missile_params');
});
